### ISSUE TITLE
Simplify Figure component tests & stories

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1028]
Currently the [Figure component fixture data](https://github.com/BBC-News/simorgh/blob/latest/src/app/components/Figure/fixtureData.jsx) file pulls in the Figure _container_. This is an issue ahead of potentially pulling the figure component out.

Furthermore, these tests make a number of assumptions based on the pre-fragment data feed, that blocks work like #801.

---

Suspect the sensible approach will be to turn the component tests into very simple snapshot tests (as many of the Figure components are already near-pure) & have more thorough container tests -- potentially using deep snapshots if that is the only way to fully check if content is rendered correctly all the way down.

**Comment by sareh** [comment]
- Figure component storybook entry should have a simple entry, not one composed with the image, caption and copyright 
- Figure component should have a snapshot test using deep rendering: `shouldMatchSnapshot` 
- Figure Container storybook entry in Simorgh should have several stories:
```
with a caption
without a caption
with a caption containing a link
with non-BBC copyright
with a caption and non-BBC copyright
```
- Figure container should have a snapshot test using deep rendering: `shouldMatchSnapshot`. This is to capture the composition of Figure, Image, Caption and Copyright.

**Comment by pjlee11** [comment]
`with a caption containing a link` is blocked on #801  which seems blocked for the short/medium term on UX designs

**Comment by bcmn** [comment]
> `with a caption containing a link` is blocked on #801 which seems blocked for the short/medium term on UX designs

I believe that was removed as part of #1025, @pjlee11.

**Comment by bcmn** [comment]
> `with a caption containing a link` is blocked on #801 which seems blocked for the short/medium term on UX designs

@pjlee11 I would advocate for testing the current implementation & updating when UX requirements change, given using fragments for Figure captions blocks removing the Text component.

**Comment by pjlee11** [comment]
@bcmn I agree, what I meant is we should remove `with a caption containing a link` because that is not current a valid implementation, due to the logic of rendering a caption only using the raw text value. [Image container](https://github.com/BBC-News/simorgh/blob/824b04ea25d1b8418142014ab45a81a4158219f4/src/app/containers/Image/index.jsx#L8) passes pulls data from the JSON, then injects it into FigureContainer which renders the Caption.

**Comment by ChrisBAshton** [comment]
Just spoke with Ben - what he's been doing is:

1. make Text component redundant in X
2. make Text component redundant in Caption (thereby just rendering 'raw' text direct from a prop)

He could then either:

a) remove the inline link examples, or
b) change the 'raw' prop usage and pass to fragment blocks instead, thereby supporting the inline-link use case

It sounds from Ben that option b) really isn't much work, and we'll be doing it anyway, _and_ it makes Caption consistent with other components that operate in a similar way, and we'd then need to add the inline link tests back in.

Have asked him to proceed with b) for now - let's see how it looks in the PR.

**Comment by pjlee11** [comment]
My opinion is that option B although at a glance looks like the correct choice actually is not. 

We purposefully chose not to implement fragments in the Caption component, when moving away from markdown, due to the UX designs needing to be updated as they currently produce visual bugs in certain use cases. The [implementation of rich text in Captions](https://github.com/BBC-News/simorgh/issues/801) is therefore blocked on UX. 

Therefore it's actually a matter of implementing a known bug at the benefit of increased component consistency. That said, I'd advocate option a, OR an third option - keep the examples but remove the tests and stories.
