### ISSUE TITLE
Meta published/modified time is wrong

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1158]
**Describe the bug**
Articles show `<meta data-react-helmet="true" name="article:modified_time" content="2018-01-01T13:00:00.000Z"/>` and `<meta data-react-helmet="true" name="article:published_time" content="2018-01-01T12:01:00.000Z"/>` which are not the `firstPublished` and `lastPublished` time returned by Ares.

**To Reproduce**

1. Visit an article
2. View source
3. Search for `article:published_time`

**Expected behavior**
The time shown is the correct time from Ares

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by bcmn** [comment]
At least one part of this issue seems to originate from the fact [we are using `lastUpdated`, not `lastPublished` in the Metadata container](https://github.com/BBC-News/simorgh/blob/3a9bf11b0cb23b917e48e1e263e97658dafa42f1/src/app/containers/Metadata/index.jsx#L28).

**Comment by jimjohnsonrollings** [comment]
To be fair, `lastUpdated` might be the right field, although the values in cxm45v3m4vlo seem a bit off if this is the case:

`    "lastUpdated": 1541594684712,
    "firstPublished": 1536153827628,
    "lastPublished": 1536153827628,`

**Comment by bcmn** [comment]
Second part of this issue is related to the fact that TEST Simorgh is currently pointing to `localhost`, & not `https://www.test.bbc.com`. This can be verified by attempting to view any Optimo article ID that does not have a correlating file in `/data/prod`. This is a symptom of [this simorgh-infrastructure issue](https://github.com/bbc/simorgh-infrastructure/issues/194).

**Comment by bcmn** [comment]
`lastUpdated` seems to be added by Ares, `lastPublished` should be used instead.
