### ISSUE TITLE
Investigate font loading strategies

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1178]
**Is your feature request related to a problem? Please describe.**
Im convinced the font issue isn't an issue, but a feature of us using `font-display: optional;`
The font simply isn't fast enough to load first time.

Task: Propose a new solution and agree it with Devs, UX and Product.

AFAIK we have the main options of `auto`, `FOUT`, `FOIT` or `optional`.

**Describe the solution you'd like**
Investigate alternatives to our current font display setting and the implications of using them.

**Describe alternatives you've considered**
We could keep the current font-display setting but try preloading the font.

**Additional context**
NB: this issue is associated with #1009, #1169 and #1053, and the outcome of this investigation is likely to be a solution that fixes all 3.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
The font not loading on the first page load is an intentional choice, to ensure that the font-loading is not render-blocking for the first page load.  This enhances the experience for people on flaky or slow connections. 
This was agreed between development, Product and UX several months ago as the agreed approach.
