### ISSUE TITLE
Separate assets for different environments

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1207]
**Is your feature request related to a problem? Please describe.**
We should have assets for test and live environments in separate directories. This will enable us to easily deploy Test assets to the Test S3 bucket and Live assets to the Live one. 

**Describe the solution you'd like**
Built assets should be in directories `build/local`, `build/test` or `build/live` depending on the APP_ENV value. The default should be to use `build/local`.

**Testing notes**
Regression testing of each build (by pointing local to the different environments (`npm run build && APP_ENV=test npm run start` & `npm run build && APP_ENV=live npm run start`)). Addition of Cypress tests will be decided upon after Cypress Test Meeting on Monday 11th Feb.

Dev insight: We should test manually and also consider adding a cypress test to check that assets are generated in correct directories, after an `npm run build`

This issue is a breaking change and pairs with https://github.com/bbc/simorgh-infrastructure/issues/255 which must be merged at the same time.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Myself and Drew spoke about this. It will require a parallel infra change because the Jenkinsfile handles the zipping of the public file and deployment of the static assets. This issue requires changing the location of the static assets from `public/` to `build/test` or `build/live`. 

Drew stated that we should evaluate the naming of the files once put into S3, as currently, we believe the name of the directory containing the file is used at the root of the file S3 asset name. EG: the S3 asset `public/static/js/main-******.js` is because we currently target the `public` dir. 

1) If we were to target `test/` which is homed in `build/` the S3 asset would be `test/static/js/main-******.js`

2) If we were to target `public/` which is homed in `build/test/` the S3 asset would be  `public/static/js/main-******.js` which is consistent with the current S3 assets.

We should use 2 for consistency with the current asset naming.

Therefore webpack should output the build to the corresponding directory based on `APP_ENV` and we should have `public` directory for each test and live. EG: `build/test/public`

**Comment by jamesbhobbs** [comment]
@sareh what is the use case for this? Or better what is the business value?

**Comment by sareh** [comment]
This is an outdated issue and I'm closing it as it is no longer needed.
