### ISSUE TITLE
Catch & handle unmatched route error specifically

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1253]
**Is your feature request related to a problem? Please describe.**
Following #1244, the final express route is set to the article regex. Ideally, we would like t be able to set this to `/*` & catch the unmatched route error thrown by react-universal-app (or it's replacement) granularly, in order to return a 404, while still returning a 500 for any unexpected errors. 

**Describe the solution you'd like**
To do this, it would need to throw an error object with a specific name, that the catch could branch on to return a 404.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Just to confirm under what circumstances this might be useful, @bcmn ...

* Server-side renders will only ever be legit (i.e. Mozart do validation for us and will never request Simorgh to render anything abnormal).
* Client-side renders will only happen if users click on valid Simorgh routes, i.e. `/news/articles/{regex}`. Other links (e.g. `/programmes`) will be treated as normal.

So if the user clicks on a valid Simorgh route that is somehow a 404, the issue is _we are currently serving a 500 error instead of a 404_. Have I understood the crux of what this issue is getting at?

**Comment by bcmn** [comment]
I believe so -- I think it's quite minor, particularly accounting for likelihood to occur. 

My understanding is that the wrong error code would be sent if any unexpected URL was requested from the Simorgh router. But as you say, this is significantly mitigated on the server-side, & would seem to be very unusual for the client -- especially given the logic in the InlineLink containers.

I think the reason we created this ticket was as much a _principle_ as anything -- the behaviour felt incorrect, but maybe highlights the need for work like #211 instead.

EDIT: It sounds like @dr3 has more thoughts on this -- sounds like the above is simply the visible aspect of some of the weirdness of the post-`Universal React App` routing system. I defer to him 😉

**Comment by jamesbhobbs** [comment]
Superseded https://github.com/bbc/simorgh/issues/1544
