### ISSUE TITLE
MVP v1 Image Captions Layout

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1369]
~~BLOCKED On https://github.com/bbc/simorgh/issues/1318~~ #1318 is done. Now we can continue:

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
**GEL Group 1 (0-399px)**
**GEL Group 2 (400-599px)**

All:
Caption spans 6 columns, starting column 1.

**GEL Group 3 (600-1007px)**
Landscape:
caption spans 5 columns, starting column 1.

Portrait:
Caption spans 4 columns, starting column 1.

Square:
caption spans 5 columns, starting column 1.

**GEL Group 4 (1008-1279px)**
Landscape:
caption spans 5 columns, starting column 2.

Portrait:
Caption spans 3 columns, starting column 2.

Square:
caption spans 5 columns, starting column 2.

**GEL Group 5 (1280px+)**
Landscape:
 caption spans 10 columns, starting column 5.

Portrait:
Caption spans 8 columns, starting column 5.

Square:
 caption spans 10 columns, starting column 5.

**Testing notes**
Regression testing across browsers/devices to make sure this is working and nothing has regressed. Test across several device sizes (phone, tablet, desktop (responsive)). Again, screenshot testing would be great for this if we're able to implement it in time.

Dev insight: Snapshot tests should be updated. The main test would be to manually check that the content matches up to the designs. IE9 will not be fixed with this logic. This will be dealt within #821 .

**Additional context**
Zeplin designs https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa94e189735593e60e8

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Blocked by https://github.com/bbc/simorgh/pull/1409

**Comment by twinlensreflex** [comment]
I made a table of the columns vs group sizes because I think it's a little clearer

group | landscape | portrait | square
-- | -- | -- | --
1 (0-399px) | 1-6/6 | 1-6/6 | 1-6/6
2 (400-599px) | 1-6/6 | 1-6/6 | 1-6/6
3 (600-1007px) | 1-5/6 | 1-4/6 | 1-5/6
4 (1008-1279px) | 2-7/8 | 2-5/8 | 2-7/8
5 (1280px+) | 5-15/20 | 5-13/20 | 5-15/20

**Comment by nataliesmart** [comment]
Hello, I noticed some inconsistencies with the designs compared to the descriptions in the table above, and so wanted to clarify:

Group 1 + 2: all images span the full width (100%) of the device. So, 1-6/6, **plus margins**.
Group 3: landscape - 1-**6**/6, **plus margins**.
Group 4: square - 2-**6**/8.
Group 5: landscape - 5-**16**/20.
Group 5: portrait - 5-**12**/20.
Group 5: square - 5-**14**/20.

Let me know if you have any questions, or if I've misunderstood the table above.

Thanks.

**Comment by ChrisBAshton** [comment]
Have written this up and hopefully this makes sense. NB, it's difficult to translate the Zeplin designs into the Group breakpoints because they designs skip some of the breakpoints (picking 375 - so <399px - but missing a 400px breakpoint) and add arbitrary ones (768px) 😅 

Scenario outline:
- NO images can ever span beyond their natural width.
- Captions are semi-independent of the width of the image and have their own rules.
- I'm ignoring the 'outer columns' for the purposes of this.

Groups 1 + 2 (0-399px and 400-599px):
- all images span up to 100%
- all captions span up to 100%

Group 3 (600-1007px): 
- lanscape images span up to 100% of screen (but caption spans to 5/6 columns)
- square images span up to 5/6 columns (and captions also span to 5/6)
- portrait images span up to 4/6 columns (and captions also span to 4/6)

Group 4 (1008-1279px): 
- as per Group 3, EXCEPT:
- landscape images span up to 6/6 columns (NB: caption continues to span to 5/6 columns)

Group 5 (1280px+):
- as per Group 4, EXCEPT:
- grid system goes from 6 columns to 12 "main" columns and 20 (including outer columns). So Basically double all the rules above.

**Comment by ChrisBAshton** [comment]
Some pseudocode:

```scss
figcaption {
  width: 100%;

  @media (min-width: ${GEL_GROUP_3}) {
    grid-span: 4/6;

    figure.image--landscape &,
    figure.image--square & {
      grid-span: 5/6;
    }
  }
}
```

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1508.

**Comment by sareh** [comment]
Closed since this is part of this issue now: https://github.com/bbc/simorgh/issues/1751
