### ISSUE TITLE
Fresh `npm install` breaks in Jenkins

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1382]
**Describe the bug**
If I `rm package-lock.json` and then `npm i` to generate a new `package-lock.json`, Jenkins fails at the `make productionTests` stage:

```
Module not found: Error: Can't resolve 'regenerator-runtime/runtime' in '/var/lib/jenkins/workspace/simorgh_update-dependencies-HQKAL6YH4NLIKRU7PHMJLAJ7FR6T4K2UTPVXIWPSWD446KWRPHKA@2/app/src/app/containers/App'
     @ ./src/app/containers/App/App.jsx 16:0-38
     @ ./src/app/containers/App/index.jsx
     @ ./src/client.js
     @ multi ./src/client
```

Something to do with our .babelrc setup and an incompatibility with the `useBuiltIns` option of `@babel/preset-env`.

Tried fixing in #1379 but no luck. Was impacting #1357 but I was able to use the `package-lock.json` from `latest` and apply my new dependencies to it (`npm install`).

**To Reproduce**

1. Make a new branch
2. Create a new `package-lock.json` file (`rm package-lock.json && npm i`)
3. Push the branch to GitHub and open a PR
4. See Jenkins fail

**Expected behavior**
It should pass.

**Additional context**
This isn't an immediate issue but it _will_ come back to bite us if we don't fix it soon.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by pjlee11** [comment]
`App.jsx` causes the `regenerator-runtime/runtime` error which is a result of hoisted async functions. `babel-polyfill` will fix this and can be added to the `webpack.config.js` like so ...

```
entry: START_DEV_SERVER
      ? [	
          // stop hoisting before polyfill runs https://github.com/babel/babel-preset-env/issues/112#issuecomment-292675082	
          'babel-polyfill',	
          'webpack/hot/poll?100',	
          './src',	
        ]	
      : ['babel-polyfill', './src'],
```

This *should* fix the problem because the polyfill happens before `App.jsx` is invoked. It's worth nothing that when we move to SPArtacus the polyfill is direcly in the [utilities.js](https://github.com/bbc/SPArtacus/blob/6cd6a9f523ee6e9aa3d05899c0f64093238e1190/utilities.js#L1) which then calls the `loadInitialData` function and should also fix this error

**Comment by pjlee11** [comment]
Errrrrrr this seems to pass okay - https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/regeneration-runtime-error/1/pipeline/

**Comment by ChrisBAshton** [comment]
Okie dokie - closing.
