### ISSUE TITLE
Integrate Footer to Article component

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#139]
**Is your feature request related to a problem? Please describe.**
This should be only carried out after all the other footer tickets have been completed.

The Footer is not integrated into the Article component, and by extension not shown on the page.

**Describe the solution you'd like**
Integrate the [Footer component](https://github.com/bbc/simorgh/blob/latest/src/app/components/Footer/index.jsx) with the [Article component]( https://github.com/bbc/simorgh/blob/latest/src/app/components/Article.jsx#L38-L44).

**Additional context**
- Will need to have all accessibility requirements addressed, working closely with a UX designer.
- Will likely need to add e2e tests, working closely with a QA tester.

**Definition of done:**
- [ ] Footer to have <footer> element wrapping the Brand banner and footer links
Footer Links section:
- [ ] Copy and links: Brevier - #444444
- [ ] Copy and links BBCReithSans-Regular (to be discussed) 
- [ ] Background colour: #4C4C4C
- [ ] Links: weight - 700 
- [ ] Dividers: 1px height #ffffff
- [ ] Tap targets (Trust Project Link: 32px height, 100% width. Other l inks: 32px height, 50% width (mobile only), greater than mobile:  24px
- [ ] Tab Order: Including banner (banner to be no.1)
- [ ] Landmark region content info
- [ ] Announced Text of links - (To discuss with Catherine about BBC News SVG)

**Comment by sareh** [comment]
This issue is blocked pending getting detailed accessibility acceptance criteria and screen reader user experience requirements from the UX designers.

**Comment by greenc05** [comment]
**List tab order**
To achieve the desired UX for the tab order, I believe the only way we can reliably achieve this, while using semantic markup, is to use CSS Grid columns. 

For the tab order, this means if the browser does not support CSS Grid then we will have to fall back to row order (like the ORB nav footer list) rather than the desired column order.

See screen shot and simple mock up with CSS Grid (no fall back implemented)… http://2bitstudio.co.uk/code-tests/article/footer-list-order.html 

<img width="1433" alt="screen shot 2018-06-27 at 09 35 08" src="https://user-images.githubusercontent.com/1061401/41962630-6eea71ca-79ed-11e8-870c-83537305dd05.png">

**List semantics**
Note that VoiceOver strips out the list semantics when using list style none, we should reinstate the semantics by adding role list and role listitem to the mark up:
```
<ul role="list">
    <li role="listitem">Item 1</li>
    <li role="listitem">Item 2</li>
    <li role="listitem">Item 3</li>
</ul>
```

**SVG/High contrast mode on PC/No CSS**
If this Issue is picked up before the header, see notes in https://github.com/bbc/simorgh/issues/186

**Comment by jamesbhobbs** [comment]
Very interesting, thank you @greenc05

**Comment by jtart** [comment]
While the additional context `Will need to have all accessibility requirements addressed, working closely with a UX designer.` that has been added, and @greenc05's point's are very valid, I am unsure we need to address those points before we integrate with the Article component.

We should iterate on it when it has been integrated.

Thoughts?

@benjaminhobbs
@sareh
@greenc05
