### ISSUE TITLE
Code Climate test diff coverage not running

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#143]
**Describe the bug**
Code Climate test diff coverage is not running on PRs. It is still an expected check to run, so is just hanging.

**To Reproduce**
1. Go to a PR
2. Review PR checks and note `codeclimate/diff-coverage Expected — Waiting for status to be reported`

**Expected behavior**
Code Climate test diff coverage should run on each PR.

**Additional context**
PR are blocked from being merged as it is a required check.

**Comment by jamesbhobbs** [comment]
The docs are poor, from what I can see there is no way to get this working on PRs (it was working on the branches before). I've re-enabled push tests running in Travis for now which solves this issue (upon next push for each PR). Probably best solution is to later move to a better documented coverage tool e.g. coveralls. For now this seems adequate though.

**Comment by jamesbhobbs** [comment]
Isn't actually fixed, example: https://github.com/bbc/simorgh/pull/144

**Comment by jamesbhobbs** [comment]
This is working, but the requirements of codeclimate are very specific. The coverage report needs to have been sent to them for the latest commit on the PR (obvious), it also needs to have a coverage report for the base commit. For some reason some commits don't have it, but it's very easy to fix and probably won't repeat. Example at time of writing: https://github.com/bbc/simorgh/pull/130 did have missing codecoverage diff, now it doesn't because I rebased and force pushed.
