### ISSUE TITLE
No way of going 'back' from Error page

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1450]
**Describe the bug**
When our application goes into an Error state, you should be able to hit 'back' in the browser and get back to the page you were on. But currently, you're stuck in the error state indefinitely (until you refresh the page and get a server-side render).

**To Reproduce**
This will reproduce for the time being, but we anticipate the linking logic being fixed soon so it won't be reproduced forever!

1. Go to https://www.bbc.co.uk/news/articles/cxvxrj9yvppo
2. Click on the link in the article
3. See error page
4. Hit 'back' - we'll still see the error page

We'll soon fix this instance so that 3) doesn't happen, in which case we'll have to reproduce locally (e.g. change the fixuture data to point to a 404ing link).

**Expected behavior**
It should be possible to go 'back' from an error page and continue browsing as before.

**Screenshots**
![ezgif-1-a60f32023fd4](https://user-images.githubusercontent.com/5111927/54742939-a4a83c80-4bba-11e9-9e19-e44ce4846d96.gif)

**Additional context**
When we fix this, we should also add a Cypress test that explicitly tests clicking a 404, getting the client-side error render, then hitting 'back' and getting the original article again. "A bug is just a missing test".

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by dr3** [comment]
This error, while a problem, isnt what it appears.

Whats happening is 

Show article with data from `window.simorgh` server render -> 
Click onward link -> 
Get error fetching data (due to CPS error on live) ->
Navigate back ->
Get error fetching data (due to CPS error on live)

It does navigate back, but when it does it reloads the data and gets the same error that you got when you first navigated.

To fix this issue, we need to save the `window.simorgh` data in storage, and use it if the json fetch fails.

**Comment by ChrisBAshton** [comment]
Thanks for the explanation. So we _either_ do that, or we just keep an eye on this issue and when we've fixed the CPS error on live we shouldn't be able to reproduce and should just close it?

**Comment by dr3** [comment]
Yeah, tbh we should make an issue to save the initial article data in storage, as unlike subsequent articles, the JSON isnt requested, to be cached

**Comment by ChrisBAshton** [comment]
Confirmed fixed.
