### ISSUE TITLE
Investigate JS bundle script order in page

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1469]
**Is your feature request related to a problem? Please describe.**
We currently add our JS bundle files to the page in the order

Vendor, Vendor, Vendor, Main

Could we speed up the client side hydration by reordering these? Perhaps making main the first script to be parsed and run

**Describe the solution you'd like**
Investigate and open an implementation issue if it deeps worth while.

**Testing notes**
[Tester to complete]

Dev insight: N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Doesn't need refining, its simply an optimisation investigation, if an implementation issue arrises from this, that can be refined.

**Comment by hotinglok** [comment]
**Summary of investigation**
Changing the order of loading by swapping ```main``` and ```vendor``` does not affect client side hydration much. This is because regardless of the order, all ```vendor``` scripts need to finish evaluating before the page is displayed properly. 
As seen in [1] and [2] below, both orders finish around loading around just before 2000ms and both finish evaluating the scripts which then fully renders the page at around 2500ms.

**Method of testing** 
I first used chrome dev tools in order to monitor the performance of both orders on a simulated mobile phone with fast 3G connection by throttling the CPU with 4x slowdown. I then used webpagetest on the live bbc.com/igbo to see if there was any extra information to be found. This can be seen in [3].

**Other significant findings and thoughts**
- Our first paint time is very fast so this is good.
- There is a large gap of inactivity after the first load of js activity. This may be the browser waiting for the images to download but it may be worth investigating further.
- There are always two bundles which only start loading some time after the first four have begun.
- The best option would be to find a way to choose which dependencies go into each ```vendor``` bundle but as this is currently not possible, the only real solution to further increase performance would be to reduce the number of dependencies.

**Screenshots**
[1]
![image](https://user-images.githubusercontent.com/53564281/64257532-7080c800-cf1d-11e9-856a-99200944a988.png)
[2]
![image (1)](https://user-images.githubusercontent.com/53564281/64257581-80001100-cf1d-11e9-9350-b8c1d4a35934.png)
[3]
![image (2)](https://user-images.githubusercontent.com/53564281/64257965-44b21200-cf1e-11e9-8099-bddeac20ac1a.png)
