### ISSUE TITLE
Page re-rendering multiple times

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1487]
**Describe the bug**
Currently when a page is loaded, we have three full-page re-renders occurring after most elements have been rendered. This should not be happening. 

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/cn7769kpk9mo in Chrome
2. Open Chrome dev tools' network tab & throttle to a slow 3G connection
3. Open the 'Show Rendering' drawer and enable 'Paint flashing'
4. Refresh the page and see the green flash, showing the page re-rendering multiple times. 

**Expected behavior**
To not have the whole page re-rendering multiple times. 

**Screenshots**
GIF: 

![Mar-25-2019 12-16-22 - page re-rendering](https://user-images.githubusercontent.com/3028997/54919880-c88cba80-4ef9-11e9-9cb4-cc7fd5b7dd04.gif)

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Just checked and it may actually be FIVE times!!

**Comment by ChrisBAshton** [comment]
Looks like it happens every time a font is downloaded. See gif below:

![ezgif-2-18ca8c5520e2](https://user-images.githubusercontent.com/5111927/55622129-4755e300-5797-11e9-9fa1-27eb00caa753.gif)

Consequently, since we've added in the new fonts, the page now re-renders about FIVE times.

As we've done `font-display: optional`, and prioritised showing a first screen rather than showing the 'finished' screen, the fact that we re-render is probably unavoidable... 🤔

**Comment by pjlee11** [comment]
Can re-produce as @ChrisBAshton says the re-render happens about 5 times

**Comment by pjlee11** [comment]
Reading through https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas it's clear that the paint is a costly part of the render cycle. However, this only happens on the first page load (NB: ensure caching is not disabled with dev tools open) as the font's are then added to local storage meaning page reloads / subsequent article views only render once. 

This makes me think we could close this issue as it's unavoidable on the first page render.
