### ISSUE TITLE
Tidy file structure

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1535]
**Is your feature request related to a problem? Please describe.**
Many of our helper functions and utilities are scattered about out application and should be consolidated. This will aid new joiners to the team to have clarity wrt the application structure. This will also aid maintenance of the application. 

**Describe the solution you'd like**

These should be moved into the `lib` directory since they're used within the getInitialData logic to preprocess our feed. 

~~- `src/app/dataValidator/rules/timestamp*` -> `src/app/lib/preprocessor/timestamp*`~~(already done)
~~- `src/app/dataValidator/preprocessor/*` -> `src/app/lib/preprocessor/*`~~ (already done)

The data validator should be moved out of our app
- `src/app/dataValidator` -> `dataValidator`

Helpers that are used in production code should be moved to the `lib` directory
- `src/app/helpers/json/*` -> `src/app/lib/json/*`
- `src/app/helpers/blockHandlers.js` -> `src/app/lib/blockHandlers.js`
- `src/app/helpers/logger*` -> `src/app/lib/logger*`

Helpers that are not used in production code should be moved out of `app`
- `src/app/helpers/storybook/*` -> `.storybook/helpers/*`
- `src/app/helpers/tests/jest-setup.js` -> `src/testHelpers/jest-setup.js`

Functions from these two files: 
`src/app/helpers/tests/loggerMock.js`, 
`src/app/helpers/tests/setWindowValue.js`
should all be moved into -> `src/testHelpers/index.js`

**Describe alternatives you've considered**
Not moving these - but it will lead to more confusion.

**Testing notes**
[Tester to complete]

Dev insight: All unit and cypress tests should still pass. We should ensure all `package.json` scripts and regex of files for setup still work. Regression on the application needed. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Original copy of detail (slightly out of date now, so will edit the original above)...

"These should be moved into the lib directory since they're used within the getInitialData logic to preprocess our feed.

src/app/dataValidator/rules/timestamp* -> src/app/lib/preprocessor/timestamp*
src/app/dataValidator/preprocessor/* -> src/app/lib/preprocessor/*
The data validator should be moved out of our app

src/app/dataValidator -> dataValidator
Helpers that are used in production code should be moved to the lib directory

src/app/helpers/json/* -> src/app/lib/json/*
src/app/helpers/blockHandlers.js -> src/app/lib/blockHandlers.js
src/app/helpers/logger* -> src/app/lib/logger*
Helpers that are not used in production code should be moved out of app

src/app/helpers/storybook/* -> .storybook/helpers/*
src/app/helpers/tests/jest-setup.js -> src/testHelpers/jest-setup.js
Functions from these three files:
src/app/helpers/tests/loggerMock.js,
src/app/helpers/tests/setLocationOrigin.js &
src/app/helpers/tests/testHelpers.js
should all be moved into a single file -> src/testHelpers/index.js"
