### ISSUE TITLE
Add CSS identifier for primary images for monitoring

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1613]
**Is your feature request related to a problem? Please describe.**
We would like to be able to monitor when the 'primary' image renders for different groups of users using mPulse. This should be possible using mPulse's Time to Visually Ready timer:

From mPulse:
> Our Time to Visually Ready timer accepts a CSS selector of a hero image to wait for before triggering the timer.

To determine the primary image (from @jimjohnsonrollings) for the moment we should:
> take the first image block that is a child of the article block.

but note that the logic may become more complicated later as we add more functionality.

**Describe the solution you'd like**
- Determine the primary image based on the Optimo response
- Add suitable CSS selector that allows the above mPulse functionality to be used.
- Show if/how this can also be added to PAL front pages/article pages.

**Describe alternatives you've considered**
None.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
- Need to investigate how we select which Optimo image/video is the hero (is this marked specifically or is it just the first etc)

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
The Hero image metric is to measure when a page's most important content finishes rendering in the browser. https://speedcurve.com/blog/web-performance-monitoring-hero-times/
Due to the flexibility of Optimo, we may not have an image in the first or second position, so the 'hero metric' value for articles could be muddled and vary wildly on the type of articles posted. If we were to use the hero metric, an image could be lower down the page - perhaps several scrolls down on one article, potentially with lazy loading, and right at the top for another article.  

We need to consider what will happen if we don't have an image block for an article - will mPulse be able to handle these cases gracefully? I'd want to check that this metric for an image-less article doesn't lead to an artificially high value that will skew our metrics for articles that _do_ have images. 

I think this metric makes much more sense for the Front Pages, where we consistently have a lead image, than for Articles where we do not have any guarantee of an image being on the page.

**Comment by jamesdonoh** [comment]
Good point, thanks @sareh. Closing this as won't do.
