### ISSUE TITLE
Re-enable no-cycle linter warnings

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1622]
**Describe the bug**
In https://github.com/bbc/simorgh/pull/1597 we updated our dependencies but had to add to temporarily disable `import/no-cycle` in `.eslintrc.js`.

This is because with that warning enabled we now get 10 errors of the form:
```
/path/to/simorgh/src/app/containers/Article/index.jsx
  10:1  error  Dependency cycle via ../Text:6=>../Paragraph:2=>../InlineLink:5=>../../routes:10  import/no-cycle
```

We should re-enable the linter rule and fix the errors.

**To Reproduce**

1. Remove `import/no-cycle` from .eslintlrc
2. Run `npm run test:lint`

**Expected behavior**
No linter errors should be shown.

**Screenshots**
NA

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by rossgaskell** [comment]
**Investigation**

The errors started appearing due to the bump in eslint import plugin version. There was a bug with the babel-eslint parser not reporting the errors. The errors reported already existed before the dependency update in #1597, but were not reported.

https://github.com/benmosher/eslint-plugin-import/pull/1218
https://github.com/benmosher/eslint-plugin-import/issues/1166

The warnings are a false negative. Whilst there is a circular dependancy due to the internal link requiring the routes regex to match against, this only imports a constant and therefore isn't a true circular dependency.

However to improve readability, the regex paths have been moved to separate file that the routes and internal link component can share without eslint flagging a circular dependency.
