### ISSUE TITLE
Do not use a list if there is just one StoryPromo

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#1811]
**Is your feature request related to a problem? Please describe.**
At the moment, in the `FrontPageSection` container we are displaying the `StoryPromo` as a list item even if there is just one in the group items array.

**Describe the solution you'd like**
Do not wrap the `StoryPromo` in a list if the items array has just one item.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: snapshot and unit tests

**Additional context**

**Comment by greenc05** [comment]
We need this to meet the following accessibility acceptance criteria:

Given I use a screen reader
When I view a section with **more than** one promo (on an index page)
And I navigate to the first promo
Then it should be announced as a list item within a list

This is because, we use semantic HTML and lists are generally used to group **more than** 1 piece of related content, to signal a correlation between multiple elements. When there is only 1 promo, we have nothing to 'group' and no need to signal correlation.
