### ISSUE TITLE
Travis reports failures building latest

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1814]
**Describe the bug**
We have observed that Travis sometimes reports it is building `latest` in relation to a PR, e.g.:
![Screenshot 2019-05-28 at 16 18 07](https://user-images.githubusercontent.com/11161809/58489997-3fe20300-8164-11e9-873b-0867b727694d.png)

See Travis build: https://travis-ci.org/bbc/simorgh/builds/538193160

Seems to relate to a merge of `latest` into the feature branch.

![Screenshot 2019-05-28 at 16 19 37](https://user-images.githubusercontent.com/11161809/58490092-6bfd8400-8164-11e9-9cfe-ca1ed9d9548e.png)

**To Reproduce**
Steps to reproduce the behavior: _unknown_

**Additional context**
Possibly related: https://github.com/travis-ci/travis-ci/issues/8767#issuecomment-344749612

Also:

> Rather than build the commits that have been pushed to the branch the pull request is from, we build the merge between the source branch and the upstream branch.
https://docs.travis-ci.com/user/pull-requests/

**Comment by jamesbhobbs** [comment]
@jamesdonoh Based on the options set here: https://docs.travis-ci.com/user/notifications/#configuring-irc-notifications there is no resolution to this problem. I think there's no way to differentiate between it being on latest branch and running the test on the commit from latest in a given PR. Therefore there are two solutions:

1. Slightly change template from
`Build <%{build_url}\|#%{build_number}> (<%{compare_url}\|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}\|#%{pull_request_number}> by %{author} %{result} in %{duration}"` to something making it clear it might not actually be latest.
2. Instead change travis to run on push as well as PR and turn off slack notifications for PRs. This would slow travis down, but would mean we don't get a notification in slack of OSS PRs (probably good, avoids spam if it becomes an issue) and it means the push tests run a little earlier (before the PR is created) which is useful. So only downside is slower travis tests (due to limited resources in travis spread across more builds).

**Comment by jamesbhobbs** [comment]
Note for record, @jamesdonoh agreed with option 2 as 'Travis speed isn't our limiting factor at the moment'.
