### ISSUE TITLE
Investigate - scalability of e2e test for new services

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#1837]
**Is your feature request related to a problem? Please describe.**
Currently we have our cypress e2e test running against two services news and persian but this would be needed to be extended when we start adding in other language services.The way the tests are written now is like separate test files for every feature per service which would mean there would be identical test code per services executing the same tests but with a different data which seems redundant.

**Describe the solution you'd like**
1. We need to investigate are we able to separate the feature test files and the data that is feed into separate files which means having a javascript object holding all the service assets ids and then looping through each service and running all the tests for each service.

`var service = {
news: 'c8xxl4l3dzeo'
persian: 'c7eel0lmr4do'
.....
}`

`Object.keys(service).forEach((key) => {`

`execute generic feature tests`

`}`
2.Also Cypress can now run tests in parallel across multiple virtual machines, or can be parallelized on a single machine. Cypress will automatically figure out, detect, and load balance all of your specs in the fastest and most efficient way possible.Can look into this as well if this would be something that can be done as running tests for all services would consume more time.More info [https://docs.cypress.io/guides/references/changelog.html#3-1-0](url)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by david-boydell** [comment]
I'm currently using .map, but I don't care what we use.

For WS frontpages I would like to have a simple object containing services that include data common e.g. urls (as seen in the first line) Then, for each spec, we will have a separate js object that will contain data specific to that spec (e.g. for the frontpage spec it would include a list of the sections & articles we would expect to see).

We then `deep-extend` the two objects, creating a super-object for the spec. The question of where to store this data is up for discussion. Probs a directory under cypress and a sibling of integration, plugins, support etc.

`deep-extend` is currently a node_module but not in the dependencies. I get a linting error because of this but I'm tempted just to ignore it rather than add to dependencies. If you decide to give `deep-merge` a try we can add it later if it sticks.

**Comment by david-boydell** [comment]
I'll have a working example soon so can show you what I mean.

**Comment by david-boydell** [comment]
Igbo just has a hellish amount of test data to create :(

**Comment by jamesbhobbs** [comment]
Relates to https://github.com/bbc/simorgh/issues/2046

**Comment by jamesbhobbs** [comment]
This is actually entirely covered by that issue
