### ISSUE TITLE
Timezone dependant tests

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1855]
**Describe the bug**
The unit tests on latest for `src/app/containers/ArticleTimestamp/index.test.jsx` fail based on the current timezone/time near to midnight (haven't been able to pinpoint the exact problem yet).

**To Reproduce**

1. Go to `Date & Time` on you local device
2. Set your timezone ahead 3+ hours (might need to try different locations to get this right)
3. `npm run test` or specifically `npm run test:unit src/app/containers/ArticleTimestamp/index.test.jsx`

**Expected behavior**
Our tests shouldn't fail based on timezone. 

**Screenshots**
Failure with timezone non-english
![image](https://user-images.githubusercontent.com/7791726/58943883-cdf96180-87d4-11e9-89fe-1f420b747c0a.png)

Pass with timezone english
![image](https://user-images.githubusercontent.com/7791726/58944374-d2724a00-87d5-11e9-9ded-e6d7b4ddf887.png)

**Additional context**
Some initial debugging showed that `console.log(firstChild(renderedWrapper));` in `src/app/containers/ArticleTimestamp/index.test.jsx` the passing tests return with `31 May 2017, 03:00 BST` whereas the failing tests return with `31 May 2017`. This makes me believe it's to do with the BST logic in the code or tests. 

It also could be due to the test using regex (EG `regexDatetime` and `regexUpdatedDatetime`) which are expecting a `,` and `BST`

**Comment by 12** [comment]
I think we need to be careful in assuming the fault lies with different timezones. This has also failed on our CI (which is UTC) when the job was ran a couple of hours after midnight. Locally for me, the tests also failed when switching to UTC when `3 hours ago` and `5 hours ago` would cross the previous day.

**Comment by billy-reilly** [comment]
@pjlee11 I think the issue in your example is that they are using hardcoded timestamps, and the [isSameDay](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleTimestamp/helpers.js#L15-L18) comparison is done according to the machine's timezone.

For example, in this test:
https://github.com/bbc/simorgh/blob/0f4c7f5f6f7e32c64bf75621124b8ff71f846b23/src/app/containers/ArticleTimestamp/index.test.jsx#L97-L111
if you parse the two different timestamps that can be returned by the mock `Date.now` you see that they represent a time that is 1pm in UTC:
```
const timestamp = inBritishSummerTime ? 1496235600000 : 1483275600000;
console.log(moment.utc(1496235600000).format()); // 2017-05-31T13:00:00Z
console.log(moment.utc(1483275600000).format()); // 2017-01-01T13:00:00Z
```

If your timezone is set to +12 hrs then the timestamp represents 1am local time, so when compared to a timestamp that is 11 hours earlier `isSameDay` returns false. This means [formatType](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleTimestamp/helpers.js#L22) returns `formatDate` rather than `formatDateAndTime`.

I think the best way to make the tests work across timezones is to calculate timestamps that will meet the test's conditions taking the timezone offset into consideration, instead of hardcoding them.

I've had a go at implementing this in #1884

**Comment by billy-reilly** [comment]
hey @pjlee11 @rhell 👋 sorry I'm new here - ~the travis CI build stage has failed a few times for me now, do you recognise either of these errors?~
```
$ ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
[...]
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
[...]
The command "./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT" exited with 255.
```
~or~
```
The command "./cc-test-reporter before-build" failed and exited with 2 during .
```

~could the first one be because my PR is coming from a fork of simorgh?~

Apologies ignore me, just read the docs properly 🤦‍♂
