### ISSUE TITLE
The header we currently have on the article needs to be made production ready

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#186]
**Is your feature request related to a problem? Please describe.**
We have detailed design specifications to meet and should follow them.

**Describe the solution you'd like**
A BBC dev works with UX to improve this component

Similar work to: https://github.com/bbc/simorgh/issues/139 but simpler

**Comment by sareh** [comment]
A prerequisite will be to consider typography - details in this issue: https://github.com/bbc/simorgh/issues/184

**Comment by greenc05** [comment]
**Inline SVG brand logo - Recommended approach**
- Add an attribute of focusable="false" to the svg - Without this, when using Jaws with IE and navigating via the ‘tab’ key, the SVG content is read out twice to screen reader users. This is due to a bug with IE in which it makes all SVGs within links/buttons focusable, resulting in you being able to tab to the link and also to the SVG inside the link, this is also an issue for sighted users using the keyboard to navigate with the tab key who will have to tab twice when encountering a link with an svg inside.
- Add an attribute of aria-hidden="true" to the SVG (title is not reliably supported)
- Use a ‘visually hidden’ (also known as off-screen text) span for the textual equivalent of the SVG
- Even if you are following these recommendations, always thoroughly test your exact implementation

```
<a href="https://www.bbc.co.uk/news">
    <svg focusable="false" aria-hidden="true” …>...</svg>
    <span class="gs-u-vh">BBC News</span>
</a>
```

**High contrast mode on PC**
It's important that the brand logo SVG works with default and custom colour themes, ensure you test this in development.

**No CSS**
If the user doesn’t have CSS (it either hasn't loaded or they have chosen to disable it), it would be awesome if the user can still see the brand logo SVG i.e. a white SVG cannot be seen on a white background. 

The following example code demonstrates how you can display an SVG in black for users without CSS, by specifying an inline fill colour (black) for the SVG which is available if the user doesn’t have CSS (which works on a white background), the colour of the SVG is then changed to white with CSS which can then be seen on the CSS coloured background. An example of how to implement this can be seen here http://2bitstudio.co.uk/code-tests/article/svg-brand.html

**Comment by sareh** [comment]
Designs at two breakpoints - mobile & desktop.

![375_header](https://user-images.githubusercontent.com/3028997/42102199-24022f14-7bbd-11e8-9ab2-d03012988927.png)

![1280_header](https://user-images.githubusercontent.com/3028997/42102198-23dbba1e-7bbd-11e8-8e6a-3d7f6c32fffb.png)

**Comment by jtart** [comment]
Closing for more granular issues.
