### ISSUE TITLE
Reith font not loading on articles

### ISSUE THREAD

**Issue by nataliesmart** [bbc/simorgh#1993]
**Describe the bug**
On multiple occasions, when I've loaded an article, the Reith font does not load in, even though it's downloaded/cached locally. I see a fallback font, Helvetica/Arial.

**To Reproduce**
https://www.bbc.co.uk/news/articles/c744mjrym37o (happens on other articles too)
Command 'R' to refresh the article page. Or, upon loading an article via a url link.

**Expected behavior**
I should always see the Reith font within the article after my first visit, (arguably during my first visit too, if I'm in the UK and have a good connection) and/or once the Reith fonts are downloaded/cached locally.

**Screenshots**
![Screen Shot 2019-06-19 at 12 33 40](https://user-images.githubusercontent.com/30656637/59763306-38a8a380-9291-11e9-8e89-2984f4cdfc7a.png)
![Screen Shot 2019-06-19 at 12 34 01](https://user-images.githubusercontent.com/30656637/59763307-38a8a380-9291-11e9-8b92-4625b553dc00.png)
![IMG_6112](https://user-images.githubusercontent.com/30656637/59764081-e7011880-9292-11e9-8473-af369f38e158.PNG)

**Desktop:**
- OS: 10.12.6 (16G1918)
- Browser: Chrome 
- Version: 74.0.3729.169 (Official Build) (64-bit)

**Smartphone:**
- Device: iPhone 6s Plus
- OS: 12.3.1
- Browser: Safari
- Version: Couldn't find this, sorry.

**Additional context**
N/A

**Comment by ryanmccombe** [comment]
This is actually intentional for performance reasons - users who first load into the page will be given a brief amount of time for the Reith font to download - after that period expires, we just use a fallback font

There are two alternatives, but they also have their issues:

Alternative Implementation 1 would be to not show any text until Reith is downloaded.  This extends the period of time that users see nothing

Alternative Implementation 2 would be to show the fallback font as we do now, but switch it out for Reith once Reith is downloaded.  This would involve the font changing after the content loads, which is visually jarring

Our current implementation is arguably the least-bad, but it is worth spending some time investigating if it can be improved - if the fallback is so aggressive it is regularly happening on our connections, it doesn't bode well for world service provinces with slower speeds.

One redeeming factor is the Reith font will be cached after the first visit though, so it shouldn't happen for recurring visitors

**Comment by ryanmccombe** [comment]
Related issue: https://github.com/bbc/simorgh/issues/1009#issuecomment-502131575

**Comment by nataliesmart** [comment]
Hello @ryanmccombe, thanks for the info. 

The problem/bug here is that although the font is cached after the first visit, I still see Helvetica/Arial for recurring visits, Reith doesn't display at all (as per screenshots).

You might be right, and I initially suspected, that the fallback threshold might be too aggressive? Especially given we have good connections.

**Comment by ryanmccombe** [comment]
Ah interesting - definitely seems to be problems here still

I can't reproduce this by refreshing the page - ie, font coming from memory cache - but I can by opening a new tab and visiting the site again, ie, font coming from disk cache as per the screenshots

The No-Reith bug happens about 10% of the time for me on a new tab.  What's strange is, most of the other times, before you see the content in Reith, you still get see helvetica for a fraction of a second - ie, the exact problem this is supposed to be mitigating

**Comment by jamesbhobbs** [comment]
We've now made some fairly substantial performance improvements, @nataliesmart can you confirm if this is still persistent?

PS improving performance is the only fix "You might be right, and I initially suspected, that the fallback threshold might be too aggressive? Especially given we have good connections." Changing this fallback threshold is not possible.

**Comment by nataliesmart** [comment]
Thanks @benjaminhobbs. Still appears to be persistent for me.
![Screen Shot 2019-07-17 at 10 18 44](https://user-images.githubusercontent.com/30656637/61364586-113bfb00-a87e-11e9-937a-66e8a407ee67.png)

**Comment by jamesbhobbs** [comment]
@nataliesmart and I went through it together and could only reliably reproduce on a throttled network connection with a hard refresh, which is when this should occur. Issue will be reopened if and when this can be reproduced reliably without network speed problems.
