### ISSUE TITLE
Update bundle size tests to dynamically generate list of services

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2133]
**Is your feature request related to a problem? Please describe.**
Introduced in https://github.com/bbc/simorgh/pull/1872, the `scripts/bundleSize.sh` currently has a hardcoded array of services, we should make it dynamic

![image](https://user-images.githubusercontent.com/11341355/60179247-2ee4ea00-9815-11e9-8485-9616f1a105ac.png)

**Describe the solution you'd like**
Build the array dynamically based on files in the dir. 

Add an extra test to ensure the array includes a minimum number, to avoid it skipping all services if the bundle splitting breaks :)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by pjlee11** [comment]
```
listOfPublicServices=$(ls -d build/public/*/)
stringOfServices=$(echo "$listOfPublicServices" | sed -e "s/build\/public\///" -e "s/\///" )

echo $stringOfServices
```

Had a little play and this gives a return of `igbo news persian pidgin static yoruba` which is a string and would need `static` removed from. Then could be turned into an array. 

My only concern is that this uses the names of the directories from the `build/public/` and not the name of the bundles generated. Personally I think it might be more sensible to read from a list of services that simorgh supports rather than dynamically checking agains the name of the generated bundles. This way the "list of services" could work as a whitelist for the names of bundles we actually create

**Comment by dr3** [comment]
This has been done :)
