### ISSUE TITLE
Put all services in the app

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2230]
**Is your feature request related to a problem? Please describe.**
We currently only have services in this application that are on the immediate product roadmap. We should add all services and ensure they're available locally (and where possible on test) and ensure all our application setup and testing can scale to this number of services.

**Describe the solution you'd like**
Do all things required to add all services:
**World Services:**
www.bbc.com/afrique
www.bbc.com/afaanoromoo
www.bbc.com/amharic
www.bbc.com/arabic
www.bbc.com/azeri
www.bbc.com/bengali
www.bbc.com/burmese
www.bbc.com/gahuza
www.bbc.com/gujarati
www.bbc.com/hausa
www.bbc.com/hindi
www.bbc.com/igbo
www.bbc.com/indonesia
www.bbc.com/korean
www.bbc.com/kyrgyz
www.bbc.com/marathi
www.bbc.com/mundo
www.bbc.com/nepali
www.bbc.com/pashto
www.bbc.com/persian
www.bbc.com/pidgin
www.bbc.com/portuguese
www.bbc.com/punjabi
www.bbc.com/russian
www.bbc.com/serbian
www.bbc.com/sinhala
www.bbc.com/somali
www.bbc.com/swahili
www.bbc.com/tamil
www.bbc.com/telugu
www.bbc.com/thai
www.bbc.com/tigrinya
www.bbc.com/turkce
www.bbc.com/ukchina
www.bbc.com/ukrainian
www.bbc.com/urdu
www.bbc.com/uzbek
www.bbc.com/vietnamese
www.bbc.com/yoruba
www.bbc.com/zhongwen

**UK News:**
https://www.bbc.co.uk/cymrufyw
https://www.bbc.co.uk/naidheachdan
https://www.bbc.co.uk/news

**Describe alternatives you've considered**
Do it later, but let's push ourselves.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by benjaminhobbs** [comment]
Scalability of cypress e2es: https://github.com/bbc/simorgh/issues/2046

**Comment by sareh** [comment]
For error pages,  cookie banners and offscreen text, if we do not yet have the translations, initially use the text for `news`. Once we have the translations we should add them in a future issue. 

For other fields such as metadata, visit the relevant site linked above and use existing values. At the review stage of this ticket, these values can be reviewed by the relevant Product owner / Business Analyst.

We have several services that have multiple scripts, such as Zhongwen (traditional and simplified) and Serbian (Latin and Cyrillic). To accommodate these there are two options - we add a separate service config files `zhongwen-trad`. This will be useful if some page metadata will differ depending on the script variant, eg. lang and social media meta links. We would need to add logic to map from URL params to the correct Service Script variant. 

An alternative approach is to completely separate out translations from the Service configuration. This would mean we would have a new page-level context that would pull in translations and script-specific configuration. The creation of this separate context may be helpful regardless, since we will shortly be pulling in translation data from an API.

**Comment by thekp** [comment]
Hi @sareh ,

update from core-pod

All service front-pages are available on test. e.g: https://www.test.bbc.com/urdu/articles/c4vlle3q337o

and we have error pages on test for articles per service: 
https://www.test.bbc.com/mundo/articles/c4vlle3q337o

**Comment by dr3** [comment]
WIP for service varients

**Comment by dr3** [comment]
We now have all services (inc variants) in simorgh :)
