### ISSUE TITLE
Fix consistency of file naming convention

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#235]
**Is your feature request related to a problem? Please describe.**
Files are not consistently named, for example, see:
- https://github.com/bbc/simorgh/blob/latest/cypress/support/test-helper.js
- https://github.com/bbc/simorgh/blob/latest/src/app/helpers/proptypes.js

**Describe the solution you'd like**
All file names to use camelCasing.

**Comment by jamesbhobbs** [comment]
We should add some linting to this too, it won't be perfect but it can definitely stop `-`s

**Comment by radiocontrolled** [comment]
Do icon names e.g. `public/images/icons/icon-128x128.png` need to be camel cased?

**Comment by radiocontrolled** [comment]
Input needed on this please.

(1) Should  `index.test.jsx` change to `indexTest.jsx`

(2) Or as @pjlee11 suggests, 

Should we do `/Headline/headline.jsx` and `/Headline/headlineTest.jsx` and `Headline/headlineStories.jsx`, rather than have a huge amount of `index*` files such as:
`/Headline/index.jsx` and `/Headline/indexTest.jsx` and `Headline/indexStories.jsx`

**Comment by jtart** [comment]
I really disagree with `indexTest.jsx` and `indexStories.jsx`, it is ambiguous and against all convention. 

I am also keen on `/[Component]/index.jsx` as I think it is the cleanest implementation and most popular naming convention. This latter point feels distinct from the conversation on the former and I would be keen to separate them.

**Comment by jtart** [comment]
@radiocontrolled `Do icon names e.g. public/images/icons/icon-128x128.png need to be camel cased?` - no, static assets like this don't need to follow this naming convention.

**Comment by pjlee11** [comment]
@jtart based on your reply this issue is vaguely defined. The combination of the problem being _"Files are not consistently named" and the solution being _"All file names to use camelCasing."_  could easily suggest that everything in the codebase should follow camelCase format, including directory names etc, as this would be "consistent". 
However this is not the case given that we use the Capitalisation for the components directory EG: `Headline/` and we are using dot notation for stories and tests EG: `index.test.jsx` and `index.stories.jsx`.

Therefore to be clear we are actually supporting 4 conventions in the following ways:
- Component directories should be capitalised as per the React convention EG: `/Headline/`
- Test files should be dot notation as per the Jest convention EG: `index.test.jsx`
- Component stories should be dot notation as per the Storybook convention EG: `index.stories.jsx`
- Leaf files should be camelCase EG: `storyBody.jsx`

I personally would say that it is not obvious we are supporting 4 conventions and that defining this as consistent naming would be confusion to anyone who doesn't know about sed conventions.

My thoughts are that I'm happy to support them all we just need to be explicit in which naming conventions exist in this repo, which could most likely be achieved by adding some information to the README.

NB: The solution only mentioned files however I'm assuming that directories would want to be camelCase as well such as:
`utils/testHelpers/helperA.jsx`

Would you agree?

**Comment by jtart** [comment]
@pjlee11 I agree to everything you said, including the NB 👍 

We should also add documentation about our naming convention to make it clear.

**Comment by jamesbhobbs** [comment]
I think documenting this creates a document no one will read (I haven't if you're wondering) I am 99% sure people will name based on what they see, hence the urgent and small PR to standardise the JS file naming ^^^

**Comment by pjlee11** [comment]
I think it's good to have it as part of the CONTRIBUTING.md  for clarity especially as this is a public repo. Also if someone is struggling with keeping the naming consistent we have a single place to point them to understand the 4 conventions we are using across the repo.
