### ISSUE TITLE
Lock down use of dangerouslySetInnerHtml

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2622]
**Is your feature request related to a problem? Please describe.**
By allowing arbitrary data to be added to the DOM `dangeroulySetInnerHtml` is an acknowledged XSS vector (see https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)

At the time of writing we have [10 instances where this attribute is used](https://github.com/bbc/simorgh/search?q=dangerouslysetinnerhtml&type=Code) and the number is increasing. The more examples there are the codebase the more it appears an accepted pattern and the greater chance there is that we will add more in future, one of which will eventually create an XSS risk.

**Describe the solution you'd like**
- Audit existing usage of `dSIH` and assess potential XSS risk of each
- Identify which (if any) uses are strictly necessary and which could be replaced/removed or as last resort mitigated by using sanitisation libraries
- Investigate using stricter linting to contain spread
- Look at what changes might be needed to coding standards
- Make recommendations based on above and open PR/separate issues to address

**Describe alternatives you've considered**
None come to mind, and the problem will get worst the longer we leave it.

**Testing notes**
This is an investigation issue the actual issue which will be raised later will require testing.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by 12** [comment]
Was looking for something else but came across this that (as a last resort) should help us achieve this.

https://www.npmjs.com/package/react-safe

https://bundlephobia.com/result?p=react-safe@1.3.0

**Comment by jamesbhobbs** [comment]
I think we should use the approach described here: https://medium.com/@Jam3/how-to-prevent-xss-attacks-when-using-dangerouslysetinnerhtml-in-react-f669f778cebb

TLDR sanitise using https://www.npmjs.com/package/dompurify add custom eslint rule to force all uses of dangerouslySetInnerHtml to be sanitised

**Comment by jroebu14** [comment]
Currently in Simorgh, I think there's only one case where we really need to use `dangerouslySetInnerHtml` and it could be worth the effort investigating how we can remove the need for it https://github.com/bbc/simorgh/pull/4051#pullrequestreview-297982884

**Comment by samora** [comment]
We use `dangerouslySetInnerHTML` primarily for SSR and injecting AMP data. In all these cases we are trying to avoid React's explicit [escaping](https://shripadk.github.io/react/docs/jsx-gotchas.html). This seems to be the easiest option without having to add any dependencies. I see a low surface area for XSS vulnerabilities, since in all these cases the data is within our control and doesn't contain user input.

There seems to be only one instance of `dangerouslySetInnerHTML` which can be easily removed. I have a [PR](https://github.com/bbc/simorgh/pull/4169) up for this.

All usage of `dangerouslySetInnerHTML` should have one line eslint opt-out too. [This](https://github.com/bbc/simorgh/pull/4176) also addresses that.
