### ISSUE TITLE
Change Caption style for Persian

### ISSUE THREAD

**Issue by twinlensreflex** [bbc/simorgh#2623]
**Is your feature request related to a problem? Please describe.**
Captions are currently italicised by default. We do not want Farsi captions to be italicised.

**Describe the solution you'd like**
Pull in the updated version of `psammead-caption` to at least [2.0.0](https://github.com/bbc/psammead/pull/939)

This is similar to [pulling in updated psammead-headings in 2549](https://github.com/bbc/simorgh/pull/2549)

**Describe alternatives you've considered**
n/a

**Testing notes**
- Updating snapshots
- Visual regression (would be nice to see how inline links works with caption)

**Additional context**

**Comment by RayNjeri** [comment]
This issue is pretty much done. We are currently using psammead-caption version 2.0.3 which pulls in the work that fixes that ticket. All captions are currently not italicised. cc @eleanombre 
![Screen Shot 2019-07-23 at 10 55 23 AM](https://user-images.githubusercontent.com/27012452/61693722-bcdec280-ad38-11e9-99c5-5829872c49bf.png)

**Comment by RayNjeri** [comment]
Based on the tests carried out by @jamesbrumpton and myself this issue is pretty much solved for.
