### ISSUE TITLE
Test Chartbeat

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2808]
**Is your feature request related to a problem? Please describe.**
We fixed various existing issues with Chartbeat in https://github.com/bbc/simorgh/issues/1987, https://github.com/bbc/simorgh/issues/4573 and https://github.com/bbc/simorgh/issues/2811 however Chartbeat still needs fully testing on test before it can be enabled on live.

**Describe the solution you'd like**
- [Re-]test Chartbeat on test
- Create issues for any problems or errors found

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]
JIRA Ticket with Chartbeat expected output - https://jira.dev.bbc.co.uk/browse/NEWSART-605

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Values checked on  News Test:
Key | Expected value | Actual value (canonical)
------------ | ------------- | ------------- 
g | 50924 | 50924
h | test.bbc.co.uk | test.bbc.co.uk
g0 | News, News - ART | News, News - ART
_s.bbc_hid | value of cookie OR not set | value of cookie OR set to "null"
i | SEO Headline | Page <title>
Content Type | New Article | not set*
v | Referrer OR not set | not set

* we are setting the wrong variable I think - `_sf_async_config.contentType` instead of `_sf_async_config.type` 

Additionally, values do not appear to update correctly when moving between pages within the SPA (on canonical and AMP), including the i, v and p.

The p value, which I believe is set by the Chartbeat code, is lacking the domain, which it contains on the current live implentation on PAL pages - however we might be in the right here - it doesn't seem to break anything.

Values checked on  News Test:
Key | Expected value | Actual value (AMP)
------------ | ------------- | ------------- 
g | 50924 | 50924
h | test.bbc.co.uk | test.bbc.co.uk
g0 | News, News - ART | News, News - ART
i | SEO Headline | Page <title>
Content Type | New Article | New Article
v | Referrer OR not set | not set

So issues:
* content type not set correctly on canonical
* bbc_hid set incorrectly when the cookie is not set
* title is not set by us at all
* fields are not set correctly when moving from article to article on canonical

**Comment by jamesdonoh** [comment]
Further testing is blocked on https://github.com/bbc/simorgh/issues/2811 which covers the initial problems found when first testing this.

**Comment by jimjohnsonrollings** [comment]
Had a quick look... some things:

1) On canonical, the `g1` value is set to `No Author`, whereas on AMP this value is left empty.  I'm not particularly fussed which we go with but we should be constistent.

2) On canonical only, when using the inline link to move between articles (so moving from one page to another within the SPA), the `p` value does not update to reflect the URL of the second article

3) When looking at a page in Firefox Private Browsing, I get `The resource at “https://static.chartbeat.com/js/chartbeat.js” was blocked because content blocking is enabled.` in the console and nothing is sent to Chartbeat. (Chrome Incognito isn't working for me so can't check there)

**Comment by 12** [comment]
The third problem exists on the current News homepage FYI

**Comment by jimjohnsonrollings** [comment]
Blocked awaiting https://github.com/bbc/simorgh/issues/3040

**Comment by amywalkerdev** [comment]
Now unblocked and can be tested again

**Comment by jimjohnsonrollings** [comment]
Raised https://github.com/bbc/simorgh/issues/3303 as the referrer value appears to change between Chartbeat pings

**Comment by rhenshaw56** [comment]
Unblocked. Moving this to ready for test as the referrer issue with back clicks have been fixed by charrbeat

**Comment by jimjohnsonrollings** [comment]
Can we do this before https://github.com/bbc/simorgh/issues/4573 ?

**Comment by rhenshaw56** [comment]
> Can we do this before #4573 ?
@jimjohnsonrollings Ideally we should do this after #4573 but I'll suggest that since we would be moving most of these related issues to another pod I reckon we could test this before moving them on

**Comment by jamesdonoh** [comment]
We should defer this till https://github.com/bbc/simorgh/issues/4573 is done to avoid repeating effort.

**Comment by jimjohnsonrollings** [comment]
Other than the `v` it looks good to me

**Comment by jroebu14** [comment]
@jimjohnsonrollings can we close this issue?

**Comment by jimjohnsonrollings** [comment]
@jroebu14 Yep, I think so

**Comment by rhenshaw56** [comment]
closing this as it's no longer an issue
