### ISSUE TITLE
Make propType isRequired console.error's real throw errors

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#289]
**Is your feature request related to a problem? Please describe.**
Currently the prop-types dependency only `console.error`'s any failures around required props. This means the error's are only logged and therefore we have false positive tests and application code. 

**Describe the solution you'd like**
We should investigate possible solutions for this problem, some of the examples on comments may be valid.

**Describe alternatives you've considered**
1) We could identify a way to find the exact console.error message that relates to prop-types error EG: Regex. 
2) We could change the prop-types package to throw an actual error.

**Additional context**
N/A

**Comment by jtart** [comment]
What is the intended value in making isRequired errors throw errors?

**Comment by pjlee11** [comment]
Currently we have defensive code like https://github.com/bbc/simorgh/pull/288/files#diff-e2b8219c37e700ed70ed4898e04ccffeR6 which is checking that a required prop, in this case text, is passed to the component. This is effectively a graceful fail base on what props are passed to the presentational components, however this logic could be handled by error as per this issue and catching the error gracefully. 
By handling required prop checks using propTypes `.isRequired` we can have a consistent approach across all presentational components and it scales out easily for when a component has 5 required properties.

**Comment by pjlee11** [comment]
Also tests like https://github.com/bbc/simorgh/pull/288/files#diff-a9b5ed025b9a79eb40a7cff27516a701R7 will no longer create `console.warn` logs during the jest test output - currently this test will produce the following: 

![image](https://user-images.githubusercontent.com/7791726/42684062-ef6956c2-8686-11e8-8b4c-2420f13a1eb5.png)

**Comment by ChrisBAshton** [comment]
+1 - would cut down on noise when we fix the errors too

**Comment by pjlee11** [comment]
Question: how do we think we should silence these warnings? We could mock the `console.error` function in Jest similarly to how we do for `console.log` in the [dataValidator](https://github.com/BBC-News/simorgh/blob/greenkeeper/monorepo.storybook-4.0.4/src/app/dataValidator/helpers/dataLoader/readScenario.test.js#L1)

**Comment by ChrisBAshton** [comment]
~~Can't we fix the underlying issue?~~

EDIT: there is no underlying issue 😅have finally looked at the code and to be fair, the failures are expected:

```js
  describe('with no data', () => {
    isNull('should return null', <Text />);
  });
```

...gives:

```
 PASS  src/app/containers/Text/index.test.jsx
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: The prop `blocks` is marked as required in `TextContainer`, but its value is `undefined`.
          in TextContainer (at Text/index.test.jsx:10)
```

We have a couple of options as far as I can see:

## Option 1: override propTypes
The above example is fixable with one line in the `index.test.jsx`:

```js
Text.propTypes = {}; // override propTypes to avoid throwing errors
```

We could apply this line to every `index.test.jsx` file to cut out the verbosity.

## Option 2: change our tests
In the above example: "with no data, should return null" - is that what we actually want?
Or do we want the application itself to error, because it's been passed invalid data?

If we're using propTypes to ensure props are what we expect, then we should delegate as much as we can to that, and trust that the library works (we want to test our code, not necessarily that the library does what it says it will).

As you can guess - I'm in favour of Option 2 (though could live with Option 1 in the short term!).

**Comment by rossgaskell** [comment]
**Handover**
I don't think this is as simple as we originally throught during refinement. As discussed before and as mentioned above, just failing unit tests on every propType error would generate false negatives from tests written to check exactly how components perform when their required prop types are not provided.

One package to look into would be https://www.npmjs.com/package/check-prop-types which would allow us to write unit tests specifically for the purpose of checking prop types.
