### ISSUE TITLE
AV: investigate player loading message

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#3178]
**Is your feature request related to a problem? Please describe.**
Currently, while the SMP player is loading (immediately after placeholder click) there is no announced 'loading' message. There is just a white screen.

**Describe the solution you'd like**
Investigate whether a ‘loading’ message can be included whilst the SMP iframe loads in and before the SMP player starts buffering. 
UX suggest keeping the placeholder until the SMP player loads in, with the addition of a status message (e.g. 'loading' or 'offline').
Note that SMP will also announce its own loading message once the video loads, so we would need to think about the UX and make sure the announced messages are distinguishable. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Current video fail designs: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/dashboard?tag=Video%20fail for further discussion with UX if a loading error message is needed for this scenario.

**Comment by rhenshaw56** [comment]
By adding a [load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) listener on the iframe, we can watch out for when the av content is loaded and ready to play thereby adding a custom loading message or use the placeholder. I have a small working example of this [here](https://github.com/bbc/psammead/pull/new/investigate-av-loader). However there's still a time lag between when the iframe content renders it's own placeholder image and transitions to show the SMP loader and at this point we have a white screen shown in between. I think this might be due to how the iframe is rendered in or some SMP setting playing a factor but I haven't been able to reproduce that on SMP cookbook.

**Comment by simonsinclair** [comment]
> By adding a [load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) listener on the iframe, we can watch out for when the av content is loaded and ready to play thereby adding a custom loading message or use the placeholder.

- 👍

> I have a small working example of this [here](https://github.com/bbc/psammead/pull/new/investigate-av-loader).

- I like the idea of using an effect to register multiple `load` handlers - timeout could be refactored to use this. We should probably separate the logic from the component itself and default to using the `once: true` option.

> However there's still a time lag between when the iframe content renders it's own placeholder image and transitions to show the SMP loader and at this point we have a white screen shown in between. I think this might be due to how the iframe is rendered in or some SMP setting playing a factor but I haven't been able to reproduce that on SMP cookbook.

- This is probably due to the fact we're dealing with two iframes. A more robust solution might be to use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to notify Simorgh when the inner iframe has loaded, eliminating the dead-spot between the first and the second iframe's.

**Comment by HarveyPeachey** [comment]
> > 
> > However there's still a time lag between when the iframe content renders it's own placeholder image and transitions to show the SMP loader and at this point we have a white screen shown in between. I think this might be due to how the iframe is rendered in or some SMP setting playing a factor but I haven't been able to reproduce that on SMP cookbook.
> 
> * This is probably due to the fact we're dealing with two iframes. A more robust solution might be to use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to notify Simorgh when the inner iframe has loaded, eliminating the dead-spot between the first and the second iframe's.

Following on from this, I agree with Simon's proposal of using postMessage to notify Simorgh as this will also allow the use of `postMessage` in the future which can be very useful. 

Another quick solution will be going into the template files of the morph module and adding a loading message/image and then add some JS so when the iframe has appeared using the `intitialised` event which SMP emits when the iframe has loaded, it then removes the loading message/image. But a `postMessage` solution would be better because we can then handle the loading logic all in Simorgh/Psammead.

**Comment by rhenshaw56** [comment]
thanks, @simonsinclair @HarveyPeachey for checking this out. I will do a little more investigation into making this work with `postMessage`.

**Comment by rhenshaw56** [comment]
Had a chat with @simonsinclair and the agreed upon approach was to fire a message event in the news-av-player module and listen for that event in psammead/simorgh for when the video is loaded. Tested this approach utilizing @HarveyPeachey's [POC](https://github.com/HarveyPeachey/postmessage-av-concept) by triggering a message event within the embedded content and subscribing to that event in the Mediaplayer component and it works.

**Comment by rhenshaw56** [comment]
This is not a priority now. Will be revisited.
