### ISSUE TITLE
Fix accessibility issues and remove the a11y test skips

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#336]
**Describe the bug**
https://github.com/bbc/simorgh/blob/08390ab85ec12196fe6bb7cb37cb2b245d2c6d9e/a11y.js#L2-4
we skip some a11y tests. We did this to enable the a11y testing, but we need to fix these accessibility issues and remove these skipped tests.

**Comment by radiocontrolled** [comment]
I'm marking this as blocked for now as I need some more information from bbc-a11y on errors related to font-sizing using pixels. See my issue: https://github.com/bbc/bbc-a11y/issues/262

**Comment by radiocontrolled** [comment]
There is now a partial fix for this in `latest` with a `<main role="main">` added to simorgh: https://github.com/bbc/simorgh/issues/373

Simorgh issue 336 depends on the following bbc-a11y being fixed: https://github.com/bbc/bbc-a11y/pull/266 . When that is fixed in bbc-a11y, we should remove the skipped test in https://github.com/bbc/simorgh/blob/latest/a11y.js#L3 and address any bugs that arise.

**Comment by greenc05** [comment]
@radiocontrolled you may of missed my message on Monday, as @andymsuk has been kind enough to very promptly address the Issue you created https://github.com/bbc/bbc-a11y/pull/266 to fix our errors related to font sizing, please could you (and/or @jtart) return the favour and review the fix @andymsuk has done (complete re-write of the test) https://github.com/bbc/bbc-a11y/pull/266
