### ISSUE TITLE
Question: How should we trigger tracking of events

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#3365]
**Is your feature request related to a problem? Please describe.**
Based on the event tracking spike https://github.com/bbc/simorgh/pull/2957, we need to agree on the way we want to track components.

The original spike uses `addEventListener` to each component to be tracked, which keeps the logic in Simorgh, however using `onClick` in the component itself was also mentioned.

**Describe the solution you'd like**
Discuss and decide on the best approach. 
Document pros and cons of the methods mentioned above to decide on the way forward.

**Describe alternatives you've considered**
Stick to what's on the spike, but that's not very democratic of us.

**Comment by jamesbhobbs** [comment]
I don't think this should be a question. Event listeners seem significantly better, rather than try to say why myself: https://stackoverflow.com/questions/6348494/addeventlistener-vs-onclick Also due to how our components are split between this repo and used in another, this should mean fewer PRs to deliver and remove the events.

NB event delegation as a concept should be written up along with the docs we write on how to add events, this link might help https://davidwalsh.name/event-delegate

PS there was a good question about whether this would happen on every react render (https://github.com/bbc/simorgh/pull/2957/files#r315784760), there are several ways to avoid this, I found this nice writeup, in which the latter hook method is obviously cleaner: https://atomizedobjects.com/blog/react/add-event-listener-react-hooks/

**Comment by dr3** [comment]
I think this should work as a context around the application. You add a click listener to the document, and use `const { addListener } = useContext(EventContext)` then call `addListener('click', 'navigation', frontpageNavClickHandler)`. This `addListener` function will add the click event type onto an object.

When a click happens on the page, it checks the `data-type` attribute, if it equals ('navigation') it calls the `frontpageNavClickHandler` function. This function does all the ATI stuff for you.

The advantage of this is its scaleable to any type of event listener and any number of them. This also has the advantage of only creating 1 event listener on the whole page, not 1 per type or 1 per item, which is better for performance

(this is a rough idea, so may need cleaning up)
