### ISSUE TITLE
Add translations for cookie and privacy banner for Tigrinya 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3411]
**Is your feature request related to a problem? Please describe.**
We need to add the cookie / privacy banner translations for Tigrinya 

**Describe the solution you'd like**
Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-30)

- Tigrinya 

Check with UX  to ensure the length of the translations are suitable (not too long)

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to need a tester due to simplicity

**Additional context**
WSMEDIA-30

**Comment by LilyL0u** [comment]
EDIT: The translation on test page is showing the non-uk content, instead of UK content. I am raising a bug for this.

The translation sheet says ከም  [hyperlink]ኩኪታት[/hyperlink]  ዝኣመሰሉ with spaces either side of the link.
The cookie banner is however displaying ከም ኩኪታትዝኣመሰሉ with the link running into the next word. This language seems to use spaces between words, and this could be the equivalent of English text saying something like 'such as cookiesand collecting browsing data'.

I think we need a space after the linked word which is a translation of the word cookies: ኩኪታት

@ibMadbouly

**Comment by gavinspence** [comment]
Done
