### ISSUE TITLE
Change the privacy banner's cookie logic

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3446]
**Is your feature request related to a problem? Please describe.**
The logic for the privacy banner needs to change - instead of tracking whether the user has seen it, we want to track which version of the privacy policy was in place when the banner was seen.

**Describe the solution you'd like**
Change the privacy banner logic so that:
- if a user has no ckns_privacy cookie, display the banner
- if a user has the ckns_privacy cookie, but its value is `0` or `1` then display the banner
- if a user has the ckns_privacy cookie, and its value is `july2019` then do not display the banner
- if a user has the ckns_privacy cookie, and its value is not `0`, `1`, or `july2019` then do not display thhe banner (as the assumption here is that it has a future value we don't know about yet)
- when the banner is displayed to the user, set the ckns_privacy cookie value to `july2019`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
|Cookie name | Value | Behaviour of Privacy banner |
|-- | -- | -- |
| ckns_privacy | not present or value is undefined or null | Show banner |
| ckns_privacy | `'0'` or `'1'` (e.g. previousVersion) | Show banner |
| ckns_privacy | `'july2019'` (e.g. currentVersion) | Do not show banner |
| ckns_privacy | `'anythingelse'` | Do not show banner |

In future, if there will be for example a `'july2020' updated version of the policy we will add logic so that 
```
const previousVersions = ['0', '1', 'july2019'];
const currentVersion = 'july2020';
```
Then in this case if someone has a previousVersion they *should* be shown the banner.  

@jimjohnsonrollings is this correct? I notice the main description has just been updated.

**Comment by jimjohnsonrollings** [comment]
Yes 👍
