### ISSUE TITLE
White space below footer when page contains little content

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3613]
**Describe the bug**
The footer sits right up underneath the page content, so when a page has little content there is visible white space below the footer.

**To Reproduce**

1. Go to https://www.bbc.com/korean/bbc_korean_radio/liveradio
4. See whitespace below footer

**Expected behavior**
The footer should always sit at the bottom of the page when there is not enough content to fill the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/14273378/70797625-c545a180-1d9c-11ea-9349-ea6290423617.png)

**Testing notes**
Ensure the footer sites at the bottom of the screen and has no white space below when viewing a page with little content i.e. https://www.bbc.com/korean/bbc_korean_radio/liveradio

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
hey @oluoluoxenfree just a bit of a suggestion as to how to progress with this issue, through experimenting in dev tools, I managed to implement the flexbox version of this pattern for sticky footers: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers#Alternate_method

- I set the `min-height` of the `root` div to be `100vh` so the root div is at least the size of the view port - it will expand beyond this on pages with more content
- I set the display to `flex`
- I set `flex-direction` to `column` to flex down the page (rather than horizontally across the row)
<img width="531" alt="image" src="https://user-images.githubusercontent.com/9645462/72342824-50c89000-36c5-11ea-8181-12913b5b96ec.png">

- I added `flex-grow: 1` to the `main` element so it fill all available space between `<header>` and `<footer>`
<img width="598" alt="image" src="https://user-images.githubusercontent.com/9645462/72343319-7a35eb80-36c6-11ea-945d-b22157e4e27e.png">
