### ISSUE TITLE
Rich Media not being Captured in WS_LANGUAGES_TEST

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3668]
**Describe the bug**
RIght now we're capturing values for rich media tracking in ATI but nothing is being captured in WS_NEWS_LANGUAGES_TEST 

We need to investigate why none of these values aren't being captured. 
It may be an issue with SMP or with Echo and Orbit. 

**To Reproduce**

1. Go to test.bbc.com/amharic/bbc_amharic_radio/liveradio 
2. Open the ATI tag inspector in Chrome dev tools 
3. Click on the play button
3. Note the richMedia event in the tag inspector 
4. Now log in to ATI explorer: https://explorer.atinternet-solutions.com/
5. Navigate to content > RichMedia 
6. Select the destination as WS_LANGUAGES_TEST
7. Select today, yesterday and the last 7 days 
6. Note that no data has been captured for rich media (except 2 instances of arabic and persian tv) 

**Expected behavior**
Richmedia events on test should be captured on WS_NEWS_LANGUAGES_TEST, and playback should remain working. 

**TESTING**
Visit https://www.test.bbc.com/korean/bbc_korean_radio/liveradio ensure there is real playback. Then check that rich media tracking in ATI is returning `WS_NEWS_LANGUAGES_TEST` for the liveradio pages on TEST

**Screenshots**
![image](https://user-images.githubusercontent.com/22519682/64525334-849b3f80-d2f8-11e9-9781-782ab8675cc3.png)

**Additional context**

**Comment by ryanmccombe** [comment]
Problem is:

- Environment is currently hardcoded as `live` here: https://github.com/bbc/mozart-page-configs/blob/master/configs/ws/av_embeds_media.json#L5
- This was done because we need to use the live mediator, here: https://github.com/bbc/morph-modules/blob/master/news-av-player/src/smp.js#L60
- This is necessary because live assets are not available on the test mediator
- A side effect of hardcoding environment to live is that we now report the wrong destination to ATI, based on this logic: https://github.com/bbc/morph-modules/blob/master/news-av-player/src/smp.js#L15-L17

Two possible solutions

**Split out mediator and analytics environments by adding an additional prop**
Would also need updates to Mozart - eg, https://github.com/bbc/mozart-routing/blob/5c2c5d07a55b845261f9a023dc880ebb205b0f6e/src/lib/mozart_routing/payloads/ws_av_embeds_media.rb#L11

**If the asset is a live asset, force the morph module to use the live mediator**
https://github.com/bbc/morph-modules/blob/52fa1687a9f58d9b81da27c8c5e015eadcc1601f/news-av-player/src/smp.js#L30

**Comment by pjlee11** [comment]
My suggestion would be to have an optional override for the mediator environment. This way we can set the `enviornment` prop back to being the current env (EG: test or live) to fix tracking while also allowing the optional to override the mediator env for the live radio use case therefore keeping real live stream playback on `www.test`

**Comment by pjlee11** [comment]
Screenshot showing stats destination correctly set to `WS_NEWS_LANGUAGES_TEST`
![image](https://user-images.githubusercontent.com/7791726/64797354-36e13a00-d579-11e9-9511-fac359cb5eb4.png)

**Comment by LilyL0u** [comment]
Rich Media is now being captured in WS_NEW_LANGUAGES_TEST:

![Image 13-09-2019 at 14 53](https://user-images.githubusercontent.com/54575620/64867916-3e1a4d80-d636-11e9-8ded-51c9dca4e6c2.jpg)

@aeroplanejane :)
