### ISSUE TITLE
Variants - Cypress test multiple variants

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3698]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/3509 we have service variants, but we currently only test 1 per service. 

**Describe the solution you'd like**
Test all variants of services

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment]
A maybe solution described in here https://github.com/bbc/simorgh/pull/4190 but having some console issues.

**Comment by PriyaKR** [comment]
imo the simplest way is to repeat the three services with variants in config file rather than creating a array for variant:[lat,cyr] and having the pagetypes for each variant which would need updating all the test files eg - have done it for errorPage404 in here https://github.com/bbc/simorgh/pull/4190
