### ISSUE TITLE
ATI appears to capture two page loads on one visit in Tag Inspector

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3777]
**Describe the bug**
Using ATI Tag Inspector, when I load the live radio page, two URL rows appear in the tag inspector per visit. They have all the same metadata apart from the page load is always 1ms for one, and a more realistic page load time for the other (130-140ms).

**To Reproduce**

1. Go to https://www.test.bbc.com/korean/bbc_korean_radio/liveradio
2. Open the Tag Inspector in developer tools
3. Reload page
4. See the rows appearing in the Tag Inspector

**Expected behavior**
One page visit should capture one page visit

**Screenshots**

![Image 16-09-2019 at 14 52](https://user-images.githubusercontent.com/54575620/64963738-a9139080-d891-11e9-9b11-68dbd057f876.jpg)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: 76.0.3809.100

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This may mean we have inaccurate reporting in ATI of how many visits to the page there have been, and also page load times.

**Comment by pjlee11** [comment]
We have a hunch that having the iframe on the page causes the second page track as this bug is currently not present on the MAP without an iframe, we should check after we add the iframe. 

Also it could be that SMP is reporting to ATI.

**Comment by ryanmccombe** [comment]
With the iframe now on the MAPs page, this bug is appearing there too

![Screen Shot 2019-11-04 at 12 12 53](https://user-images.githubusercontent.com/8601460/68120134-81898d80-fefc-11e9-81e9-fb92b6d77b13.png)

I'm fairly confident this bug is with the tag inspector - not with us

The network traffic only shows one request to ATI, and the analytics dashboard also only shows one request to ATI.

![Screen Shot 2019-11-04 at 12 13 10](https://user-images.githubusercontent.com/8601460/68120143-877f6e80-fefc-11e9-9338-6246d5b15075.png)

My suggestion would be to close this issue

**Comment by aeroplanejane** [comment]
@gavinspence says this is fine
