### ISSUE TITLE
Add articles-validator to simorgh

### ISSUE THREAD

**Issue by oluoluoxenfree** [bbc/simorgh#3853]
**Is your feature request related to a problem? Please describe.**
Relates to #3697. 

We're removing the data validator in simorgh and want to use https://github.com/bbc/articles-validator instead.  

**Describe the solution you'd like**
"While we await Ares to integrate the validation logic into production we should use the articles-validator schema along with ajv in the deploy pipeline to validate our article fixture data."

**Describe alternatives you've considered**
Not validating the fixtures.

**Testing notes**
Doesn't require any testing from a tester - the data validation will be added to pipeline and run as a part of pipeline.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
This involves;

1) Adding the new articles data validator as a dev dep to Simorgh
2) Adding a pipeline step in CI (Jenkinsfile) to run the new validator in our CI pipeline

**Comment by thekp** [comment]
The initial issue was to add `articles-validator` to the Simorgh pipeline. 

However, the article-validator is currently a private repo and is only validating against some fixture data. More work is required in this repo (https://github.com/bbc/articles-validator), so that it is published to BBC's private npm repo and for it to validate against real data. 



Furthermore, @hindsc52 will discuss with others to confirm if using articles validator is necessary and who would be in charge of keeping the repo updated.
