### ISSUE TITLE
Storybook knobs aren't working

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3896]
**Describe the bug**
inputProvider service toggling isnt working

**To Reproduce**

1. Go to https://bbc.github.io/simorgh/?path=/story/containers-header--default
2. Flick through other services
3. See no change

NB: After investiating, it appears storybook `addon-knobs` are entirely broken in simorgh. They show, but changing them have no affect

**Expected behavior**
It changes for each service.

**Screenshots**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
I'd like to pick this up.

**Comment by mykeels** [comment]
Turns out adding a button,  then clicking it would re-render the component.

Why it doesn't auto re-render, when the `select` value is changed, I'm still not sure of.

**Comment by samora** [comment]
This seems to be broken in multiple places and not just the Header.
https://bbc.github.io/simorgh/?path=/story/containers-copyright--default
https://bbc.github.io/simorgh/?path=/story/containers-footer--default

I think the `ServiceContext` is where the issue is but I'm yet to pin it. Maybe you can help me out @dr3?

**Comment by dr3** [comment]
@samora Sure, ile take a look now :)

**Comment by dr3** [comment]
I dont think its the service context, using the code below, the service switch dropdown still doesnt work
```jsx
storiesOf('Containers|Brand', module)
  .addParameters({ chromatic: { disable: true } })
  .addDecorator(withKnobs)
  .add(
    'default',
    inputProvider({
      // eslint-disable-next-line react/prop-types
      componentFunction: ({ service }) => (
        <h1>{service}</h1>
      ),
      services: Object.keys(services),
    }),
  );
```

**Comment by dr3** [comment]
Infact, even the `addon-knobs` example in their repo does work
```jsx
storiesOf('Containers|Brand', module)
  .addDecorator(withKnobs)
  .add('as dynamic variables', () => {
  const name = text('Name', 'Arunoda Susiripala');
  const age = number('Age', 89);
 
  const content = `I am ${name} and I'm ${age} years old.`;
  return (<div>{content}</div>);
});
```

Gunna rename this issue

**Comment by hotinglok** [comment]
Paired with @mykeels on this today and did a bit of investigation work. Here's what we found:
- Originally we thought that the cause may have been changes to their API from bumping which we didn't notice but since everything still works fine in Psammead, we concluded that this is probably not the case.
- We then tried to copy a working story with knobs from Psammead into Simorgh which resulted in it not working which lead to us to believe that it was something to do with the way that we run Storybook in Simorgh.
- Comparing individual stories of the same components in both didn't lead anywhere so we realised that it must have been something to do with either the `config.js` or the `webpack.config.js`. 
- ~@mykeels finally found what might be causing our issue here~: https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode
The `webpack.config.js` in Psammead is already setup in this way where it exports a function to enable 'full control mode' whereas Simorgh currently exports it as an object which according to the documentation above will be deprecated very soon. This might not be actual solution but it is the closest thing we have so far. 
- Upon further investigation this didn't change much, knobs are still broken. Logging in verbose shows that in psammead, there are more things in the response when you change a knob:
![image](https://user-images.githubusercontent.com/53564281/66412443-77ec3300-e9ed-11e9-8c3a-a00ceec54b75.png)
Compared with just the one message in Simorgh:
![image](https://user-images.githubusercontent.com/53564281/66412481-876b7c00-e9ed-11e9-9f2c-98bcbd83756e.png)
The `forceReRender` is very suspicious.

Will carry on investigating to see if we can implement this and see if this makes any difference.

Should also be noted that when resizing the window, it triggers a re-render which makes changes what is displayed to what is being currently set by the knob (ie. making it so that selecting different knobs actually works)

**Comment by mykeels** [comment]
We finally found out that setting [timemachine](https://github.com/schickling/timemachine) globally in `.storybook/config.js`, was the culprit.

Since it's only useful for ArticleTimestamp stories _(and similar)_, it should be restricted to those components, and reset when they're unmounted.

**Comment by hotinglok** [comment]
*Cause of the original issue with storybook knobs:* 
`timemachine` was somehow disabling the `setTimeout` event from occurring so even though the knobs registered that there was a change. The culprit is potentially the `tick` being set to `false` by default.

*Solution and problems thus far:*
- Making `timemachine` a `testhelper` which is then added via a decorator to each component affected by chromaticqa with the logic that the `testhelper` sets `tick` to allow knobs functionality and then resets the time in order to get the correct time for chromaticqa. Ticking in this attempt was still running even after the reset however as we originally thought we needed it to in order to preserve functionality of the knobs.

This worked until we saw the live timestamp on FrontPage | Pidgin which only rendered a '0' as well as other seemingly random timestamps appearing as 1 unit of time behind what it was supposed to be when run against chromaticqa snapshots (Eg. 5 seconds -> 4 seconds, 1 hour -> 59 minutes). This behaviour is suspected to be because it is a second or two faster than what it was before so the units are rounding down.

- Using the newly made `testhelper` as a global decorator and resetting it twice instead of twice solved the issue of the live timestamp failing but there are still some remnants of being 1 second behind in internet explorer for certain timestamps.
