### ISSUE TITLE
Scotland footer links display error

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#3950]
**Describe the bug**
On a BBC Scotland article page: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
The footer links are not displaying correctly.

**To Reproduce**
1. Go to: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
2. Scroll to the end of the page
3. The 'Terms of Use' link is where the 'Why you can trust the BBC' link usually is. The rest of the footer links are spread along the row below.

![Footer1](https://user-images.githubusercontent.com/52247014/65508448-1e054c80-dec8-11e9-86cb-e7cdd3a1bfc8.JPG)

**Expected behavior**
The footer links should all appear in the same section of the footer. E.g. 
![Footer2](https://user-images.githubusercontent.com/52247014/65508455-22ca0080-dec8-11e9-84a6-0d00f9ea3957.JPG)

Note: There should be no 'Why you can trust the BBC' link. Nothing should take its place when this link is not present.

**Screenshots**
See above.

**Desktop (please complete the following information):**

- iOS and Windows

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by amywalkerdev** [comment]
Note this will require changing how we currently lay out the list items in the grid in the sitewide links component, and possibly changing how we group the links from the config? Worth checking the suggested implementation with all pods to make sure its a good approach.

**Comment by sareh** [comment]
I'd suggest splitting this work up in this way:

- 1 A PR in Simorgh to update the Service configs to have the trust project link listed separately from the list, keeping the trust project link still in the footers array link for now. 
```
    footer: {
      trustProjectLink: {
        href: '...',
        text: '...',
      },
      externalLink: {
        href: '...',
        text: '...',
      },
      links: [
        {
          href: '...',
          text: '...',
        },
...
      ],
      copyrightText: "...",
    },
```

- 2 A PR to `psammead-sitewide-links` that's a breaking change, to add the `trustProjectLink` prop and the logic to have the different layout if a `trustProjectLink` is not passed in. (Note: the reason this needs to be a breaking change is that otherwise we'd immediately get the changes upstream, meaning two Trust project links appearing.)

- 3 A PR in Simorgh that pulls in this updated `psammead-sitewide-links` package and removes the trust project link from the service config `footers.links` array.
