### ISSUE TITLE
Live Radio page for Afaan Oromoo has embedded recursive page displayed

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#3976]
**Describe the bug**
The Live Radio page for Afaan Oromoo is currently showing an embedded version of the entire live radio page instead of the audio player.

**To Reproduce**
1. Navigate to https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio
(issue is present on stage too)
2. See screenshot below
![image](https://user-images.githubusercontent.com/53176209/65669518-a0624d80-e03b-11e9-815f-4edf05af6969.png)

**Expected behavior**
The audio player controls should be displayed

**Testing notes**

- [ ] This bug fix is expected to need manual testing.
- [ ] *Note* Automated e2e tests must be re-enabled

**Comment by aeroplanejane** [comment]
Might be caused by change to payload: https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_afaanoromoo_radio/liveradio
To clarify - we require 'bbc_afaanoromoo_radio' in the URL only e.g. 'bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio' - everything else can be 'bbc_oromo_radio' This is the service id for afaan oromoo radio and this is what we must pass to SMP for playback

**Comment by aeroplanejane** [comment]
Might be related to this recent fix: https://github.com/bbc/simorgh/issues/3849
