### ISSUE TITLE
Tests for ability to render special characters

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#401]
**Is your feature request related to a problem? Please describe.**
We want to add some tests to check that we can render a list of special characters in a Headline, SubHeading and text (paragraph). The list of special characters is here https://confluence.dev.bbc.co.uk/display/NEWSART/Text+-+Glyphs.

We now have a test article containing all of the characters: `cev804m5n0vo`.

**Describe the solution you'd like**
~This should be in the form of cypress tests. Current consensus is leaning towards an initial manual check, opening tickets to fix as needed, & enforcing long-term via screenshot tests.~

Update: Following the creation of #1370 we have agreed that we can MVP a manual check for the Testers to perform which should be added to the Articles Test Steps. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Manually test that all of the special characters display as expected across numerous devices/browsers. We can implement screenshot tests once these has been enabled.

**Additional context**
n/a

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Tried out a little POC in #908, think this needs some dev & test refinement before looking at again.

**Comment by ChrisBAshton** [comment]
In addition, looks like we'll need to [mark up some special characters for a11y reasons](https://github.com/BBC-News/simorgh/pull/908#issuecomment-437805482). Let's refine the issue.

**Comment by ChrisBAshton** [comment]
EDIT: we actually cover the marking up of special characters in #402.

**Comment by sareh** [comment]
@jamesbrumpton Could you let me know where you'd prefer to have these manual test instructions? 

I also haven't yet specified the exact browser/devices to test on, since I thought you would want to input on that. 

**~**

When there is a change to a Font implementation, or to a Heading, Caption or Text component, we should do a manual regression test of special characters. This is to ensure our changes do not affect the rendering of these characters in the browser. 

This article has special characters in the headline, subheadline, caption & paragraphs:
- Test https://www.test.bbc.com/news/articles/cev804m5n0vo 
- Local http://localhost:7080/news/articles/cev804m5n0vo

The characters should be using Reith and rendering correctly. See this screenshot: 

![screenshot_2019-03-08 test article for special characters](https://user-images.githubusercontent.com/3028997/54025522-b1786980-4192-11e9-89fd-9c78ca881f8b.png)

These should be regression tested on a subset of the browsers/devices that we support. [.....]
In a future we will automate this manual process with snapshot testing.
