### ISSUE TITLE
Render super/sub script in Fragments

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#402]
For a subscript, the tag `<sub></sub>` should be used. For a superscript, `<sup></sup>` should be used.

For example, for carbon dioxide CO2  should have a subscript of 2, or E=mc2 with the superscript 2.

**Solution**

Add a `super` and `sub` component in the Fragment components, similar to the [bold and italic components](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Fragment/index.jsx#L4-L5).

Ensure they styling is consistent across browsers.

**Testing notes**
[Tester to complete]

Dev insight: We should have unit tests within the fragment container. We shouldn't need an integration test. 

**Additional Context**

The styles for `sub` and `sup` are already in the Normalize file, which we have imported globally. So the styling should 'just work'. 

```
sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}
sub {
  bottom: -0.25em;
}
```

**Comment by jtart** [comment]
Blocked until have clearer idea of what super/sub scripts will look like in passed data.

**Comment by sareh** [comment]
Unblocked since we have examples of subscript and superscript in our data:
https://github.com/bbc/simorgh/blob/9408f50c14b56d1161b4470e73f1a59a66612c11/data/test/news/articles/c0000000005o.json#L83
https://github.com/bbc/simorgh/blob/9408f50c14b56d1161b4470e73f1a59a66612c11/data/test/news/articles/c0000000003o.json#L183
https://github.com/bbc/simorgh/blob/53c605555f14074740bb9543caa9c797d6643f49/data/test/news/articles/c0000000002o.json#L197
https://github.com/bbc/simorgh/blob/0a3e2c6b43c2b9d0b4173c0ccd2ffc8dd4e52c00/data/test/news/articles/c0000000006o.json#L105

Visiting article 2 locally shows that the superscript is not being applied (http://localhost:7080/news/articles/c0000000002o)
<img width="1158" alt="Screen Shot superscript" src="https://user-images.githubusercontent.com/3028997/55811087-7d210180-5ae0-11e9-8734-62936b29e622.png">

**Comment by jimjohnsonrollings** [comment]
Optimo hasn't implemented this, so nor should we.  Probably we should close this and remove those attributes from the fragments in the scenario data.
