### ISSUE TITLE
Add padding to the bottom of Media Player

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#4239]
**Is your feature request related to a problem? Please describe.**
Currently there is no padding below the media block, so there is no space when a media block is followed by another content block. See example test article here showing the lack of padding between a media block and subsequent text, image, and other media blocks: https://www.test.bbc.co.uk/news/articles/cjn0qpz3jjvo

**Describe the solution you'd like**
Add 24px of padding after the media block using gel spacing. 
Zeplin designs here: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa88971d341fae3fd53

**Describe alternatives you've considered**

**Testing notes**
- Would need manual regression across browsers and devices

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

Screenshot of media block followed by text block, with no padding:
![image](https://user-images.githubusercontent.com/52247014/66848538-2ef82980-ef6d-11e9-9034-3f4d85b85a73.png)

And of media block followed by an image block:
![image](https://user-images.githubusercontent.com/52247014/66848586-433c2680-ef6d-11e9-8451-914c12321e75.png)

**Comment by simonsinclair** [comment]
@lizcameron, as discussed, we should combine this with https://github.com/bbc/simorgh/issues/4647, because where the bottom margin to Media Player is applied is dependent on whether a figcaption is showing or not.

- if Media Player doesn't have a figcaption, apply `padding-bottom: ${GEL_PADDING_TRPL};` to Media Player.
- if Media Player has a figcaption, apply `padding-bottom: ${GEL_PADDING_TRPL};` to figcaption and ensure it is correctly spaced from Media Player.

Cc @RayNjeri
