### ISSUE TITLE
CPS Pages - Any blocks with `bold` or `italic` dont transform on client correctly

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#4408]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:7080/igbo/afirika-23252735
2. Click on `Test MAP to MAP inline link`
3. See blocks
4. Refresh
5. See more blocks

**Expected behavior**
All blocks render, with no different on server to client

**Desktop (please complete the following information):**

Mac Chrome 77.0.3865.120

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
This only happens against `npm run build && npm run start`. It only happens on client renders. It only happens on blocks with `markup_type: candy_xml`. It weirdly renders the `urlLink` inside of a `candy_xml` block but not the paragraph text and not the bold or italic text. 

This is a damn weird bug.

**Comment by pjlee11** [comment]
Drumroll please..... 🥁 

So the culprit of this bug seems to be [this line](https://github.com/bbc/psammead/blob/92738b890aebe5a73afc4e648c4ce7f9628f0848/packages/utilities/psammead-rich-text-transforms/src/candy-xml.js#L12) which checks if the `node.constructor.name` is `XmlTextNode`. However, on the client the `constructor` has been minified to the function `i` and therefore the `if()` linked above returns false. 

![image](https://user-images.githubusercontent.com/7791726/67507270-7c1f7e00-f686-11e9-94d6-e64734bc6778.png)
_console.log() of the `node.constructor` and `node.name` when the code executes on the client_

Therefore we should be able to change that if statement to the less explicit:
```
if (node.text) {
  return fragment(node.text, attributes);
}
```
Because the `text` field on the `node` performs the same logic.

**Comment by pjlee11** [comment]
As the following GIF shows all text inside of the `candy_xml` blocks is not rendered do the the bug mentioned above by the minification of the code. 

![Client side parsing failing](https://user-images.githubusercontent.com/7791726/67566081-d0763c80-f71e-11e9-87b6-7e50ac87a691.gif)
