### ISSUE TITLE
[Spike] Investigate Lighthouse 5 Opportunities

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4482]
**Is your feature request related to a problem? Please describe.**
Lighthouse 5 is likely to include features that will make some of our custom tooling redundant

https://github.com/GoogleChrome/lighthouse/releases/tag/v5.0.0

The main opportunity is likely to be performance budgets: https://developers.google.com/web/tools/lighthouse/audits/budgets

**Describe the solution you'd like**
We already run Lighthouse as part of our CI - investigate if these new features can be used in place of any other part of our CI - eg, the bundle size check, or `scripts/lighthouseRun.sh`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Research spike - no testing required

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DemonusPC** [comment]
Ok this actually depends on what we are trying to improve. 
We dont actually run lighthouse performance on CI. Running a performance check on a localhost server is redundant. We only check for the local relevant categories (everything except performance)
While the new features are great, the lighthouse-ci module would not help us, since the lighthouse-ci server has no authentication.... And we cannot have something like that with public write access. We would need to have a conversation on what specificn new features of lighthouse would help you guys deliver faster.  
On CD thats a different story.
