### ISSUE TITLE
Placeholder image

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#449]
**Is your feature request related to a problem? Please describe.**
Users should have a visual indication of when an image needs to load or is simply missing (after failing to load).

**Describe the solution you'd like**
Add a placeholder image to all lazy-loaded images.
This will be displayed before images are loaded client-side or the request fails.

**Testing**
- Automated test for checking the presence of the placeholder
- Manual tests where we throttle an image request and even drop the connection for an image

**Comment by greenc05** [comment]
For the scenario where the request fails and the placeholder image is shown, what alt text we want for the placeholder image should be considered.

**Comment by sareh** [comment]
On other News pages (e.g. https://www.bbc.co.uk/news) the placeholder is the 'BBC blocks' image. This is base64-encoded and included as a background image.
You can inspect this on the News front page by finding the class `.gs-o-responsive-image`. 
```
.gs-o-responsive-image {
    position: relative;
    height: 0;
    overflow: hidden;
    background-color: #f0f0f0;
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zd…YtMy41MzRIMTQuOTY0ek0wIC4wMTZoNTcuMDQ0VjUzLjdIMFYuMDE2eiIvPjwvZz48L3N2Zz4=);
    background-repeat: no-repeat;
    background-position: 50%;
    background-size: 30%;
}
```

Do we want to repeat this pattern for these article pages? 

This addresses @greenc05 's comment about alt text, since here is a screenshot of it with alt text showing over the placeholder background:
![screen shot image placeholder](https://user-images.githubusercontent.com/3028997/43899662-86e25374-9bda-11e8-8d57-65784c438afc.png)

**Comment by BogdanDogaru** [comment]
Blocked:
- [ ] on #448 and its implementation PR(s)

**Comment by nataliesmart** [comment]
![bbc_news_placeholder](https://user-images.githubusercontent.com/30656637/44021616-29d19252-9edd-11e8-8c83-8a718deeac71.png)

**Comment by pjlee11** [comment]
Blocked until https://github.com/bbc/simorgh/pull/652 is merged
