### ISSUE TITLE
Navigation links not working properly for variants

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#4557]
**Is your feature request related to a problem? Please describe.**
Right now navigation links on services with variants (ukchina, zhongwen, serbian) are only working on frontpages. E.g. if you are on a `ukchina/trad` homepage and you click on any navigation link, you get redirected to a url on the correct variant. However, if you are not on the homepage but on a topic page (e.g. on `ukchina/trad/sport`) and click on `ukchina/trad/video` then you get redirected to `ukchina/simp/video`.

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
>In addition, going to http://localhost:7080/zhongwen or http://localhost:7080/ukchina returns a 404 page instead of redirecting you to either /simp or /trad.

This is an issue currently being worked on by the core pod.

**Comment by PriyaKR** [comment]
4560 is unrelated to this issue.

**Comment by AlistairGempf** [comment]
I've had a quick look at this and the problem is not with the `Navigation`, but with our routing. The route `/serbian/cyr/some_non-existent_page` doesn't match any of our regex, as expected since it isn't one of our pages, so we don't get a variant, which means that it uses the default variant in the `Navigation`. This is actually the case with the `service` too, but [this line](https://github.com/bbc/simorgh/blob/582d91df90f1423323b620ccdef891b214eabb5c/src/app/routes/utils/fetchPageData/utils/getRouteProps/index.js#L24) gets us a fallback for the service that makes sense. We can do something similar with variants to solve the issue.

**Comment by AlistairGempf** [comment]
I've had a quick look at this and the problem is not with the `Navigation`, but with our routing. The route `/serbian/cyr/some_non-existent_page` doesn't match any of our regex, as expected since it isn't one of our pages, so none of our regex matches. This is actually the case with the `service` too, but (this line)[https://github.com/bbc/simorgh/blob/582d91df90f1423323b620ccdef891b214eabb5c/src/app/routes/utils/fetchPageData/utils/getRouteProps/index.js#L24] gets us a fallback for the service that makes sense. We can do something similar with variants to solve the issue.

**Comment by OlgaLyubin** [comment]
Tested this for Ukchina `simp` and `trad` services as well as for Serbian `lat` and `cyr` and this issue has been fixed.
