### ISSUE TITLE
Non-JS tracking is not working on new front pages (and maybe other page types?)

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#4711]
**Describe the bug**
Non-js tracking is not tracking any page views of new Simorgh front pages in ATI. 
The existing front pages on PAL are tracking page views in ATI. 

This means it is not tracking anything on the following pages:
igbo.page
pidgin.page
yoruba.page
punjabi.page
thai.page
azeri.page
kyrgyz.page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Looking at the Thai front page `https://www.bbc.com/thai` and disabling JS, I see the network request made to ATI:
`
https://a1.api.bbc.co.uk/hit.xiti?s=598342&s2=90&p=thai.page&x1=[urn:bbc:cps:3fd51a2d-70f9-c435-e050-380a4e80342f]&x2=[responsive]&x3=[news-thai]&x4=[th]&x7=[index-home]&x9=[%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B9%81%E0%B8%A3%E0%B8%81+-+BBC+News+%E0%B8%9A%E0%B8%B5%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B9%84%E0%B8%97%E0%B8%A2]&x11=[2016-10-27T10:36:34.000Z]&x12=[2019-11-27T09:10:12.000Z]
`
Same with the other Simorgh pages. So I'm interested in knowing whether there are specific values that are incorrect.

**Comment by sareh** [comment]
Comparing with a front page that is currently still on the previous technical stack, e.g. `https://www.bbc.com/mundo` I see this ATI network request
`https://a1.api.bbc.co.uk/hit.xiti?&col=1&from=p&ptag=js&s=598253&p=mundo.page&x1=[urn:bbc:cps:327bd4c8-3bff-27bf-e050-380a4e805a61]&x2=[responsive]&x3=[bbc_website]&x4=[en]&x7=[index-home]&x8=[reverb-1.2.0-nojs]&x11=[WS_NEWS_LANGUAGES]&x12=[MUNDO]`

**Comment by PriyaKR** [comment]
Also the non js article pages are not being tracked by ATI.For eg https://www.bbc.co.uk/news/articles/cj7xrxz0e8zo

**Comment by sareh** [comment]
Having talked with Alex, we have this following suggested solution.
We should add the `x8` aka library version parameter, to track js/nonjs requests.

We have 3 ways  ATI is called on Simorgh pages - one for AMP pages - which will always have `x8=[simorgh]`
Two for Canonical pages - one that’s using client-side Javascript which should have  `x8=[simorgh]` and one that’s in a `<noscript><img src="ATIurlhere"/></noscript>`  this should have `x8=[simorgh-nojs]` 

We don’t have simorgh versions in the traditional sense, so will look to add that later. If we do, should it be `x8=[simorgh-2.0-nojs]` `x8=[simorgh-2.0]` for non-js/js. This version number work is a future enhancement and should not need to be carried out in this ticket. 


The reason we're using this approach is because the PAL implementation using the Reverb library carries out a work-around to put all nonjs into a separate top-level destination bucket `598253`/`OTHER_BBC_NONJS` and we do not want to follow this. We would rather keep the buckets as they currently are in our application.
