### ISSUE TITLE
dependencyUpdateCheck does not always work

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#4725]
**Describe the bug**
The `dependencyUpdateCheck` script that is supposed to run whenever we merge sometimes does not work as expected. e.g.
```
$ git pull
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 23 (delta 11), reused 14 (delta 9), pack-reused 0
Unpacking objects: 100% (23/23), done.
From github.com:bbc/simorgh
   b1866a0a1..e3e6dfd0f  latest                                -> origin/latest
   b1955097f..51f3f088b  bump-react-deps                       -> origin/bump-react-deps
 * [new branch]          cypress-tests-multiple-variants-fixed -> origin/cypress-tests-multiple-variants-fixed
 * [new branch]          refactor-image-with-no-caption-e2e    -> origin/refactor-image-with-no-caption-e2e
Updating b1866a0a1..e3e6dfd0f
Fast-forward
 package-lock.json | 582 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------
 package.json      |  18 ++--
 2 files changed, 429 insertions(+), 171 deletions(-)
husky > post-merge (node v12.13.0)
mc-xxxx:simorgh yyyyy$
```

i.e. why was `npm install` not triggered here?

Question: Should this script be removed?

**To Reproduce**
Steps not known.

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
I think the problem is that it tries a `git diff origin/latest -- package-lock.json`, and counts the number of changes between both. However, if your current branch is `latest`, and you'd just pulled, there'd be no changes, and `npm install` won't run.

We'll have to handle being on the `latest` branch differently.

**Comment by mykeels** [comment]
This [stackoverflow thread](https://stackoverflow.com/questions/2428270/git-how-to-diff-changed-files-versus-previous-versions-after-a-pull) recommends comparing using `git diff HEAD@{1}`, because that commit would be the commit just before the pull. We could use this when on the `latest` branch.

I'll work on a PR.
