### ISSUE TITLE
Update Article Timestamp to use `withServiceKnob` storybook-helper

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#4808]
**Is your feature request related to a problem? Please describe.**
Our current implementation for the Article Timestamp container creates a story for each service. We now have `withServiceKnob` functionality from the psammead-storybook-helper which allows us to add a list of services in a drop-down list for people to select from.

**Describe the solution you'd like**
update our implementation of the stories file for `ArticlesTimestamp` to use serviceKnobs:
- import { withServiceKnob } from psammead-storybook-helper into `src/app/containers/ArticleTimestamp/index.stories.jsx` and use the `withServiceKnobs()`.

example: https://github.com/bbc/simorgh/blob/a6cec7239c6e5403883f8472eead8178afef157b/src/app/containers/Brand/index.stories.jsx

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
~We should note that by making this change, we won't have Chromatic QA snapshots of each service variant, but just one of the default service.~
Since we've removed the Chromatic QA snapshots, this should be okay to be updated. Would be good to confirm with the Article pod prior to the change, so they're aware of it.
