### ISSUE TITLE
TopStory image doesn't occupy 50% of the width

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#4978]
**Describe the bug**
On chrome the `TopStory` span 6 columns out of 12. Meaning in IE11 the image should occupy `50%` of the width but it doesn't.

**Chrome**
<img width="945" alt="Screenshot 2019-12-18 at 10 54 11" src="https://user-images.githubusercontent.com/48688870/71068156-28fa1100-2187-11ea-8e21-6f3d1131d33a.png">

**IE11**
<img width="945" alt="Screenshot 2019-12-18 at 10 53 58" src="https://user-images.githubusercontent.com/48688870/71068219-53e46500-2187-11ea-9ef4-5f5bd2542585.png">

**To Reproduce**

1. Go to 'http://localhost:7080/news'
2. Use chrome 
3. Use IE11 
4. See the difference

**Expected behavior**
The image should occupy 50% of the width in IE11.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
@sadick254 It looks fine when bumping to the latest alpha version of the Story Promo in Simorgh.

<img width="1680" alt="Screenshot 2019-12-18 at 13 52 40" src="https://user-images.githubusercontent.com/46446236/71088062-e4c63b00-219d-11ea-94e5-5b388e54beec.png">

I don't think we can make a fix for now, since it is an alpha and it should be fine when integrating it in the new layout.

**Comment by ghost** [comment]
Ok. We can keep this open so that we don't forget about it when integrating the new layout.

**Comment by DenisHdz** [comment]
Checked this again on the new front page layout https://github.com/bbc/simorgh/pull/5139 and the top story image takes 50% of the width on IE11 as expected:

<img width="2004" alt="top-story-new-layout-ie11" src="https://user-images.githubusercontent.com/46446236/73735246-e1c7df80-4736-11ea-8b6d-018c63bdb5eb.png">
