### ISSUE TITLE
Simplify preprocessor rules for CPS assets

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5175]
**Is your feature request related to a problem? Please describe.**
The current preprocessor rules used for CPS assets such as PGLs are quite heavily coupled and interdependent. They also include bits of deep branching logic based on asset type.

We would like to make these rules easier to understand and safer to work with, also with a view to splitting them out into a separate service later on.

For further discussion see https://github.com/bbc/simorgh/pull/5153/files#r367517021

**Describe the solution you'd like**
Plan a solution that is easier to develop and maintain.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Thanks for creating this, and @jroebu14 's PoC looks good 👍 

If we are refactoring this though, I'd really encourage we consider moving at least the block data handling close to where the block renderer is, rather than using this preprocessor pattern for everything

eg, I think someone should be able to look at the ARES data, and the Simorgh renderer for that data, and understand what is happening

My original proposal was instead of using the existing pre-processor pattern, the CPS page would be doing things like this:

```js
const componentsToRender = {
    heading: block => <Heading>{transformHeadline(block)}</Heading>,
    text: block => <Text block={transformText(block)} />
}

render() {
    <GhostGrid>
        { generateVisuallyHiddenHeading(pagedata.meta) }
        { generateSummaryBlock(pagedata.meta) }
        <Blocks data={blocks} componentsToRender={componentsToRender} />
    </GhostGrid>
}
```
I understand the rationale for trying to make the code for such a core component as "clean" as possible, but I'd argue it's fallen way off the other edge.

The CPS page component is less than 100 lines, but every new developer who looks at it alongside the data is confused how it works, because it seems to be plucking blocks and block properties out of thin air

@karinathomas @rebeccarfmcginnbbc @RichardPK have more recent experience of trying to make sense of this :)

It's not just a dev experience / onboarding thing, it's also affecting our tests.

We have to replicate arbitrary bits of preprocessor logic in our jest tests if we want to use real data:

https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsAssetPageMain/index.test.jsx#L57-L71

or import the transformers and reuse them, which is also problematic because if a transformer breaks, an integration test will still pass because it is generating expectations from the same broken transformer

https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsAssetPageMain/index.test.jsx#L79

(apologies for the Friday rant!)
