### ISSUE TITLE
Analyse if a CSS grid fallback is required

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#521]
**Is your feature request related to a problem? Please describe.**
We are using CSS grid which requires a fallback for backwards compatibility with older browsers. 

**Describe the solution you'd like**
We should evaluate recent browser stats to see if we need to implement a grid fallback to maintain our 0.05% browser support metric. Following this analysis we should document our findings and then if required we should create a ticket to implement a grid fallback. 

**Additional context**
If possible the analysis should also take into account the world service sites and if the fallback is required for all world service and not news an issue should be opened in v1.1 instead of in v1

**Comment by bcmn** [comment]
Discussed the [screenshots of the issue](https://github.com/BBC-News/simorgh/issues/821#issuecomment-438605956) alongside the browser usage stats with Jim.

In summary:
Some WS sites see a reasonable amount of usage coming from affected versions of browsers. Instead of attempting a more full-featured fallback, we would like to establish a minimum width for the article body content on browsers that don't support CSS Grid. It's likely we will need to pair with UX to agree the specific width values.

The initial suggestion would be to be the constrained width would be static above the 1008px breakpoint, changing again at the 1280px breakpoint. The constrained width for the 0-1007 breakpoints would likely be dynamic, established as a percentage width for each breakpoint.

This work will be done in #821.
