### ISSUE TITLE
VoiceOver doesn't recognise dropdown navigation as a list

### ISSUE THREAD

**Issue by AlistairGempf** [bbc/simorgh#5214]
**Describe the bug**
When opening the dropdown navigation using VoiceOver on both iOS and macOS, each link is individually read out. 

**To Reproduce**

1. Go to a service's home page while on a mobile breakpoint
2. Turn on VoiceOver
3. Navigate to the exposed navigation
4. Notice that VoiceOver reads out that it is part of a list (the correct behaviour)
5. Navigate to the menu button
6. Select the menu button
7. Navigate to the list
8. Notice it is not read out as a list

**Expected behavior**
VoiceOver should say that the dropdown navigation is a list.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Safari
- Version: macOS Safari 13.0.3

**Smartphone (please complete the following information):**

- Device: iPhone XR
- OS: iOS 13.3
- Browser: Safari

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
The problem seems to be with the `visibility` css that we are using as part of the animation. removing that seems to make it work but we need that for the animation.

**Comment by AlistairGempf** [comment]
Raised as part of swarm from #4569.

**Comment by Bopchy** [comment]
Using HTML attribute `hidden` instead of the CSS `visibility: hidden` when the dropdown is closed, and removing `visibility: visible` from the styling fixes Voice Over not reading out the Dropdown as a list, however; it causes the dropdown itself to not be visually visible as its height is always `0`

**Comment by benjifellows** [comment]
I am trying to replicated this behaviour but VoiceOver is recognising the Dropdown Navigation as a list on my machine. 

Exposed Navigation
<img width="1227" alt="Screenshot 2020-03-11 at 11 27 44" src="https://user-images.githubusercontent.com/54984834/76412458-8dde9500-638b-11ea-8b20-6a022d02afb2.png">
Menu Button Clicked - Dropdown Navigation
<img width="844" alt="Screenshot 2020-03-11 at 11 28 08" src="https://user-images.githubusercontent.com/54984834/76412443-85865a00-638b-11ea-9c2e-cef5324c52cc.png">

**Comment by PriyaKR** [comment]
@benjifellows I have tried using voice over on safari on Mac OS desktop at mobile viewport and on iphone 11 it doesn't seem to mention the navigation as a list.

**Comment by benjifellows** [comment]
VoiceOver is recognising Dropdown as a list if the Menu button is pressed prior to VoiceOver being turned on. However it is not recognising the list if the Menu button is pressed using VoiceOver controls

**Comment by benjifellows** [comment]
As per investigation:
The DropdownNavigation component is being rendered when the home page initially loads in order to show an animation when the CanonicalMenuButton is clicked of the DropdownNavigation appearing. However, this is causing the issue whereby screenreaders are not recognising DropdownNavigation as a list when it is on screen - rather recognising it as a series of links.

We attempted to add a conditional to have the DropdownNavigation menu only get rendered when the CanonicalMenuButton is clicked - however this removes the animation and sets the height of DropdownNavigation to 0.

**Comment by greenc05** [comment]
Won't fix
