### ISSUE TITLE
Igbo fixture data for UsefulLinks removed which breaks Front Page Section story

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#5240]
**Describe the bug**
On the simorgh storybook (both online and localhost), the Front Page Section/useful links is broken due to missing fixture data in igbo for `useful-link`. This was added in this commit here: https://github.com/bbc/simorgh/commit/0fdc63461408fd164f3ce10e3cc3e3a0c17536df#diff-b7925515a1c96634c56e02f996f24a63  but for some reason it seems to have disappeared.

**To Reproduce**

1. Go to storybook
2. Click on Front Page Section/useful links
3. See error

**Expected behavior**
No errors and story to be displaying as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/53564281/72979159-a42a9480-3dcf-11ea-8df8-de6c9e8290f2.png)

**Desktop (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
Marked as having manual testing but just needs manual confirmation that story is working is fine on storybook.

**Comment by OlgaLyubin** [comment]
I think Useful Links were removed from Igbo data because we wanted the json to match test/live data (live Igbo website does not have useful links). So instead of adding useful links data back to igbo json we should just pass another data set to storybook here https://github.com/bbc/simorgh/blob/latest/src/app/containers/FrontPageSection/index.stories.jsx#L45
For example we can use Kyrgyz data since it contains useful links https://github.com/bbc/simorgh/blob/latest/data/kyrgyz/frontpage/index.json

**Comment by hotinglok** [comment]
After further investigation with @OlgaLyubin, we found that the useful-links data even in services with this in `./data/service/frontpage` is not fit into a "strapline" object, hence the items containing this data is never reached. The data does have a `semanticGroupName` but this does not fit the `pathOr` currently in stories. This seems to be the reason why the items aren't being found properly.
![image](https://user-images.githubusercontent.com/53564281/73168863-af90ff00-40f2-11ea-90f6-4f6adb1471cc.png)
