### ISSUE TITLE
[Investigation] Understand how can we configure the SMP to play pre-roll ads

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5390]
This is an investigation task, we do not need a MAP page (necessarily)- can use the embed endpoint or cookbook. Whatever is easiest/fastest way to get the SMP onto a page and play around with it.

https://paper.dropbox.com/doc/Pre-roll-Ads-Example-Mapping--AtteSS2P8~sUB7d6mKFXdnviAg-yYdTagH52RYhm5FNB1fH3

Key questions we want to answer:

- [x] Speak to James Donohue to seek guidance. He has offered to help us based on experience integrating the plugin.
- [x] Ask Jane if she has the JSON SMP settings from the PAL MAP pages.
- [x] How do we load the GNL plugin?
- [x] How to we use the plugin to control playing of ads?
- [x] Is there a new version of the 'GNL plugin'? (There is a call on Thursday pm) & can we use it? 
- [x] Is it true that the plugin/s are _big and heavy_?

**Comment by jroebu14** [comment]
### Speak to James Donohue to seek guidance. He has offered to help us based on experience integrating the plugin.
James D provided us with an [example of the plugin integration](https://github.com/bbc/morph-modules/blob/117e117c7e604e9904696c7cf83ddaa734c85248/news-front-page-js-bundle/src/modules/smp.js#L24-L35) for the News front page media player.

### Ask Jane if she has the JSON SMP settings from the PAL MAP pages.
In the above example from James we can see the SMP settings needed.

### How do we load the GNL plugin?
[I asked in the WebCore Help Slack channel](https://bbc-dpg.slack.com/archives/CCNUHV5TM/p1580911963237600) where to get this plugin. The conversation is below.
The TLDR is that we shouldn't use the traditional plugin because it's on Forge and to use it we need to load a bunch of other stuff we don't need. There is a [new plugin for just preroll ads](https://bbc-gnl-sandpit-ngas.s3.eu-west-2.amazonaws.com/preroll.js) that is not quite ready yet. There is a [proof-of-concept PR in WebCore](https://github.com/bbc/web/pull/2084) that demonstrates a preroll ad working.

> **Jonathan**
> Hey, I'm currently tasked with rendering GNL preroll ads in SMP in Simorgh for World Service pages. I think I know how to go about it using the adverts plugin but I'm not sure how to actually get the plugin as any example I've seen gets it from the bbcdotcom global variable on the window which I guess comes from Orbit(?) and we don't have this in Simorgh.
I heard Web Core are solving this problem too. I was wondering if there's anyone I could speak to who could potentially point me in the right direction. Thanks!

> **Andrew**
> have you seen this smp page? i'm pretty sure the plugin you want is the dfpads one, which is hosted by the smp team and should be able to get with just name:dfpAds.js https://confluence.dev.bbc.co.uk/display/mp/Media+Playout+hosted+plugins

> **Dom:webcore:**
> Welcome back Jonathan Roebuck. I did see this PR come through: https://github.com/bbc/web/pull/2084

> **Jim**
> yes the ads plugin is dfpAds.js but that is not enough to get ads, the stuff we don't know about is also needed

> **Jim**
> I can provide sample data, but the "problem" is the rules around when to show which come from that bbcdotcom object.

>**Jonathan**
> so this method?
`window.bbcdotcom.adverts.getPrerollAdTagWithAdRule()`

> **Jim**
> As I say no idea! #help-advertising has the people I'd ask in

> **Jonathan**
> I'll poke in there then. Thanks, Jim

> **Fatima**
> Hi Jonathan Roebuck, I work in the GNL team… And all the things mentioned above are not the solution we’d like to implement on Simorgh…

> **Fatima**
> We’ve been working on a POC for webcore that we do want to extend to Simorgh

> **Fatima**
> Once we have a MVP

> **Jonathan**
> Hi Fatima. Thanks for chipping in. Do you know when this will be ready? Is there anything I can look at or try as a POC in Simorgh?

> **Fatima**
> https://github.com/bbc/web/pull/2084

> **Jonathan**
> Thanks. I was looking at that earlier. I had a question about this line https://github.com/bbc/web/pull/2084/files#diff-cad5cc32d03a3523f31e75769676c72bR187 (edited) 

> **Jonathan**
> where does DotcomPreroll come from?

> **Fatima**
> https://github.com/bbc/web/pull/2084/files#diff-cad5cc32d03a3523f31e75769676c72bR169

> **Jonathan**
> also, why do you not want to use the traditional preroll ads setup? what's the benefits of this method?

> **Fatima**
> because it’s old code that lives on Forge and it’s a big module that doesn’t do just preroll 

### How to we use the plugin to control playing of ads?
I tried creating a [proof-of-concept PR for the preroll ads in News AV player embed](https://github.com/bbc/morph-modules/pull/34308) in Morph however there is currently a problem with loading the SMP locally so I can't test my changes locally

### Is there a new version of the 'GNL plugin'? (There is a call on Thursday pm) & can we use it?
[Yes there is](https://bbc-gnl-sandpit-ngas.s3.eu-west-2.amazonaws.com/preroll.js) as mentioned above. After the call it would appear that this plugin is not ready to be used until the end of March. [Here are the notes from the call.](https://confluence.dev.bbc.co.uk/pages/viewpage.action?pageId=205344629)

### Is it true that the plugin/s are big and heavy?
This is true for the old/current plugin that is hosted on Forge. The new plugin looks very light in comparison.

**Comment by aeroplanejane** [comment]
Some Notes:
Do we have everything we need to pass to the player plugin - where is the data coming from and can we derive it from the ares response? - I can look in to this and have raised a Jira to cover this. 

We need to ensure that we can pass the correct cookie settings to the plugin and that we ensure we are tracking the correct cookies in our header. - I can start to look at this but might need some help  

Previously, ATI tracking for ads would have been handled by Orbit. We need to ensure we continue to track on page analytics - we need to speak to GNL about their on page analytics requirements and what they're currently tracking across the services - this is something that other Simorgh teams may have to worry about, so can speak to them on this 

It seems like Jim Ley doesn't have the requirements for the new plugin when it comes to SMP tracking, so we may have to wait from rich media ATI tracking 

If we think the POV isn't going to be ready until March is there anything we need to do on our end to ensure the solution integrates with Simorgh, or do we expect the solution to be the same? 

Can we work with Fatima to get this implemented on our pages rather than waiting for the trial in March? 

I've added some of this to the example mapping doc here: https://paper.dropbox.com/doc/Pre-roll-Ads-Example-Mapping--At4_h3ieBwwoNQcz1LQcjCdoAQ-yYdTagH52RYhm5FNB1fH3

**Comment by aeroplanejane** [comment]
This looks like it's done now!
