### ISSUE TITLE
Ensure TC2 Asset Poster Image is visible when links are shared 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5591]
**Is your feature request related to a problem? Please describe.**
We want to ensure that the poster image is added to the og:image 
Currently when you share an pal TC2 asset link on social you get a preview of a the poster image
We want to ensure the same behaviour applies to TC2 links on Simorgh. 

**Describe the solution you'd like**
Set the og:image as the poster image
if a poster image isn't available it should default to the service logo. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]
Can be tested using the structured data testing tool: https://developers.facebook.com/tools/debug/

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
I am getting a warning saying invalid image content type when I check this with the structured data testing facebook tool.

'Invalid Image Content Type
Provided og:image URL, http://ichef.bbci.co.uk/news/1024/branded_afrique/worldservice/live/assets/images/2015/07/14/150714114834_hissene_habre_bbc_144x81__nocredit.jpg could not be processed as an image because it has an invalid content type.'

I used the URL bbc.com/afrique/institutionelles/2015/07/150714_hissene_habre_explainer

**Comment by paruchurisilpa** [comment]
This is not Ready for test yet, so will pick up when it is Ready..

**Comment by karinathomasbbc** [comment]
This should now be ready for test. You can get URLs via the Cypress config (search for TC2 MAP in Test / Live environments) - https://github.com/bbc/simorgh/blob/latest/cypress/support/config/settings.js

**Comment by paruchurisilpa** [comment]
Example URL's:

https://www.test.bbc.com/afrique/bbc_afrique_radio/programmes/p030s6g6?renderer_env=live
https://www.test.bbc.com/afrique/bbc_afrique_radio/w172xlmx3r0xtz8?renderer_env=live

**Comment by aeroplanejane** [comment]
Hey @paruchurisilpa the urls above are for radio pages - so don't apply here, we want to test TC2 MAP pages 
Here are some sample URLs for you to test: 
https://www.test.bbc.com/ukrainian/multimedia/2016/05/160509_mariana_trench_video_ag?renderer_env=live
https://www.test.bbc.com/russian/multimedia/2013/12/131202_v_apartheid?renderer_env=live

Let me know if you need any more.

**Comment by aeroplanejane** [comment]
This doesn't appear to be fixed after merge. 
Tested using the fb debug tool and sharing on slack. Still defaults to the site image. 
https://www.test.bbc.com/azeri/multimedia/2015/08/150804_azeri_test
https://www.test.bbc.com//arabic/worldnews/2015/11/151120_t_arabic_av

**Comment by paruchurisilpa** [comment]
Checked using the above links provided by Jane and I still see the default image..Attached is the screenshot.Moving this back into Progress..
<img width="503" alt="Screenshot 2020-08-25 at 12 26 37" src="https://user-images.githubusercontent.com/1379277/91168869-41cfa480-e6ce-11ea-86fb-83ef1e6d180e.png">

**Comment by RichardPK** [comment]
Interestingly with that Azeri url (https://www.test.bbc.com/azeri/multimedia/2015/08/150804_azeri_test) - it doesn't have any data in the path being passed to the `imageLocator` prop in the `CpsMetadata` component (`'promo' > 'indexImage' > 'path'`) so it will fall back to the default. It does have data within `'promo' > 'media' > 'image'` however - so maybe we need to try multiple paths before defaulting to the masterbrand?

Secondly, a piece of content which DOES have data in the `'promo' > 'indexImage' > 'path'`https://www.bbc.com/afrique/institutionelles/2015/07/150714_hissene_habre_explainer (add .json to the end of the URL to see the data we're working with) also renders the fallback default, presumably because the string in it isn't a valid URL (`/amz/worldservice/live/assets/images/2015/07/14/150714114834_hissene_habre_bbc_144x81__nocredit.jpg`).

@paruchurisilpa has already moved this back into in-progress, but with this comment... I mark it... reopened!

**Comment by karinathomasbbc** [comment]
Ah, I need to explain what I have implemented here (it was too complicated / time-consuming to make the poster image work for TC2s, so I decided to always default to the brand image - further information on the PR https://github.com/bbc/simorgh/pull/7498). 

Let's have a quick session to discuss and see if that's acceptable @aeroplanejane and @paruchurisilpa

**Comment by aeroplanejane** [comment]
@karinathomas that's completely fine, no discussion needed (at least with me!). This was always a fairly low priority issue anyway (no one is really going to be sharing a link from pre-2016 much...). It just wasn't clear from the notes what the expected behaviour was, so maybe just update the testing notes for @paruchurisilpa so it can be tested and closed. Thanks!

**Comment by chris-hinds** [comment]
Ohh hello......... I have just merged some work that ensure PGL, STY's & MAP's now use the index image for the Schema.org structured data if available.

**Comment by karinathomasbbc** [comment]
@chris-hinds does this mean we are no longer sharing the index image, or is it only if the index image is not available?

**Comment by chris-hinds** [comment]
@karinathomas if the indexImage is available we use that, if not we fallback to the brand logo image which was previously being used

**Comment by paruchurisilpa** [comment]
Shared both TC2 and CPS Map's and you get default image for TC2 assets and correct image for CPS assets if there is an image in CPS.

LGTM..
