### ISSUE TITLE
Investigation: Social Media embed fallback

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#5611]
**Is your feature request related to a problem?**
In order to embed Social Media content in our STYs, we need to display HTML using the oEmbed response from providers (like YouTube, Instagram or Twitter). It is currently unknown what currently happens when an embedded item is unavailable.

**Describe the solution you'd like**
On the PAL (see 'useful links' below), investigate:

1 - What happens when a social media item is unavailable.
  - Do we render a fallback?

2 - If we render a fallback, what happens when there is an error rendering it?
  - Do we show an error message to the reader?

3 - What happens if a social media item is embedded from an unsupported provider. E.G. Facebook
  - Do we render a link to the item instead?

**Useful links:**
- [Article containing Twitter and YouTube embeds](https://www.bbc.com/mundo/noticias-america-latina-51518716)
- [Article containing Instagram embed](https://www.bbc.com/mundo/noticias-51475372)

**Describe alternatives you've considered**
n/a.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rhenshaw56** [comment]
**What happens when a social media item is unavailable ?**

The embed content becomes unavailable when the content gets deleted and in special cases (eg, Facebook) when the owner changes the view permissions to something other than public (eg, close friends), and when that happens oembed is unable to fetch the original content. 

- _Do we render a fallback ?_
    This depends on what implementation approach we intend to use but part of our requirement is that we should have the ability to cache the original embed response which ensures we always have the markup cached in the case it gets deleted or updated so in that case we always have a fallback cached unless the story author decides the dissociate the embed content from the story. Else, In the case that we don't have the ability to cache embed responses it would solely come down to product recommending if we would prefer to have a form of custom fallback.


**If we render a fallback, what happens when there is an error rendering it?**

The providers don't explicitly provide a method for handling fallbacks. Although it is recommended to specify a fallback markup using oembed.

**What happens if a social media item is embedded from an unsupported provider. E.G. Facebook ?**

I haven't actually seen a story page example with a Facebook embed but this is very possible as an [example](https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fethindiaco%2Fposts%2F743464362652316&width=500) is given in the oembed docs and it's also possible to have embedded contents of Facebook posts, videos, activities and permalinks. As previously stated, the only caveat with rendering a Facebook embed is that the content should be publicly accessible. I think it would be worth confirming from product if part of our requirement also includes having Facebook embeds.

**Comment by mykeels** [comment]
| Social Media | oEmbed Link  |      oEmbed for Deleted Posts |
|----------|-------------|:-------------:|
| Facebook Post | https://www.facebook.com/plugins/post/oembed.json/?url= |  becomes unavailable  |
| Facebook Video | https://www.facebook.com/plugins/video/oembed.json/?url= |  [untested]  |
| Twitter | https://publish.twitter.com/oembed?url= |   returns 404 unless when cached by the browser |
| Instagram | https://api.instagram.com/oembed/?url= | returns 404 with text, `No Media Match` (no noticeable caching) |

**Comment by simonsinclair** [comment]
Thanks, Rowland. As we discussed in the call earlier, it would be good to build on this and confirm some of the scenarios by posting a Tweet and creating a CPS STY that includes it. Then record the process (screenshot, etc) at every stage. @lizcameron has kindly agreed to helping us with this.

Some of these stages _could_ be:

1. Post a Tweet we can control.
2. Create an STY that includes the Tweet.
3. Publish the STY and record result.
4. Delete the Tweet.
5. (Browser) Refresh STY and record the result.
6. Edit the STY, but don't remove the Tweet and then re-publish.
7. (Browser) Refresh and record result.

**Comment by simonsinclair** [comment]
Details regarding Social Embed behaviour on PAL have been captured in a Dropbox Paper document by @jimjohnsonrollings.
