### ISSUE TITLE
Fix console error for Script Link tests

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#5815]
**Describe the bug**
There is a following console error for Script Link tests:
<img width="799" alt="Screenshot 2020-03-09 at 11 55 00" src="https://user-images.githubusercontent.com/17802955/76210915-fba88680-61fc-11ea-9071-a97bda92084a.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Simorgh `latest` branch
2. Run `npm run test:unit`
3. See console error

**Expected behaviour**
No console error when running tests.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by j-pendlebury** [comment]
I started to look into this, but didn't get very far.

What I've found is:
- A lot of sources say that this failure is to do with `window.location`, more [here](https://github.com/jsdom/jsdom/issues/2112), however I could not figure out how that could affect our tests.
- There are two tests that are causing this issue and both use `fireEvent.click` which is most likely the culprit here. These tests live [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Header/ScriptLink/index.test.jsx#L217-L252)

**Comment by joshcoventry** [comment]
Cannot reproduce
