### ISSUE TITLE
Investigate adding AMP Ads for Canonical pages

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#5819]
**Is your feature request related to a problem? Please describe.**
Following this SPIKE PR: https://github.com/bbc/simorgh/pull/5799, SPIKE issue: https://github.com/bbc/simorgh/issues/5620

We were able to display AMP ads on our canonical front page. However, using the amp components in our canonical pages caused the `lazyloading` of images to not work as expected. 

The overall plan with Ads is to use `amp-ad` for both our AMP and Canonical pages.

**Describe the solution you'd like**
- Investigate how we could fix lazyloading for our canonical pages when amp-script/amp-ad is imported into the page. 
-  Make sure we respect cookie values that have been set for personalised ads on canonical

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

I recommend, when developing/testing to check the components works in an "in-private/incognito" browser, to ensure your plugins do not block the ad.

useful resources:

https://amp.dev/documentation/components/amp-ad/?format=websites
https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-ad.example.1.html%3Fformat%3Dwebsites&format=websites&_gl=1*1te7d9j*_ga*ODE0MzYzNzc2LjE1ODM1MDAzOTM.&mode=Responsive

**Comment by mmcculloch** [comment]
```js
const AMP_JS = <script async src="https://cdn.ampproject.org/v0.js" />;
```
At the moment importing the AMP JS file into our non-amp pages will display the ad, but seems to break `react-lazyload`. Even without displaying an ad, the act of importing this file stops the lazyloads triggering.

Importing the `amp-ad` js file
```js
export const AMP_ADS_JS = (
  <script
    async
    custom-element="amp-ad"
    src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"
  />
);
```
doesn't allow us to display the `<amp-ad` tag, though it also doesn't break the lazyload.

**Comment by hotinglok** [comment]
As a summary of the work @mmcculloch, here is what we have tried and found with trying to put the amp ads on a canonical page:

**Main Conclusion: Amp ads need something in the amp runtime in order to run despite the docs saying amphtml ads work fine out the box**
- The basis for this investigation is that amp ads supposedly run fine on any page, [not just amp pages](https://amp.dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads/?referrer=ampproject.org):
> Most of all, these ads can be delivered anywhere on the web, _not just on AMP pages_.
- The work done in https://github.com/bbc/simorgh/pull/5799 followed a similar structure to how the ads were being used on amp pages in https://github.com/bbc/simorgh/pull/5835 and was what @mmcculloch worked off of as a base since this PR managed to successfully put an amp ad onto a canonical page, but various problems arose with this approach.

**Issues with the approach done in the SPIKE PR**
- The `{AMP_JS}`import breaks various things in react it seems. The most immediately obvious one was the way in which it breaks how we handle our lazy-loading as stated above, however this may be just the tip of the iceberg with regards to what else it might be breaking.
  - `{AMP_JS}` allows the amp runtime to be run on the page which in some ways makes a 'pseudo' amp page. What I mean by this is that as soon as the `{AMP_JS}` script is present, the page becomes 'Powered by AMP' showing the amp runtime present, however it still lacks a lot of the [requirements to become a full on amp page](https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/?format=websites), which isn't what we want anyways.
  - The amp ad in the previous PR loads with various specifications we need but only works when the line below is removed, which may be another thing that supports the notion that amp stuff is breaking more than we can see on a surface level.
https://github.com/bbc/simorgh/blob/08cd828a4f097883dbb6b1f88f7213788abc644f/src/app/containers/Ad/index.jsx#L28
  - When we tried with the same code for an amazon ad in the [example on the documentation page](https://amp.dev/documentation/components/amp-ad/?format=websites), The same issues occurred with lazy-loading being broken etc. This suggests that the placeholder ads we used in the SPIKE may not have been an issue, the underlying issue still being the `{AMP_JS}` script we're using.
- The `AMP_ADS_JS` script supposedly needs to be present in order for the amp ads to work as it's stated as a [required script in the docs](https://amp.dev/documentation/components/amp-ad/?format=websites), yet the ad still loads correctly when we remove this. The [repository](https://github.com/ampproject/amphtml/tree/master/extensions/amp-ad) for this script is also quite hard to understand. This suggests that it may be to do with how we're using the ad, but this shouldn't be the case if amp ads are meant to work on any page, as well as the fact that this still doesn't work even with an ad in their example.
  - Even stripping the files down to just containers with the most basic of tags to make an amp ad, it still requires the amp runtime script to be shown at all.

**Other information**
- One thing that does work is dealing with lazy-loading alongside what we currently use for it on actual amp pages. You can set the attribute `loading="lazy"` in the amp ad and it will correctly function alongside the rest of our lazy-loaded components.

**Actions moving forward**
- @tochwill has made a post on the amp slack and we will have further discussions with more people who have more experience with previous work done with AMP.

**Comment by mmcculloch** [comment]
After discussion we decided to try solutions that would avoid the need to import the main amp js into the application, since this seems to cause event issues (and possibly more unknown issues). There are 2 possible ways to do this:

- Use Shadow DOM
- Use an iframe 

The Shadow DOM solution should be the easiest to try and we can use a library like [ReactShadow](https://github.com/Wildhoney/ReactShadow). Overall browser compatibility could be an issue however.

An iframe might work in all browsers but we'll have to create an ad page which we can server through the iframe. (edit from Tom - or potentially link to the page that the iFrame that the amp-ads component links to)

**Comment by mmcculloch** [comment]
PR for this investigation here https://github.com/bbc/simorgh/pull/6078
And a writeup of my findings https://paper.dropbox.com/doc/Amp-ADs-on-Canonical-pages--AxV6I5jYKlOVqQu4MGCTGyXqAg-GcUqUlqWizZtlIPPVcw9e
