### ISSUE TITLE
Remove container stories 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#589]
**Is your feature request related to a problem? Please describe.**
We currently have container stories which are duplicates of the component stories that the container renders. 

**Describe the solution you'd like**
We should evaluate each container `.stories.jsx` and if any of the stories duplicate a component story they should be removed. 

**Describe alternatives you've considered**
Keep container stories as realistic data as compared to component stories which have purposefully placeholder data. Opposing this we could have fixture data for each component which could differ between realistic and placeholder.

**Comment by DemonusPC** [comment]
Ideally the container is separate from the component that renders the data. In other words there really should be stories for components themselves since all the styling code should happen in the component and not the container. Although the downside of this is that when you are implementing the container you might want some visual feedback to what you are developing. When developing this we should be careful to always mention that a certain story is a component or a container not to confuse future devs.

**Comment by pjlee11** [comment]
Further thought on this has lead me to think of a way to seperate what container stories are needed and which are not. Given the following examples I think we can justify when a container story is required.

**Example 1**
The Figure container has a direct 1-to-1 mapping with the Figure component. Given this we can use the Figure container to generate the various different scenarios that can be produced by passing it data and allowing the container to handle the optional rendering logic. In this case using the container to generate the Story data means that the container and component stories would be an identical match. 

**Example 2**
The MainContent container has the ability to render a variety of components meaning it does not have a 1-to-1 mapping to a component and therefore would require it's own stories. 

**Conclusion**
With this logic I would suggest the following container stories need to be removed:
- Footer/index.stories.jsx
- Image/index.stories.jsx

And going forward we don't had stories for containers if they have a 1-to-1 mapping

**Comment by jamesbhobbs** [comment]
@pjlee11 there may be cases when your points are valid, but as discussed there are no current valuable container stories.
