### ISSUE TITLE
Investigate improving the presentation of Most Read

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#5948]
**Is your feature request related to a problem? Please describe.**
Following a review with the UX team, we need to investigate how to improve the presentation of the Most Read onward journey. The font is too large at the moment.

**Describe the solution you'd like**
An investigation that looks into:
- Can the presentation of Most Read be altered on a STY page without impacting the front page?
  - Pass in styling or theming - maybe a React context theme
  - Check whether new props need to be added or props can be reused

- Is it easier or beneficial in another way to create a Most Read component just for STY pages? I.e. don't try and continue using the same component from the front page.

The investigation should have the following outcomes:
- A proposal for altering the presentation to better match the design from UX (see Zeplin - link in Jira NEWSART-936). Note: This issue is just the investigation to decide how to improve the presentation - the proposal should be discussed with the team before continuing.
- Issue(s) to implement the changes created and ready to be refined

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Zeplin designs exist for the Most Read component on STY pages - ask @lizcameron for a link or the link can also be found in Jira: NEWSART-936.
The PR that was reviewed: https://github.com/bbc/simorgh/pull/5739/

**Comment by 12** [comment]
Have been working with @Simon2828 on this today. We both explored slightly different options.

I've created a POC (bbc/psammead#3304) that resolves the issue with font sizing by passing a `small` prop to the Most Read component, which is great... but there are future concerns.

Whilst this original issue suggests exploring a solution for the font sizing, it does also mention observing the other styling differences, of which there are quite a few:
1. Border between most read items
2. Vertical and horizontal alignment of the numeral
3. The smaller size may require some grid adjustments (as the numerals are smaller, the margin between the numeral and title is greater)

Whilst these can be addressed through prop hacks, it does a feel a bit _too_ hacky to say that this would be the best solution. 

Personally, I think we should explore creating a separate component, or refactoring the existing one further to return a `full-width` and a `sidebar` component. The latter could be nicer, as the component will be identical in terms of functionality so would therefore reduce duplication.

**Comment by Simon2828** [comment]
I passed the `pageType` prop from simorgh to alter the styles depending on its value. Considered using styled-components’ [theming support](https://styled-components.com/docs/advanced) but don’t think this is the correct use case as we only want one component to be rendered, so instead have just passed functions to the styled component's template literal to adapt it based on its props:

![Screenshot 2020-03-26 at 08 48 34](https://user-images.githubusercontent.com/13512114/77627510-ee9acf80-6f3e-11ea-98ce-9d8d1394fa16.png)

After discussing with Rhys @12, he suggested it was better to decouple the logic from simorgh, so rather than passing down ‘STY’ use a boolean as in his POC above which I agree is a better solution.

As Rhys says above, there are quite a few changes to be made to the styles. Whether we should instead build a new component, I think depends on how faithful we need to be to the styles provided by UX [zeplin](https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5e6b9ddc00514713f87412fc)

**Comment by lizcameron** [comment]
Thanks @Simon2828 and @12 for the great investigation and sharing what you've found! After discussing this morning with everyone, UX are going to review this locally and summarise the changes that are still needed from a UX point of view. We'll then prioritise those and decide whether we need to build a new component or not.

**Comment by Simon2828** [comment]
The decision taken is to add a new prop to change the font size: https://github.com/bbc/psammead/issues/3320
