### ISSUE TITLE
AMP error

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6007]
**Problem**
It looks like there is an issue specifically with media asset pages when you examine amp validation in the search console. 

Our canonical pages are not linking the relevant amp page due to this error: https://search.google.com/u/1/search-console/inspect/amp?resource_id=https://www.bbc.com/ukrainian/&id=j0sKpUWpn4eb2mY7vf9VSQ&alt_id=mdIFINGI-EHkkwAWGPG6JA

Looks like there’s a missing h from the `https://` in `<a href="ttps://www.bbc.com/ukrainian/in-depth-46892639" class="InlineLink-hkwpaz-0 idscKS">`
![image (3)](https://user-images.githubusercontent.com/22519682/77768976-25eea680-703b-11ea-89ed-c175fd10e05a.png)

**This affects media asset pages specifically.** 

**Impact:** May impact how our pages are ranked in search as these pages are not ticking all the boxes in terms of performance and validation

**Comment by karinathomasbbc** [comment]
https://www.bbc.com/ukrainian/media-47718707
https://www.bbc.com/ukrainian/media-47733086
https://www.bbc.com/ukrainian/media-47707060

These assets contains a paragraph which has an invalid link to another BBC page (https://www.bbc.com/ukrainian/in-depth-46892639) - I think it can be fixed by updating the asset in CPS. This problem is not specific to AMP, but validation will pass once URL fixed.
