### ISSUE TITLE
Ensure all cypress tests are running - for full regression check

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6206]
**Is your feature request related to a problem? Please describe.**
We currently have some cypress tests that are disabled, mainly due to giving false negatives (e.g. for media playback on Media Asset Pages).

However, we are changing to a new major version of our API and we should temporarily enable all of these disabled tests. We note that there will be a likelihood of increasing false negatives, but it'll give better page coverage across all 41 services. 

**Describe the solution you'd like**
Have a PR that enables the tests that are disabled.
Do a full run of this on the branch, locally, to check tests are working fine.
Merge it in, prior to our API migration.
During the time when it is merged in, note down any false negatives in a new Simorgh issue.
After the API migration, either disable those tests that consistently give false negatives, or find another type of test that can cover those scenarios (perhaps integration tests would work better for some).

**Describe alternatives you've considered**
N/A

**Testing notes**
The full test suite should be run locally, prior to merging (not just the smoke test suite that's run on the CI for the PR).

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by joshcoventry** [comment]
@LilyL0u Is this actively being worked on?

**Comment by LilyL0u** [comment]
> @LilyL0u Is this actively being worked on?

Was this related to when we changed to Ares V2? When we did that I enabled a lot of tests across services and page types to regression test the change. I have now disabled many because the tests often fail when the test run is too long (sometimes the tests themselves flaking, sometimes other errors like SIGSEGV).

OR is this about another API change I don't know about? If so, I can work on it.
