### ISSUE TITLE
Consolidate Most Read and Radio Schedules approaches

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6219]
**Is your feature request related to a problem? Please describe.**
We have updated the Most Read and Radio Schedules containers in https://github.com/bbc/simorgh/pull/6142 and https://github.com/bbc/simorgh/pull/6175. There were a few points raised to look into after this work was done:

- ~Change the service to one that has an actual variant in src/app/containers/App/App.test.jsx~.

- Look into extra logging if status codes are not what we expect (200) in src/app/containers/RadioSchedule/Canonical/index.jsx, ~and update Most Read client data fetching to log with the same format.~

- ~Check all occurrences of getInitialData in tests to ensure an object is passed. Tests seem to not fail with the old string format, as fetch-mock is still returning the correct data.~

- ~We can add a new constant and replace the usage of DATA_FETCH_ERROR for supplementary data fetches, to better distinguish them in logs.~

- ~Consider replacing tests using `wait` with an approach that uses `act` in src/app/containers/RadioSchedule/Canonical/index.test.jsx.~

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
> and update Most Read client data fetching to log with the same format

I have moved this point above to this separate issue: https://github.com/bbc/simorgh/issues/6451

> Change the service to one that has an actual variant in src/app/containers/App/App.test.jsx.

This has been done a part of this commit: https://github.com/bbc/simorgh/commit/a9ac49929aff3865fcf41799cf2c6e7659780406


> Consider replacing tests using wait with an approach that uses act in 
src/app/containers/RadioSchedule/Canonical/index.test.jsx.

Another team has updated this from `wait()` to `waitFor()` as wait is being deprecated. I have created another issue for updating `waitFor()` test structure to `act()`: https://github.com/bbc/simorgh/issues/6457

> Check all occurrences of getInitialData in tests to ensure an object is passed. Tests seem to not fail with the old string format, as fetch-mock is still returning the correct data.

I've split this out into a tech-debt issue: https://github.com/bbc/simorgh/issues/6454


> We can add a new constant and replace the usage of DATA_FETCH_ERROR for supplementary data fetches, to better distinguish them in logs.

We are handling the Radio Schedule server side render error response here: https://github.com/bbc/simorgh/blob/latest/src/app/routes/utils/withRadioSchedule/index.js#L26-L29 with the `RADIO_SCHEDULE_FETCH_ERROR` const so that it is clear in our logs if radio schedules failed to fetch.

> Look into extra logging if status codes are not what we expect (200) in src/app/containers/RadioSchedule/Canonical/index.jsx

I have created a separate issue for this point here: https://github.com/bbc/simorgh/issues/6459

**Comment by thekp** [comment]
I am gone through this issue and split out the work into smaller issues mentioned in the comment above.
