### ISSUE TITLE
On Demand Radio Page - e2e User Journey

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6245]
We would like to be able to test some form of user journey, navigating from the home page to the on demand radio page, and then checking if the media player is rendered, and that a play button is visible

Similar to the tests we have for MAP pages - check that the player embed URL is correct & returns a 200 status code.

This will need to be a special feature, as it does not follow the same pattern as existing Cypress tests.
See https://github.com/bbc/simorgh/pull/6051 as an example

Considerations:
- [ ] Test data - episodes expire after 30 days
- [ ] If navigating from front page, we may need to update local fixture data, and also Front page indexes on test - to mitigate this, we might just look up the schedule endpoint instead, and get the most recent on demand episode from there. We would need to use the Cypress config (or some other form of config to determine if a service has on demand radio, and only then would we run these tests for that service
- [ ] Can test viewport to see if hero image appears when it should, and does not appear when it shouldn't. (cy.viewport)

**Comment by LilyL0u** [comment]
Ideas and questions:
- Make sure we always go to an episode that has not expired by clicking on one from the radio schedule on the front page. (will the front page schedule always feature an on demand episode if that service has on demand radio?)

- Could local fixture data be automatically updated? The test checks if the episode has expired, if it has, is it possible to take a snapshot of live data (like snapshots in Jonathan's integration tests) and update the fixture data that the local test reads from? (I don't know enough about the snapshot method to know if this is possible). Alternatively, it could update the fixture data via snapshot every time the tests runs if checking the expiry date is awkward, but this might take longer.
Because the URL of the page of the fixture data would change when it is updated, we would not be able to put a fixed on demand radio URL in the test config. Could the fixture data file instead have a name that does not change as it is updated, but the content changes as it is overwritten with the updated data from live, and that same file path is always accessed and contains the changed URL within it? This would make the config different from the other tests: the front page would be the URL accessed first. What would the URL on localhost look like in this case? It would be using a fixture data file with a name that is not the URL of the page on live. Does this matter? I suggest accessing a file with an unchanged name because then visiting a different page would not need a URL string change anywhere in the code. 

- I guess we would need some kind of wait happening while the fixture data is updated, so that the URL is only accessed after the update is finished. (How long could this take? I expect fast)

- A good user journey to have eventually would be to also click on the schedule or recent episodes in the other page components on the On Demand Radio page. This would also cause issues with needing changing fixture data on local, but would be good on test and live. If the updating fixture data with what is on live is easy to achieve, we could also do it with this, but otherwise we could only run these tests on test and live?

- Do we also want to go to a page that DOES have an expired episode to check the error state is shown correctly to the user? Or shall this be left to manual testing like No JS errors?

**Comment by LilyL0u** [comment]
Moving this back into the backlog as we are not implementing it yet. Currently some issue with new epiosode 404ing and needing to wait 7 seconds to refresh and get the page data.
