### ISSUE TITLE
Twitter for Social embeds on amp is blank on IE11

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#6366]
Result: https://github.com/bbc/simorgh/issues/6366#issuecomment-626763821

**Describe the bug**
A Twitter embed is not rendered in IE11 on AMP.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/kyrgyz/23292889.amp in IE11
2. Scroll to the bottom of the page where twitter is embeded.
3. It is blank, doesn't have any fallback.

**Expected behaviour**

**Screenshots**
<img width="1116" alt="Screenshot 2020-05-01 at 10 21 23" src="https://user-images.githubusercontent.com/1379277/80795963-e6fdc480-8b95-11ea-96c7-f582185d2e0e.png">

**Desktop (please complete the following information):**

- OS: All
- Browser: IE
- Version: 11

**Smartphone (please complete the following information):**

n/a

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
None.

**Comment by simonsinclair** [comment]
A test using the code shown in Minimal Example below reproduces the same bug with an error in the console: `Unable to get property 'widgets' of undefined or null reference`. The AMP component is trying to find `twttr.widgets` and it's undefined.

I decided to see if this was the case in Minimal Canonical Example and no error was shown. Delving into `widgets.js` code is almost impossible as it is minified and obfuscated, but there is a segment near the beginning that tests navigator.userAgent (`/(MSIE ([6789]|10|11))|Trident/.test(navigator.userAgent)`) which returns `true` in IE11 and `false` in all other browsers.

**I suspect Twitter does not support the embedding of Tweets in IE11, which is why they prevent their code from executing - this has a knock-on effect in AMP. Closing as we cannot fix this.**

## Minimal AMP Example
```html
<!doctype html>
<html amp lang="en">
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <title>Hello, AMPs</title>
    <link rel="canonical" href="https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
  </head>
  <body>
    <h1>AMP Twitter</h1>
    <amp-twitter
      width="375"
      height="472"
      layout="responsive"
      data-tweetid="885634330868850689"
    >
    </amp-twitter>
  </body>
</html>
```

## Minimal Canonical Example
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Twitter Test</title>
</head>
<body>
  <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sunsets don&#39;t get much better than this one over <a href="https://twitter.com/GrandTetonNPS?ref_src=twsrc%5Etfw">@GrandTetonNPS</a>. <a href="https://twitter.com/hashtag/nature?src=hash&amp;ref_src=twsrc%5Etfw">#nature</a> <a href="https://twitter.com/hashtag/sunset?src=hash&amp;ref_src=twsrc%5Etfw">#sunset</a> <a href="http://t.co/YuKy2rcjyU">pic.twitter.com/YuKy2rcjyU</a></p>&mdash; US Department of the Interior (@Interior) <a href="https://twitter.com/Interior/status/463440424141459456?ref_src=twsrc%5Etfw">May 5, 2014</a></blockquote>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</body>
</html>
```
