### ISSUE TITLE
Main Column Overlaps Secondary Column on Story Page

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6555]
**Describe the bug**
On one page, it has been found that the main column can overlap the secondary column:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/9645462/82296834-b2697580-99a9-11ea-8ea9-b81242d7e949.png">
https://www.test.bbc.com/gahuza/amakuru-23297941?renderer_env=test 

This has only been seen on Firefox so far.

**To Reproduce**
Steps to reproduce the behaviour:

Please note the below url sometimes 404s due to an ongoing issue with assets 404ing on test: https://github.com/bbc/simorgh-infrastructure/issues/1005 

1. Open Firefox
1. Go to https://www.test.bbc.com/gahuza/amakuru-23297941?renderer_env=test
Observe the overlapping behaviour

**Expected behaviour**
The main column should not overlap the secondary.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Firefox only
- Version 76.0.1

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
Bit of a speculation as to the cause:

This issue may potentially be caused by the following dependency failing to load:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/9645462/82297826-1e98a900-99ab-11ea-97b4-c4bc1cd1f0b7.png">
The `pym-manager` resizes an iframe hosting the an include at the bottom of the page:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/9645462/82297959-5273ce80-99ab-11ea-9016-a5610c344878.png">
It is not loading because of our CSP, this will be resolved when the following PR is merged: https://github.com/bbc/simorgh/pull/6427 
Once the `pym-manager` has been loaded correctly, the include may resize correctly preventing the overlap.

**Comment by mykeels** [comment]
Adding a `max-width: 100%` to the main div, fixes the issue on Firefox, and does not create problems on Chrome.

**Comment by sareh** [comment]
@andrewscfc @sadickisaac 

I believe this issue is that in containers used on CPS assets, you're still using `GridItemConstrainedLarge`, `GridItemConstrainedMedium`, `GridItemConstrainedLargeNoMargin`, with `NestedGridParentLarge` etc., but the page is using the new Grid defined in `@bbc/psammead-grid`. 

The way to fix this should be by replacing these old `GridItemConstrained*`s with `Grid`.

There is already an issue for this. https://github.com/bbc/simorgh/issues/3686

https://www.test.bbc.com/gahuza/amakuru-23297941?renderer_env=test

Edit: Looking at the page with dev tools, it seems more specific than I initially thought.
In the console, when I delete the `<div>s` that have includes, the overlapping is fixed. These divs have the class `GridItemConstrainedMedium` applied to them.

It'd be good to move away from `GridItemConstrainedMedium` to using `Grid` from `@bbc/psammead-grid`, rather than masking the issue with a quick fix relating to a `width: 100%;` or `max-width: 100%;` around the `<main>` block of the page.

**Comment by ghost** [comment]
@sareh sure. I was looking at it realising that we don't use the new `psammead-grid`, I have updated my PR to use the `psammead-grid`. Currently checking if its being rendered ok on I.E 11

**Comment by sadickisaac** [comment]
@sareh using `psammead-grid` on the STY pages also requires change in containers that are used on other pageTypes. Has any work been done on #3686. Could we fix the main column issue with this PR https://github.com/bbc/simorgh/pull/6566. And start working on doing the necessary changes to remove `GridItemConstrainedMedium`.
