### ISSUE TITLE
P2 A11y - Voice Over MacOS repeating bulleted list items on STY pages

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#6557]
**Describe the bug**
Following on from the full page STY a11y swarm, when navigating through a bulleted list on a STY page, some of the items are available twice when using Voiceover for MacOS on Safari e.g. some items are 2 key presses reading out the same content twice though with silighly different semantics, and the items that are 2 key presses are different depeding if you move through the content from the top or bottom of the component.

**To Reproduce**
Steps to reproduce the behaviour:

1. Activate VoiceOver for Mac
2. Visit https://www.test.bbc.com/gahuza/23302543
3. Navigate to the bulleted list with the screen reader navigation (Ctrl + alt/option + left/right arrow key)

**Expected behaviour**
Bulleted list items should only be read out once when navigating forwards and backwards.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
Check the behaviour with all other supported screen readers is ok.

**Comment by greenc05** [comment]
Lets start by removing the CSS, is the bug still present?

**Comment by Simon2828** [comment]
> Lets start by removing the CSS, is the bug still present?

Thanks @greenc05. The bug is no longer there when removing the CSS. 

VoiceOver does not say 'bullet' because of the way the `BulletedList` component bullet points are implemented using pseudo-elements  - is this better for accessibility? 

By deleting `list-style-type: none` and the pseudo-element the bug is fixed, but 'bullet' is read out by VoiceOver, which we do not want to happen I suppose?

**Comment by greenc05** [comment]
Correct @Simon2828 we don't want it to say bullet, and we need the CSS 'list style type none' inorder for this to not be announced.
