### ISSUE TITLE
Update e2e's for frontpage to be run on few services

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#6674]
**Is your feature request related to a problem? Please describe.**
Currently the e2e test for frontpage are run across almost all the services.Can we select a cross section of the services to cover the variants may be Mundo,Russian,Persian,Serbian,Afrique?

**Describe the solution you'd like**
Select a few services and enable the config such that tests are run only across those services.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
I'd suggest only using these three, since I think they have all of our major features between them:
Afrique - left-to-right, radio schedule, adverts
Arabic - right-to-left, radio schedule, adverts
Serbian - left-to-right, has two scripts

I think we shouldn't likely need to test in Cypress the existence of the Radio bulletin/TV bulletin/Podcast promo, since this should be tested at the unit test and integration test level.
