### ISSUE TITLE
Error in grid implementation

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#693]
**Describe the bug**
https://www.chromestatus.com/feature/6708326821789696 describes the issue

**To Reproduce**
It affects the Footer's Link component's css. Needs updating to new syntax

**Testing notes**
Regression suffices.

**Comment by BogdanDogaru** [comment]
Pending a question on affected browsers

**Comment by pjlee11** [comment]
The pen https://codepen.io/phil-lee/pen/MPVzRJ is a simplified version of the problem.

Chrome 69 render:
![image](https://user-images.githubusercontent.com/7791726/47165793-b4adae80-d2f2-11e8-96c9-523f3ed4ddb4.png)

Canary render: 
![image](https://user-images.githubusercontent.com/7791726/47165772-a790bf80-d2f2-11e8-9892-05c02a68acd1.png)

The canary render is failing because we are defining the rows using percentages and it appears that in the with the coming changes margin's are no longer exclusive of a row/template. I'm unsure whether this should be considered a bug and plan to raise a chromium issue to be certain. We were using percentage's to define the row heights so they could vary from row to row. 

Current suggested solution to not block work, hardcode the first row to the correct height then define the following rows using `1fr`. 
EG: replace `grid-template-rows: repeat(3, 33.333%)` with `grid-template-rows: 8rem 1fr 1fr` where `8rem = 64px`

**Comment by pjlee11** [comment]
[Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=896715&can=2&q=CSS%20component%3ABlink%3ELayout%3EGrid%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by pjlee11** [comment]
RE: affected browser, currently only seen on Chrome Canary and Opera Developer

**Comment by pjlee11** [comment]
Following a response in the Chromium ticket I've updated the pen to show a nicer solution - https://codepen.io/anon/pen/bmxmYp. This basically means we can keep our old implementation and change percentage 33.33% to auto and it should fix the problem.
