### ISSUE TITLE
Remove 'hasAds' check in Service config

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#7015]
**Is your feature request related to a problem? Please describe.**

In Simorgh, for adverts, we are fetching configuration for each service. 
https://config.test.api.bbci.co.uk/?application=simorgh&service=mundo&__amp_source_origin=https://www.test.bbc.com 
In the response we have a value whether to show ads:
```
{
  "toggles": {
    "ads": {
      "enabled": true,
      "value": ""
    },
    "preroll": {
      "enabled": true,
      "value": ""
    },
    "mostRead": {
      "enabled": true,
      "value": ""
    }
  }
}
```

We should remove the `hasAds` flag in the Service config files. `src/app/lib/config/services/afrique.js`:
```
  ads: {
      hasAds: true,
  }
```
This is because the logic is duplicated across iSite and in Simorgh. 

**Describe the solution you'd like**
We should remove the `hasAds` field from the code and ensure we're just checking the `ads` toggle from the config endpoint. 

Additionally, we should move the translations into the translations block:
```
translations: {
  ads: {
    advertisementLabel: 'Publicités',
    infoLink: 'https://www.bbc.com/afrique/institutionelles/2015/08/000000_advertising_faq',
  },
},
```

**Describe alternatives you've considered**
Keeping the extra check will lead to unnecessary complexity, when we already have multiple levels of toggles/flagpoles. 

**Testing notes**
Ensure to test the happy path and also the fallback path.

Dev insight: Relevant unit tests/integration tests should be updated. We should ensure that we have ads for the 7 services (afrique, arabic, hindi, mundo, pidgin, portuguese, russian, zhongwen) and that we don't have ads for all other services. 

- [x] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by tochwill** [comment]
This gets more complicated when we consider AMP:

- We can't use the values from the config service that we will request on the server for canonical pages to decide whether to show an ad on the AMP page.
- This is because AMP pages can be cached in the AMP cache for minutes, hours, days etc... depending on the levels of traffic to the page. This is because of the AMP cache's stale-while-revalidate caching model.
- If we remove `hasAds` from config, we will then have to make a client side call from every AMP page whose pagetype supports ads. This will be one request per page view across all 41 services.
- The requirement to be able to read values from the config service is in order to be able to quickly turn ads off globally/for a service. The propagation time for `hasAds`to be adhered to across all AMP pages when a new service wants to display ads is less of a concern.
- For these reasons, do we need to continue checking `hasAds`, for the sake of AMP pages?
- Alternatively, do we check the value returned from the server-side call to the config service before rendering the AMP ad, instead of `hasAds`? As the code stands, this would happen. We can then make the client side call as well, to ensure that the value hasn't changed during the time this page has been cached. This will mean we won't have to make client side calls for all 41 services. The downside of this, is that when the call to the config service on the server does return false and subsequently returns true, we won't render an ad on the AMP page until the cache has been updated.
