### ISSUE TITLE
OD TV & Radio - player error on visiting new episode

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#7067]
On visiting https://www.test.bbc.com/burmese/bbc_burmese_tv/tv_programmes/w13xttn3 for the first time, the player gave the error ‘1065-The playlist contained no items’. This is a brand page showing the episode for today (29th June), so is new and the first time I have visited it. Refreshing the page fixed it.
It was fine on PAL.

![Image 29-06-2020 at 16 38](https://user-images.githubusercontent.com/54575620/86027488-ae108d80-ba28-11ea-91f2-f3054ac94d57.jpg)

We do not have Simorgh logging for this error. Could be SMP logs?

I got another error a different time, also visiting an OD TV brand page for the first time:

The error here is '1052 | Some sort of unavailability, the item failed to play ie page sent in crap.'. We can also see that the page is showing a different date to the json.

![Image 29-06-2020 at 17 02](https://user-images.githubusercontent.com/54575620/86030896-fe89ea00-ba2c-11ea-984d-612d3719d53c.jpg)
![Image 29-06-2020 at 17 03](https://user-images.githubusercontent.com/54575620/86030902-0053ad80-ba2d-11ea-8905-994eef1721fa.jpg)

Slack discussion on this issue https://bbcnews.slack.com/archives/CJT0284G2/p1593446702339800

**Comment by karinathomasbbc** [comment]
This can occur due to a couple of factors:
1. the packaging of radio / tv episodes after broadcast can take some time before they are available on demand
2. due to the pull (rather than push) mechanism for Nitro assets, there may be stale pages served occasionally

We're going to close this, because it is difficult to replicate, and also, there's probably not much that we can do to resolve it
