### ISSUE TITLE
Ensure Live and Test CSP is correct for Ads

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#7366]
**Is your feature request related to a problem? Please describe.**
We have implemented some changes to our content security policy for ads. We should ensure before going live that we test each service, and do not see any content security policy errors. If we do, we should ensure that the CSP is corrected.

This needs to be tested for both Canonical and AMP implementations.

Also test this using the querystring to use the live GNL script and flag any issues.

As a follow up to this, we will monitor CSP violations during the rollout to live. As we can release service by service using iSite, we can release the smallest service first, and disable ads while we update our CSP header if we encounter any live CSP violations that weren't picked up beforehand.

For example, we currently see the following on test:

```
Refused to load the image 'https://googleads.g.doubleclick.net/pagead/ide_cookie' because it violates the following Content Security Policy directive: "img-src https://ichef.bbci.co.uk https://ichef.test.bbci.co.uk https://ping.chartbeat.net https://a1.api.bbc.co.uk/hit.xiti https://logws1363.ati-host.net https://news.files.bbci.co.uk https://news.test.files.bbci.co.uk https://r.bbci.co.uk https://pagead2.googlesyndication.com https://securepubads.g.doubleclick.net https://tpc.googlesyndication.com https://www.google.com http://b.files.bbci.co.uk http://ping.chartbeat.net https://syndication.twitter.com https://platform.twitter.com https://pbs.twimg.com https://i.ytimg.com https://ton.twimg.com https://news.bbcimg.co.uk https://static.bbc.co.uk http://static.bbc.co.uk https://collector.effectivemeasure.net https://csi.gstatic.com https://sb.scorecardresearch.com https://secure-us.imrworldwide.com data: 'self'".
```

**Describe the solution you'd like**
Add any missing entries to the live and test CSP.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by amywalkerdev** [comment]
PR has been merged, this should be on test in about an hour so can be checked on the test env then

**Comment by PriyaKR** [comment]
Tested on test env noted these issues:
1. On FF,Safari and Chrome https://www.test.bbc.com/arabic.amp?site=test&renderer_env=live the ads doesnt seem to load the MPU ad becos of this warning  Secondary height 90 is smaller than 2/3rds of the primary height. (edited). 

2. Also if i test with live ads issue on chrome,FF and safari ie) https://www.test.bbc.com/hindi?site=live&renderer_env=live the ad slots are seen CSP issue is seen in the console  error in console - Refused to load the script`'https://pixel.adsafeprotected.com/jload?`anId=9708&campId=970x250&pubId=28402338&chanId=109528578&placementId=126120738&pubCreative=138259526429&pubOrder=121574418&cb=1413303163&custom=index&custom2=&custom3=leaderboard&adsafe_par&impId=' because it violates the following Content Security Policy directive: "script-src (edited) 

3. On FF seeing few more csp errors refer screenshot.
<img width="1306" alt="FF_CSP" src="https://user-images.githubusercontent.com/9802855/90665884-8e396100-e244-11ea-91b5-c67ceb36187f.png">

**Comment by PriyaKR** [comment]
> Tested on test env noted these issues:
> 
> 1. On FF,Safari and Chrome https://www.test.bbc.com/arabic.amp?site=test&renderer_env=live the ads doesnt seem to load the MPU ad becos of this warning  Secondary height 90 is smaller than 2/3rds of the primary height.  - raising a separate issue for this amp error
> 2. Also if i test with live ads issue on chrome,FF and safari ie) https://www.test.bbc.com/hindi?site=live&renderer_env=live the ad slots are seen CSP issue is seen in the console  error in console - Refused to load the script`'https://pixel.adsafeprotected.com/jload?`anId=9708&campId=970x250&pubId=28402338&chanId=109528578&placementId=126120738&pubCreative=138259526429&pubOrder=121574418&cb=1413303163&custom=index&custom2=&custom3=leaderboard&adsafe_par&impId=' because it violates the following Content Security Policy directive: "script-src (edited) - there is a follow up PR 
> 3. On FF seeing few more csp errors refer screenshot. - @tochwill is looking at this FF issue 
> 
> <img alt="FF_CSP" width="1306" src="https://user-images.githubusercontent.com/9802855/90665884-8e396100-e244-11ea-91b5-c67ceb36187f.png">

**Comment by PriyaKR** [comment]
Closing this as the FF `eval` error will be blocked always and other error `failed to load ....` is a FF private browsing issue which cant be resolved.
