### ISSUE TITLE
Reserve space to prevent content shifting when Ads are rendered on AMP

### ISSUE THREAD

**Issue by itimirichard** [bbc/simorgh#7380]
**Is your feature request related to a problem? Please describe.**
We use a combination of the values from the *config service* and *GeoIP* to determine whether or not display to show display Ads. We currently check the config service on the server but we will still be checking this on the client because the value of this may be outdated as AMP pages may have been in the AMP cache for long. These checks on the client will cause content reflow when the Ads are loaded in. 
This follows from this [investigation doc](https://paper.dropbox.com/doc/Investigation-Content-Shifting-for-Amp-Ads--A4sCkGZIdXzBvIBJz55uQ6SQAg-Rki4cZvd0cN56zFHuyB85)

**Describe the solution you'd like**

- We first check if we should render an ad on the server, using the value from the config service. If this value says we shouldn’t render an ad, then we won’t. No space reserved, no content shifting.
- If the config service says we should render an ad slot, then we do, and reserve the space for the ad on the server render.
- Inside this reserved space, on the client we call the config service again, to make sure the value hasn’t recently changed (as pages could be in the AMP cache for a long time). If this returns false now, we don’t render the ad into this reserved space.

So, we only render a space with no ad in if the config service has been switched from true to false in the time between the server render of the page, and the user accessing the page via the AMP cache. This will then cause the AMP cache to request a new version of the page, updating it to a version without ads for subsequent users.

Also considering geoip lookup:

- Inside the reserved space, we can check to see if the user is within the UK. If they are, we will not render an ad. This means that users will have the reserved empty space at the top of the page. This was deemed acceptable for initial release (although should be confirmed by Jon/Jim/Gail).

- Further investigation - can we collapse the space reserved for an ad once it is no longer in the viewport once we have the geoip response? Using different container types potentially?

### UX Specifications
**Min Screen Width**
If screen width is below minimum, Ads should not be shown
Leaderboard: 320px
MPU: 300px

**Content Shifting**
We are not allowing any content shifting on AMP Ads

### Ad Unit Size

Leaderboard | Mobile: [320px - 1007px] | Desktop: [1008px+]
-- | -- | --
Ad Units Served | 320px x 50px300px x 50px | 970px x 250px 728px x 90px

MPU | All Breakpoints
-- | --
Ad Units Served | 300px x 250px

### Rendering the Ad Slot

We will always render a space the width of the screen. We will then vary the Ad Slot height depending on breakpoint.

**Padding**
The additional space we need to render for the grey border around the largest Ad Unit for each Breakpoint.

Leaderboard - Group 1, 2, and 3: `8px` of padding
Leaderboard-  Custom Leaderboard Breakpoint: `16px` of padding
MPU - All Breakpoints: `8px` of padding

**‘Advertisement’ Link**
Above each Ad Unit should be a link with the word ‘Advertisement’, language varied on service. The size of the 'Advertisement’ link above the Ad Unit is `25px`. 

- Font size: 11 
- Colour:  `#3F3F42`
- Should be regular - not bold

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Got a couple of thoughts:

- Can we drop support for the large leaderboard on AMP? I got these stats for browser window width for each page view on AMP pages, and how many of these views are for browser windows above 720px, and above 1008px.

For July 2020:

**Global**
Total: 92722110

Above 1008: 229872
Percentage above 1008: 0.25%

Above 720: 635237
Percentage above 720: 0.69%

**Mundo**
Total: 22003104

Above 1008: 51010
Percentage above 1008: 0.23%

Above 720: 137492
Percentage above 720: 0.62%

**Arabic**
Total: 4406045

Above 1008: 7917
Percentage above 1008: 0.18%

Above 720: 25615
Percentage above 720: 0.58%

**Afrique**
Total: 668144

Above 1008: 2046
Percentage above 1008: 0.31%

Above 720: 5512
Percentage above 720: 0.82%

**Hindi**
Total: 12313873

Above 1008: 4387
Percentage above 1008: 0.04%

Above 720: 48055
Percentage above 720: 0.39%

**Portuguese**
Total: 8076705

Above 1008: 18836
Percentage above 1008: 0.23%

Above 720: 45179
Percentage above 720: 0.56%

**Russian**
Total: 6902676

Above 1008: 56927
Percentage above 1008: 0.82%

Above 720: 117867
Percentage above 720: 1.71%

**Zhongwen**
Total: 1183264

Above 1008: 2954
Percentage above 1008: 0.25%

Above 720: 7726
Percentage above 720: 0.65%

- If we can, how do we feel about reserving space on the server render for AMP ads, and then collapsing immediately when we get the amp-geo data back? We could set a min-height when we have the `.amp-geo-pending` class, and then remove it when this is replaced with the uk geo group, but keep it otherwise? This should happen as soon as the amp-geo JS is loaded.
