### ISSUE TITLE
Use single regex everywhere

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#789]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**

**Comment by ChrisBAshton** [comment]
Can you fill out this issue or close it?

**Comment by ChrisBAshton** [comment]
Closing old issue.

**Comment by bcmn** [comment]
Just to clarify what I believe this was referring to -- we used to have multiple definitions of the same regex to check if something matches the `/service/articles/articleID` pattern.

Jordan & I ended up doing this in #803, a few days after this issue was opened -- the [InlineLink (New Remix)](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/InlineLink/index.new.jsx#L15-L18) now uses the same regex as `routes/index.js`. I had a look, but I can't see any additional places where this should be used.
