### ISSUE TITLE
Investigate setting the background colour below share tools/headling

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#802]
UX of the page has an oat background below the share tools/headline: #417.

There are many ways to do this, and we need to investigate what would be the most appropriate. Examples of what these might be are:
- Using CSS grid rows, and setting the background colour of top row(s)/subsequent rows - would need a non-grid fallback
- Defaulting the page to oat, and setting the headline as non-oat (could be non-grid non-fallback?)
- Splitting data below the headline

The investigation should not be limited to just these options if there are others available.

The investigation must consider the ability for flexibility of adding blocks above the headline (which would maintain the white background), but it will not be implemented in #417.

**Comment by bcmn** [comment]
Phil has a [Codepen](https://codepen.io/pjlee11/pen/ZMBmJd) exploring this.

**Comment by bcmn** [comment]
Refinement with Jordan: Clarified that everything above headline should have white background, & that no tests would be expected for an investigation.

**Comment by pjlee11** [comment]
During the investigation I realised that the 10 columns we implement to align with the UX design are based on a max-width of 1280px. We then use margin's to centre the content contained within the 1280px grid. Margin's are exclusive of the background colour and therefore we are not able to set the background colour to the full width of the browser whilst in the 1280px max-width wrapper. Because of this we could change our implementation so that the white backgrounded content and $oat backgrounded content are seperate full width divs that are siblings. 

Previous:
```
<main class="StyledMainContent" role="main">
  <div class="StyleGridWrapper">
    <div class="GridItem">
      <h1 class="Headline">Royal wedding 2018: Bouquet laid on tomb of unknown warrior</h1>
      <figure class="Figure">...</figure>
    </div>
  </div>
</main>
```

Suggested change:
```
<main role="main">
  <div class="StyledTitleDiv">
    <div class="StyledGridWrapper">
      <div class="GridItem">
        <h1 class="Headline">Royal wedding 2018: Bouquet laid on tomb of unknown warrior</h1>
      </div>
    </div>
  </div>
  <div class="StyledBodyDiv">
    <div class="StyledGridWrapper">
      <div class="GridItem">
        <figure class="Figure">...</figure>
      </div>
    </div>
  </div>
</main>
```

This has been captured in the branch `investigation-split-out-headline-blocks` see the comparison [here](https://github.com/BBC-News/simorgh/compare/investigation-split-out-headline-blocks?expand=1)

**Comment by pjlee11** [comment]
Further investigation using CSS grid has been captured in the branch `investigate-full-width-grid-implemenation` see the comparison [here](https://github.com/BBC-News/simorgh/compare/investigate-full-width-grid-implemenation?expand=1)

Pros:
- Allows for easy integration of the onward journey component
- Very flexible layouts as each component is a grid row and has the ability to be full width across all columns
- Data does not need to be split

Caveats: 
- We have to hardcode the column width to take into account grid gaps manually due to having a flexible width columns either side of the defined main content. This is required because otherwise the grid gaps affect the width of the main content grid (see Screenshot for working example)
- Paddings need to be added to the grid item instead of the wrapper (needed to allow for full width)
- As `<main>` has the grid columns definition the headline row needs to be a full width item so it can be coloured white. Then to align the headline content with the rest of the document the grid columns need to be added again and then a grid item is required inside the new grid. This means the headline content is contained in a nested grid.

## Examples ##
### Headline ###

```
<StyledMainContent>
  <GridItemFullWidth>
    <StyledHeadlineWrapper>
      <GridItem>
        <Headline />
      </GridItem>
    </StyledHeadlineWrapper>
  </GridItemFullWidth>
</StyledMainContent>
```

### Normal Block ###
```
<StyledMainContent>
  <GridItem>
    <Block />
  </GridItem>
</StyledMainContent>
```

### Full Width Block ###
```
<StyledMainContent>
  <GridItemFullWidth>
    <Block />
  </GridItemFullWidth>
</StyledMainContent>
```

## Screenshot ##
![image](https://user-images.githubusercontent.com/7791726/47154091-40b2dc80-d2d9-11e8-882f-596b55bb8916.png)

**Comment by pjlee11** [comment]
Following the investigation my suggestion would be to use CSS grid and confirm with UX what level of fallback is required for browser that do not support grid.

**Comment by BogdanDogaru** [comment]
Closing as the investigation informed other issues and PRs.
