### ISSUE TITLE
Incorrect dependencies / devDependencies

### ISSUE THREAD

**Issue by dgm34** [bbc/simorgh#82]
**Describe the bug**
It appears as though you have some packages in the `dependencies` section of your `package.json` that ought to be in `devDependencies` instead. Examples include https://github.com/bbc/simorgh/blob/latest/package.json#L34-L41 and https://github.com/bbc/simorgh/blob/latest/package.json#L44

**To Reproduce**
Can be observed in https://github.com/bbc/simorgh/blob/latest/package.json and will be apparent in the `node_modules` folder when the app is installed via `npm install simorgh`

**Expected behavior**
Packages such as `eslint-config-airbnb` are not needed when `simorgh` is installed via `npm install simorgh` on a production server and should therefore not be installed.
 
**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Node v10.0.0, npm 6.1.0

**Additional context**
This could have been an oversight / misunderstanding or it could be that you have a lint rule jobby enforcing this. If the latter, I think the rule needs fixing too.

![columbo](https://user-images.githubusercontent.com/7823438/41222558-29f5b22c-6d5f-11e8-8014-335f633af4e4.jpg)

**Comment by jtart** [comment]
@dgm34 this is currently intentional as the production Webpack build (through Razzle) also lints the source code.

The most appropriate course of action would be to disable that step on the production build as linting is executed in previous steps, and then could move the above deps to devDeps. The separation (or lack of it) of deps is quite innocuous to the runtime of the application, so not _too_ much of an issue.

I do agree they should ultimately be separated.

**Comment by jamesbhobbs** [comment]
So we patch fixed this in the PR above, specifically [this file](https://github.com/bbc/simorgh/blob/2e62047b83f01459dde042d0931f6baa99280d6a/razzle.config.js).

A longer-term fix seems to be https://github.com/jaredpalmer/razzle/issues/607 which we should contribute to. We can then have this plugin as a dev dependency.
