### ISSUE TITLE
Issue with lazy loading of images on Russian article pages in Portrait mode on Iphone

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#8954]
1. Go to https://www.bbc.com/russian/news-56320777 on an iPhone.
2. There is an issue with lazy loading of images for russian article pages.
3. Some images load only partially and the only way to fix them is to turn the phone to landscape, which reloads the images, and then back to portrait. 
4. This is not hapenning on all article pages though.
![IMG_2E3FC0DABAE4-1](https://user-images.githubusercontent.com/1379277/110339591-3c112f00-8020-11eb-908b-4dedfb66770f.jpeg)

4. Attached is the screenshot.

**Comment by HarveyPeachey** [comment]
# Investigation So Far
## Reproducing the Bug
### Live
From my investigation this bug is happening on Chrome and Safari on the latest version of iOS, I have not tested other browsers. The bug happens intermittently on the live site and is prevalent on all the WS language sites. The bug happens intermittently and seems to be caused by either our Lazy Loading implementation, or the preload we use for images. It is also not just the leading image, it can happen to any image in the page body from what I've seen.

To reproduce you need to keep clicking on different articles until you see an image that is partly rendered. 

### Local
As of now I cannot reproduce the bug locally on my iPhone on safari or chrome. I have used the instructions [here](https://github.com/bbc/simorgh/blob/latest/docs/A11y-Testing-Cross-Device.md) to expose Simorgh on my local network so I can attempt to recreate the bug. Then I used the instructions [here](https://github.com/bbc/simorgh/blob/latest/docs/A11y-Testing-Cross-Device.md) to run the live bundles and access the live articles to make reproducing the bug easier. Now this causes another issue were only the leading image gets loaded in and the other images won't lazy load back in, there might be some config changes I need to make to get them working. But when trying to reproduce the bug using the leading image I cannot seem to do it. 

One method I haven't tried is not running the live bundle and just importing a bunch of assets and creating a temporary asset that provides a link to them, so we can easily hop between story pages to try and reproduce it

## Analysing the bug on Live
### Investigating on iPhone Safari
I first tried to pinpoint whether this is a rendering problem or the browser not loading the full image. From investigating a bugged picture on iOS, I used the safari save pop out feature to isolate the image and save the image as shown below:

![safari-pop-up-image-ui](https://user-images.githubusercontent.com/4706195/118008920-7c08d100-b345-11eb-86c5-7f3a483dbe47.gif)


As you can when popping the image out, iOS is rendering a part of the image and leaving white space on the rest of the image, but once I click save on the image, the full image get saved successfully with no white section. This kind of points to it maybe being a rendering bug with iOS, in conjunction with our use of [react-lazy-load](https://www.npmjs.com/package/react-lazyload) or our usage of image [preloading](https://github.com/bbc/simorgh/blob/1aec8181f08d9880de0e893bf15f8342ce732769/src/app/containers/ImageWithPlaceholder/index.jsx#L47).

### Using Safari DevTools
I tried to further debug by connecting my iPhone to my Mac and using the debug feature in Safari. When loading a story with this bug, there were no console errors or warnings that would point to a cause. I then compared viewing the site from my mobile and also viewing the site from Safari on Mac to check if the memory size of the image was different:

![Screenshot 2021-05-12 at 11 30 09](https://user-images.githubusercontent.com/4706195/118009054-9e025380-b345-11eb-8e01-765cf4641c1b.png)

From the above image it looks like the image has been fully downloaded on the iPhone (Left table) when the bug is present, so it looks like it's probably not an issue with the loading of the image but the rendering of it, there is a small size difference but I think that's due to compression and it doesn't really correlate as 3/4 of the image didn't show.

I then used the DevTools further by changing the images width, I changed from `100%` to `99%` back and forth to see what happens, but the bug was still there. I then disable the width value completely, and when I did that the whole image rendered, and turning it back on the image returned to its normal size, looking completely fine:

![ezgif-3-afac8c42d5d7](https://user-images.githubusercontent.com/4706195/118009916-6ba52600-b346-11eb-9a4e-3a521f14d261.gif)

## Summary
Due to not being able to figure out how to replicate this locally, I can't easily start attempting to find a fix, as I won't know if my changes are doing anything. I suspect it's to do with our lazy-loading implementation or our preloading not behaving nicely with the way iOS renders images. The next step really is trying to get it reproducing on a local build or it will have to be one of those situations where we make changes and maybe launch it onto the test/staging site, but before that, we should make sure we can reproduce the bug on those environments as well.

**Comment by mukama** [comment]
**Update:** 
This issues extends to Safari for MacOS as well. For some reason, Safari seems to struggle when automatically choosing the best way to decode images automatically. By default, browsers use `decoding="auto"` for their HTML Image elements. 

Therefore, one way to troubleshoot the issue is to try adding either `decoding="async"` or `decoding="sync"` for Safari-based browsers and observing the outcome. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding

**Safari 13.0.3 on MacOS 11.2.3 Screenshot:**
![image](https://user-images.githubusercontent.com/2413911/122444850-a33c6900-cfa9-11eb-9262-53142611a4f2.png)

**Comment by paruchurisilpa** [comment]
Checked on Safari with various articles, refreshed few times. Unable to recreate, so happy to consider it as fixed :)

* https://www.bbc.com/russian/news-56320777 
* https://www.bbc.com/russian/news-57807139
* https://www.bbc.com/russian/news-57830671

**Comment by gavinspence** [comment]
Getting reports from Editorial that this issue is happening again. 

Retested on Chrome & Safari and occasionally seeing this issue happening again.

![IMG_1377](https://user-images.githubusercontent.com/52488258/129157827-f6c03338-6e2c-4dac-af34-e4a362dcf619.PNG)
![IMG_1378](https://user-images.githubusercontent.com/52488258/129157856-c78646b0-5c1b-4c1d-96ff-b20907afadcc.PNG)

**Comment by mukama** [comment]
Reopening this ticket because the issue is still happening

**Comment by jroebu14** [comment]
I've noticed that these images have a srcset attribute but not a sizes attribute meaning that the browser is likely to download and render the biggest image from the srcset list at all resolutions which could be causing this issue. Example of fix https://github.com/bbc/simorgh/pull/9436

**Comment by paruchurisilpa** [comment]
Checked on LIVE using the following links on an iPhone and also clicked around few links, seems like the problem is fixed.
https://www.bbc.com/russian/news-53473369
https://www.bbc.com/russian/features-45782775
https://www.bbc.com/russian/media-45527896
https://www.bbc.com/russian/articles/c6ygxgl53w9o
