### ISSUE TITLE
Article video player requires 2 clicks to play video and play button is not aligned correctly after first click for RTL languages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9299]
**Describe the bug**
Article video player requires 2 clicks to play video and play button is not aligned correctly after first click for RTL languages.

https://user-images.githubusercontent.com/4798332/128338800-26f45171-580a-4ba1-900c-cf63dce15712.mp4

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/persian/articles/cej3lzd5e0go
2. Scroll to the video player and click on it (this is actually a placeholder image)
3. Observe the placeholder image being swapped for the video and not autoplaying and the play button being left-aligned when it should be right aligned for RTL languages.

**Expected behaviour**
Video player in articles should only need 1 click to play and the play button should be left-aligned for LTR languages and righ-aligned for RTL languages.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by pvaliani** [comment]
Is this a "good first issue"?

**Comment by joshcoventry** [comment]
@gavinspence Looks like this is a bug with the old player. With the move to Toucan does this need to be fixed?

**Comment by DarioR01** [comment]
I am currently working on this [bug ticket.](https://github.com/bbc/simorgh/issues/9299)
This behaviour happens because Safari does not support [Feature-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay), therefore this [line](https://github.com/bbc/simorgh/blob/976a93dfb0155c8a9897557a745eefc80b787d38/src/app/components/MediaPlayer/Canonical/index.jsx#L87) of code will not make the iFrame content autoplay.
I had a look at the following [documentation](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari) from apple on how to Deliver Video Content for Safari... long story short we could start ask users [access to their cameras](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari#3030252) :stuck_out_tongue:, or refactor to use a video that plays with no sound :hear_no_evil: (I don't even know if that is feasible).

Looking at the above the only reasonable fix is to remove the media-player placeholder. This should allow user to click only once, but this solution comes with it's dose of issues :smile:. The first as showed by the bug ticket: The button will be on the left side of the player on a rtl service...

**Comment by DarioR01** [comment]
Given this is an Optimo only thing, and we don't have many services publishing, we will ignore this until we update to Toucan across Simorgh.
