### ISSUE TITLE
Fix errors that bring Lighthouse benchmarks below threshold

### ISSUE THREAD

**Issue by radiocontrolled** [bbc/simorgh#949]
**Describe the bug**

Per https://github.com/BBC-News/simorgh/issues/331 we want to ensure scores meet: 

Performance >= 90
PWA - requires analysis as which score to meet
Best practices = 100
Accessibility = 100
SEO = 100

<img width="849" alt="screen shot 2018-11-14 at 14 46 44" src="https://user-images.githubusercontent.com/916416/48489966-3b837780-e81c-11e8-9392-98bef59c178d.png">

We need to identify where scores are falling short and address this. Lighthouse results as not always consistent locally or in Travis and there will be some variance in scores. Part of fixing these errors could include getting average scores after multiple runs (potentially creating a second issue to adapt our script to do this, or creating an issue to capture performance over time).

**To Reproduce**
Examine results of local and Travis lighthouse runs. 
Thresholds are set in `simorgh/lighthouse.js` (https://github.com/BBC-News/simorgh/pull/876)

**Definition of done**
Scores meet thresholds.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
Currently, one of the failing tests when run locally is this mismatch between localhost & www.bbc.com  
<img width="727" alt="screen shot 2019-01-07 at 11 40 55" src="https://user-images.githubusercontent.com/3028997/50766445-243b9600-1271-11e9-866d-4156e1e48c74.png">
There are a few different ways of handling this:
1) disable this single check when running lighthouse on localhost & Test environments.
2) update our application to have a variable for the canonical link host  https://github.com/BBC-News/simorgh/blob/e430f572903ada27e1d28c659de537a73848ad3a/src/app/containers/Metadata/index.test.jsx#L112

**Comment by ChrisBAshton** [comment]
Note: Lighthouse is quite flaky, the 'actual' result returned varies. Sometimes returns null. So may want to run multiple times & take an average or take the highest.

Come back to refine later - perhaps when we've cemented the concept of 'adhoc environments'.

**Comment by sareh** [comment]
For best practice, we have failing tests due to not using H/2.  We will not be able to serve these assets via H/2 soon. 
<img width="762" alt="screen shot 2019-01-07 at 11 48 46" src="https://user-images.githubusercontent.com/3028997/50766955-0cfda800-1273-11e9-879a-ed5e612d4f9a.png">


We could reduce our threshold to 90% and open separate issue to investigate moving assets to be served via H/2.

**Comment by sareh** [comment]
```
Document does not have a valid rel=canonical
Points to a different domain (https://www.bbc.com/news/articles/c85pqyj5m2ko)
````
We have not found a way to ensure we update the base URL in a way that works across various environments.  

Option 1 
Use the enviroment variable SIMORGH_BASE_URL for the Canonical link in the Metadata https://github.com/BBC-News/simorgh/blob/e430f572903ada27e1d28c659de537a73848ad3a/src/app/containers/Metadata/index.test.jsx#L112

Option 2
Disable this Best Practice test only on Local and Test environments. Run it against the Live environment. 

Our preference is option 1. 
However, when branching off the 'remove razzle' branch (https://github.com/BBC-News/simorgh/pull/1117) and updating the `.env` file's `SIMORGH_BASE_URL` to be `https://www.test.bbc.com`


We prefer to *not* disable tests, to retain visibility of tests that are not passing.

```
Document does not have a meta description
Description text is empty.
```
This is the case on the Test & Live environments, until the Optimo team provide a Promo Summary string. (https://www.test.bbc.com/news/articles/c85pqyj5m2ko) & (https://simorgh.api.bbci.co.uk/news/articles/c85pqyj5m2ko)

SEO - `Page is blocked from indexing` - this is an active choice, since we're preventing indexing prior to going live. 

```
Does not use HTTP/2 for all of its resources
```
This is only an error when running locally. assets are served over H/2 on Test & Live. 
We suggest setting the threshold for Best Practices at 80 and for SEO at 90 for this current Issue. We will raise other issues to increase the Lighthouse score of the application.

**Comment by bcmn** [comment]
We intend to split the individual issues above out into their own issues, for better granularly tracking the blockers, etc.

**Comment by bcmn** [comment]
Issue 1: Canonical URL -- #1141
Issue 2: Description -- #1138 & #842 (Duplicates?)
Issue 3: Page is blocked from indexing -- #1139 
Issue 4: HTTP/2 -- #1140

**Comment by ChrisBAshton** [comment]
Thanks both.
