### ISSUE TITLE
Replaced by 9731 - Track lists with links in the article (Simplified)

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9604]
**Is your feature request related to a problem? Please describe.**
Enable tracking on the lists within the article that will send a single view event when a list is in view and a single click event if any link within the list is clicked.

Only lists with containing links will be tracked

The content of the view and click event must be the same for the list so ATI can calculate the click/view value.

~~Each list should be treated separately~~

Internal and external links will send the same type of click event

~~Multiple lists can be present on the page so set a count in the campaign eg bullet01~~

Example list with link: https://www.bbc.com/portuguese/brasil-59057279
![image](https://user-images.githubusercontent.com/16046375/140044571-2f36f021-2ac1-4030-a40d-fb338118c2a2.png)

**Describe the solution you'd like**
Send a block level view interaction event when the list is in the viewpoint but only if the list contains a link in any list item

Send a block level click event if any link within the list is clicked

~~Send the list number of the block as part of the creation field, e.g. bullet01 for the 1st list on the page bullet02 for the 2nd etc~~

Set the format field for each event as 'bullet'  

Example (ATI beacon)
``
ati=PUB-[camapignID]-[Creation]-[variant]-[format]-[general]-[detailed]-[adverts]-[url]
&type=AT 
``
 Example call (with Creation and format values)
``
ati=PUB-[article-sty]-[bullet]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]
``
 

**Describe alternatives you've considered**

**Testing notes**
CPS Test article: https://www.test.bbc.com/pidgin/tori-23463103

Description
Check if the list is seen

Given at least 1 link is in the list
and 50% of list item in the list is in view for more than 1 second
When I check ATI tracking
Then I can see the view beacon send for the list

Description
Check ATI tracking when a link in the list has been clicked

Given I click any link in the list
When I check ATI tracking
Then I can see the click beacon for the list

 
Description
Check ATI tracking shows the correct page for the list

Given I view/click any link in the block
When I check ATI tracking
Then I can see the CampaignID value matches the page where the block is located

Description
Only track if list contains a link

Given there are no links is in the  list
When I check ATI tracking
Then I don't see the view beacon as this block should not be tracked

Description
Track single list on the page

Given the page has a single list which contains links
When I check ATI tracking
Then I can see the view beacon for this list
AND I should see the following:
creation:bullet
format:CHD=bullet
``
ati=PUB-[article-sty]-[bullet]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]
``
 

Description
Track multiple bullet lists on the page

Given the page has three lists which contains links
When any list is in the viewport 
AND I check ATI tracking
Then I can see a single view beacon for these lists
and the beacon has a creation value of bullet
 
``
ati=PUB-[article-sty]-[bullet]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]
``

Description
Track internal and external links

Given the page has a list that contains links
AND the links are internal or external or a mix of both
AND I click any of the link
When I check ATI tracking
Then I all links send the same beacon value
View beacon
``
ati=PUB-[article-sty]-[bullet]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]
``

Click becon (for any link of any type) 
``
atc=PUB-[article-sty]-[bullet]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]
``

[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by ryanmccombe** [comment]
**Some technical notes:**

This component is a good frame of reference for a similar scenario:

https://github.com/bbc/simorgh/blob/a2c9ed2a5d23a1e39b922385612a0ccec34a4566/src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx#L25-L26

Note the references are created at the “list” level, so there will only be one event sent per list, as per the requirements

The references are then passed down to each list item: https://github.com/bbc/simorgh/blob/a2c9ed2a5d23a1e39b922385612a0ccec34a4566/src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx#L123-L126

For the click tracker, the link is it's final destination so it gets attached there as the `onClick`.  For the view tracker, it needs attached to a child component, so it gets passed down as a prop, and the child component can then grab it and do what it needs to do.

For the above example, the viewTracker ref is passed down from `RecentAudioEpisodes` to `EpisodeList/Episode` where it is then attached as a ref like this: https://github.com/bbc/simorgh/blob/cfb1178b4251e29419cfcafcd249f8c7060dd3fa/src/app/containers/EpisodeList/Episode.jsx#L39

That example passed the ref down as a prop called `ref`, but I wouldn't recommend doing that, at least initially.  Refs can be passed down to child components as standard props, eg `<MyComponent clickHandlerRef={someRef} viewTrackerRef={anotherRef} />` and then within their final destination, pass them as a “ref” in the case of a view tracker, eg `ref={viewTrackerRef}` or an `onClick` in the case of a click tracker eg `onClick={clickTrackerRef}`.

I’d recommend doing it this way, at least initially.  If you can get it working that way, you can consider refactoring it to use `forwardRef` for the viewTracker instead, which might be cleaner, but not necessarily.    That looks a bit like this commit: https://github.com/bbc/simorgh/commit/a2c9ed2a5d23a1e39b922385612a0ccec34a4566

In terms of how this stuff relates to this ticket specifically, the 3 relevant components are:

Bullet List: https://github.com/bbc/simorgh/blob/latest/src/app/containers/BulletedList/index.jsx
Bullet List Item: https://github.com/bbc/simorgh/blob/latest/src/app/containers/BulletedListItem/index.jsx
Inline Link: https://github.com/bbc/simorgh/blob/latest/src/app/containers/InlineLink/index.jsx

So, I think the `useClickTracker` and `useViewTracker` refs would need created at the `BulletList` component, and then passed down to the `BulletListItem` component, and then passed down further to the `InlineLink` component.

There, the `viewTrackerRef` can be passed as the `ref` and the `clickTrackerRef` passed as the `onClick` of the `InternalInlineLink` and `InlineLink` elements used in that component.  Note this `InlineLink` is used in other places too, so we can't assume that it will always be receiving the view tracker and click tracker references.

**Getting The Data**

The view and click handler needs data in order to generate the ATI string like `ati=PUB-[article-sty]-[bullet01]-[]-[CHD=bullet]-[world::pidgin.world.story.58813752.page]-[]-[]-[]`

The view and click tracker handler accepts some arguments to help it build that string: https://github.com/bbc/simorgh/blob/cfb1178b4251e29419cfcafcd249f8c7060dd3fa/src/app/hooks/useViewTracker/README.md#props

I'm not at all sure how those props match up to the generated string, so would recommend some trial and error.  The ATI request can be seen in the browser network tab, once you scroll one of the tracked elements into view.

Some of the arguments will need to be dynamically generated.  The request context would have some stuff that can help with that.  You can import it, as well as `useContext`:

```
import React, { useContext } from 'react';
import { RequestContext } from '#contexts/RequestContext';
```

And then inside the component:

```
const usefulStuff = useContext(RequestContext);
console.log(usefulStuff);
```

Note I spoke to Jon about this requirement: “Multiple lists can be present on the page so set a count in the campaign eg bullet01”

He confirmed this numbering was not necessary - rather, the campaign just needs to be unique for each bulleted list.  So, instead of the number, it would be lot easier to use the ID, which should be available within the `BulletedList` component as `props.id`.

So, rather than `bullet-01` we could have something like `bullet-c9bd8680-8894-47ad-aa39-36afc66bcf13` or feel free to shorten it to the first few characters, eg `bullet-c9b`

**Comment by JonBeeb** [comment]
After talkng with @nicola-d-bbc we are going to simplify this:
Send a single view event called 'bullet' if any bullet list is in view (event if there are multiple lists)
Sending a click event called 'bullet' if any link is clicked

The sequential naming (bullet01, bullet02 etc) will be split into a separate ticket.
