### ISSUE TITLE
CMD Click (Mac) events not opening new tab when click tracking is in use

### ISSUE THREAD

**Issue by pvaliani** [bbc/simorgh#9679]
**Describe the bug**
Recent work completed to incorporate view and click tracking to bulleted lists has highlighted that our `clickTrackerHandler` does not allow users to open a new tab in the browser when command-clicking (CMD + Left Click) a link (Chrome or FireFox) for components incorporating click tracking.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/portuguese/podcasts/p07r3r3t' or 'https://www.bbc.com/pidgin/tori-59293906'
2. Press CMD + Left Click on an External Link (Portuguese) or topic tag under 'Topics Wey Dem Resemble' (Pidgin)
3. Notice that a new tab does not open in the browser 

**Expected behaviour**
CMD + Left Click should open a new tab in the browser. 

**Screenshots**

**Desktop (please complete the following information):**

Issue is happening on Chrome, Edge, Safari and FF

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
Documentation for the clickTrackerHandler is here:

https://github.com/bbc/simorgh/tree/latest/src/app/hooks/useClickTrackerHandler

**Comment by pvaliani** [comment]
We believe the bug is contained in the logic of these lines:

https://github.com/bbc/simorgh/blob/2293d16dbfad461b51ee5db26f0e5c62a8f1ef09/src/app/hooks/useClickTrackerHandler/index.jsx#L75-L76

**Comment by MuhammadAHussain** [comment]
Having investigated the issue, it looks like [`preventDefault`](https://github.com/bbc/simorgh/blob/8b3989f68f144ce3273892b093daaabcd85988c3/src/app/hooks/useClickTrackerHandler/index.jsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L58) is not allowing the click through to happen. This`preventDefault` is needed as it can cause problems with sending the ati event without it.

Had a look at using `window.open` instead of `assign` when the CMD/CTRL key is pressed however there are issues around using `open`, one of them being popups are blocked by default on modern browsers (https://developer.mozilla.org/en-US/docs/Web/API/Window/open).
