### ISSUE TITLE
Horizontal scroll promos - not scrollable on Opera Mini Extreme 

### ISSUE THREAD

**Issue by skwong25** [bbc/simorgh#9796]
**Describe the bug**
Horizontal scroll does not work for multi-card promos.
Any cards beyond the first are not fully visible. Content is not accessible. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to links on test:
* https://www.test.bbc.com/arabic/articles/cjn2e0jek55o (RTL script) 
* https://www.test.bbc.com/pidgin/articles/crrrkxz2k0ko
2. Scroll down to view multi-card promos
3. Attempt to scroll with horizontal finger swipe

**Expected behaviour**
Row of cards should be scrollable to show additional cards and allow links to be clicked. 

**Smartphone (please complete the following information):**

- Device: Google Pixel 5A
- OS: Android
- Browser: Opera Mini - Extreme Mode
- Version:  61.x

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
See original issue/ feature request ticket #9697 
Fixed by Pull Request #9729

A Psammead issue [#3099](https://github.com/bbc/psammead/issues/3099) was previously raised, affecting scrollable banner menu.
This was not fixed as the hidden content can still be accessible via the burger menu.

**Comment by DarioR01** [comment]
After some consideration we decided that this bug is still not fixable.
What we are planning to do from now is to crate a different experience for opera mini users.
We can use this [utility tool](https://github.com/bbc/simorgh/tree/latest/src/app/lib/utilities/isOperaProxy) to make style changes only to opera-mini.

For opera-mini we will be using stack cards instead of scrollable cards. The cards will have the same height but will be as width as the article (same width behaviour as paragraphs).
