### ISSUE TITLE
Use `data-hero` for AMP images

### ISSUE THREAD

**Issue by eagerterrier** [bbc/simorgh#9801]
In order to improve LCP on AMP pages, I've come across an article that suggest the use of `data-hero` tag

https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/optimize_amp/#preload-hero-images

**Describe the solution you'd like**
For `amp-image` tags to use `data-hero` attribute.
data-hero should only be applied to the "[hero image](https://en.wikipedia.org/wiki/Hero_image)" (first image on page). This is to avoid blocking bandwidth for other critical resources. [more here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization)

**Testing notes**
[Tester to complete]

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Comment by HarveyPeachey** [comment]
Just to help with extra context on this `data-hero` attribute, we actually might already have this functionality contributing to our core web vital scores already.

When a user visits an article rendered through Simorgh on a mobile device, the majority visit the page through Googles amp cache as shown below (You can see it's served through google's domain at the top):

https://user-images.githubusercontent.com/4706195/153574995-d93278cf-24e8-4671-82e6-83d74902b0cd.MP4

Google's AMP cache runs our amp pages through an [AMP Optimiser](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/?format=websites) already, and from looking at implementing our own AMP optimiser on our origin domains, most of our audience aren't actually viewing AMP pages on our origin domain. So because Google's AMP cache is running our pages through their AMP Optimiser, it's probably automatically adding the `data-hero` attribute already, outlined [here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/#hero-image-optimization).

The main question is checking if those pages do in fact have the `data-hero` attribute, and that our core web vital scores are mostly coming from Google's AMP cache for example https://www.google.com/amp/s/www.bbc.com/mundo.amp or our origin domain https://bbc.com/mundo.amp for example. @aeroplanejane @gavinspence Did we ever get an answer about this?

It still might be worth implementing this anyway and we can compare core web vitals over a period of time to see if it does make a difference, kind of similar to testing out the AMP optimiser, although this should have no performance impact on our server.

**Comment by DarioR01** [comment]
After some research, we discovered that the cache optimizer should automatically inject data-hero images to our amp-images. [more here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization)

By analyzing one of our amp pages from mobile we discovered that the optimizer that the cache uses does not automatically inject data-hero images in our code as suggested above.
I assume this is happening because the optimizer does not detect large images in the first viewport.

An easy fix is as suggested by this ticket to implicitly add data-hero to our amp-images.

To replicate the above:
1. Follow these steps: https://developer.chrome.com/docs/devtools/remote-debugging/#debug
2. Navigate to https://www.google.com/amp/s/www.bbc.com/mundo/noticias-60170873.amp on your mobile
3. in the inspector tab identify the page HTML (remove all the google dev tool junkiness)
4. Notice how there are no `data-hero` nor `link rel=preload` keywords.

Amp page we analyzed:
[ampArticle.html.zip](https://github.com/bbc/simorgh/files/8048695/ampArticle.html.zip)
